### PR TITLE
fix running tests on Windows

### PR DESCRIPTION
**Pull request by warpech**
### Context
The test npm run-scripts are failing on Windows because the env variable set by `cross-env` is not passed to `jest` testing framework.

### How has this been tested?
Execute `npm run test` in CMD and Git Bash on Windows and verify that all test suites are executed.

**Note**: 3 tests of Walkontable are failing on Windows, but that is unrelated to this PR. This PR brings developers on Windows closer to fixing that.

image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #5878
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wojciechczerniak** [comment]
Thanks. I've linked the #5878 issue and assigned a reviewer.

**Comment by warpech** [comment]
> and that's true, all of the files return an Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style error, but it's caused by the git configuration. We should probably mention it somewhere in our docs, @wojciechczerniak?

Yeah, that's not a problem of my PR. That's a problem that our ESLint configuration expects different Git setup than the different set up on Windows.

I fixed the problem for myself by adding `text eol=lf` in `.gitattributes` for this repo, as explained in https://help.github.com/en/articles/configuring-git-to-handle-line-endings. Perhaps the current entry in https://github.com/handsontable/handsontable/blob/22dc4bd29f61ecd9611f7ff6869acaff0dcb1839/.gitattributes should be changed?

Should I merge or fix .gitattributes and/or tests?

**Comment by jansiegel** [comment]
> Should I merge or fix .gitattributes and/or tests?

I think so, it seems to fix the problem + I'm not sure if `text=crlf` (which is currently in the repo)  is even a valid format for `.gitattributes`.

**Comment by warpech** [comment]
I pushed a change in `.gitattributes` that uses LF as the line ending on all systems. Tested on Windows by making a fresh clone:

```
git clone --single-branch --branch feature/fix-tests-windows git@github.com:handsontable/handsontable.git handsontable-tmp
cd handsontable-tmp
npm install
npm run lint
```

**Comment by jansiegel** [comment]
Did the exact same thing on my end, looks good to me!

**Comment by warpech** [comment]
I also pushed a fix for scrolling tests that were failing due to a timeout.

There are, however, 2 tests that are failing due to 1px rendering offset mismatch between Windows and MacOS when calling `wtScroll.scrollViewportVertically`. I don't know how to fix these quickly, so I will just leave them failing, I guess...

image

**Comment by warpech** [comment]
Creted the issue https://github.com/handsontable/handsontable/issues/6141

**Pull request merged**
