### PR TITLE
Refactoring of walkontable

### PR DESCRIPTION
**Pull request by Siemienik**
### Context

In this PR, I did several steps of refactoring, which target to improve the developer experience while developing to Walkontable. The primary assumption was to loosen the relations between internal components. To accomplish that, I introduce the Inversion of Control with Dependency Injection through constructors wherever where it was able. That allows to introduction one-directional relation tree (in most cases). However, some classes have circular dependencies by referencing Walkontable (Core) class. This makes it impossible without deeper changes to the unification direction of relations. For that reason, I introduced Data Access Object, which allows us to get the required components without accessing the Core class dynamically. This is not the perfect approach, because DAO in assumptions should provide only raw data (and I added `// TODO` where that is broken). On the other side, it allows for loosening relations between components. So, when continuing the further improvements, probably needs to break the backward compatibility because to remove circular dependencies requires redesigning the responsibilities of each class in Walkontable and splitting into many with a single responsibility (fixing the SOLID principles here). 

Following the topic of backward compatibility. During the refactoring keeping the backward compatibility is essential. And good refactoring cannot break that. That really knots the hands, thus I introduce a new layer which makes me able to loosen this knot. I added the `facade` layer, which is the external API of Walkontable. The facade cares to keep the same API as before refactoring. That makes me able to change some method names and map access to them in the facade. This is a really useful tool for changing internal relations. However, the complexity of the facade layer grows with the wideness of internal changes. During this refactoring, I went to the point where I figured that the wider changes will occur with an enormous increasing the logic in the facade layer. Then makes the whole Walkontable even more difficult to maintain. In that situation, I recommend redesigning and rewriting the WOT lib and then exposing an entirely new API. In my human opinion, this is the song of the future because we have got many more important things to improve than the deepest layer of HOT. For that reason, I finished the refactoring for now.

Additionally, there are:
* splitted core and clone `walkontable`'s classes, which makes code cleanest and easiest to debug.
* accessing the settings indirectly from the `wtSettings` service injected into components.
* added `facadeGetter` which should be used only when we provide reference to instance externally to Walkontable.  Using internally is FORBIDDEN.

### How has this been tested?

On each step, I care about all tests passed:

1. 1e6288f
2. 1e6288f...66aece5
3. 4974d18
4. 319006a
5. 1808cb8
6. 1808cb8...b3b5610
7. 737794a
8. 1875ffc
9. 0ff6b38
10. 50e82dc...f3de109
11. f3de109...eab8df8
12. 7d410ef
13. 7d410ef...8154b6d
14. 13be185...7152001
15. 567ab3b
16. 49700f6...14b53a8
15. d29c7b6
16. d29c7b6...01a1ef0
17. 774c44ff59fd5972dd3509ea7cef85ad538a216a
18. 121f6a6

### Types of changes

- Refactoring [skip changelog]

### Related issue(s):
1. #8760 

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Comment by Siemienik** [comment]
We should discuss merging it indirectly to develop

**Comment by Siemienik** [comment]
I change the target branch to the `develop` and cherry-picked needed commits.

**Comment by Siemienik** [comment]
### Current

[image](https://www.planttext.com/?text=ZLH1ReCm4Bpx5HOdKedmWoZNLagBgjvG3Yvs20bWj5xQIbN-NeE160oa1mxip8vtFGDxXGomBdAIbIZWn191FVyrEcpeHN6P12Y3Wi6Lo-_IipcvJ5C17Y4LIwuirHN3JsJv9G0z-aie7R2cCGM6cInLw0gtP4fZNl2G-cyrLZLI54MLCnHgSpHeBo9XMroKATud-gopdByqqX_oq0a_3nsQVDEFFHE8aWlGE_IdLo0Ya8bGoZvXL5RXawbsa5GussBN9prAo3lJbFf99lN9RkyTgrjbsADYeEmjsjTrgQZbD48DRkubriwTihGsBcrDkrR3ip9YfBM0Yn_pUYDawWWDWheA0f_62mawadMNQDE_Svrs3u8iFQEchcH6ppUws5xSjVanh_LmWUPcu1_45S4X82FNUtIS5MBPEPnZ1O1OZhMu_-WxMMWOmhU0TuboKVEVS83TNDvcI7R-zde6_QVw0m00)

<details>

```plantuml
@startuml

package "Handsontable" {
  package "EventManager" {
    interface eventManager
  }
  package "Helpers" {
    interface helpers
  }
  package "3rdparty/Walkontable" {
    [calculator]
    [viewport]
    [core]
    [cell]
    [border]
    [selection]
    [table]
    [event]
    [scroll]
    [settings]
    [table/*]
    [table/master]
    [overlay/*]
    [overlays]
    [filter]
    [renderer]
    [utils/orderView]
    [utils/nodesPool]
    [utils/column]
    [utils/row]

    interface walkontable
  }

}

[walkontable] -up---( [eventManager]
[walkontable] -up---( [helpers]
[walkontable] -up-> [calculator]
[viewport] -up-> [calculator]
[core] -up-> [viewport]
[walkontable] -up-> [core]
[border] -up-> [cell]
[selection] -up-> [cell]
[selection] -up-> [border]
[table] -up-> [cell]
[walkontable] -up-> [cell]
[walkontable] -up-> [selection]
[core] -up-> [event]
[core] -up-> [scroll]
[core] -up-> [settings]
[table/*] -up-|> [table]
[table/master] -up-|> [table]
[overlay/*] -up-> [table/*]
[overlays] -up-> [overlay/*]
[core] -up-> [overlays]
[core] -up-> [table/master]
[table] -up-> [filter]
[table] -up-> [renderer]
[renderer] -up-> [utils/orderView]
[renderer] -up-> [utils/nodesPool]
[table] -up-> [utils/column]
[table] -up-> [utils/row]
```

</details>

**Comment by budnix** [comment]
I've reviewed the code. I just [pushed](https://github.com/handsontable/handsontable/pull/9005/commits/30da10c17066cc57f1b7e5732814b0d283229c5b) some typo fixes, complete docs, and changed the WoT Core class from `ACore` to `CoreAbstract` - I think the new name betters reflects the purpose of the class. Besides, I think PR is ready for merge. Good job!

**Review by budnix — APPROVED** [review]

**Comment by Siemienik** [comment]
Thank you @budnix for the review & approval. Following our team arrangements from the last meeting, I'm going to merge this refactoring after the next release to avoid any unplanned influence on to release date.

**Pull request merged**
