### PR TITLE
Amccampos

### PR DESCRIPTION
**Pull request by amccampos**
### Context
"When a table is placed inside a container that has translate3d enabled, the row/column resize handlers are placed incorrectly." (from issue #2340).
The solution was to make the handlers being absolute positioning and to make the left and top properties as the difference between the header and the table boxes.

### How has this been tested?
The changes were tested with the code provided at http://jsfiddle.net/ftnhd8jv/4/

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #2340 
2.
3.

### Checklist:

- [x ] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @amccampos 

Thank you for sharing the pull request and your effort to investigate #2340 
Unfortunately, the following PR doesn't pass our tests. Please sign the CLA document if you haven't done it before as well. Till it happens I need to close the issue.

**Comment by amccampos** [comment]
Hi Aleksandre,
Yes, I've already signed the CLA document.
There were two missing semicolons causing erros, and I corrected them.
However, there are still 7 errors from "phantomjs-walkontable" test task,
which are also present in the handsontable master branch.
So, should I disconsider these 7 errors and submit a new PR (since they are
in the master)?
Cheers,
André.

2017-08-28 8:48 GMT+01:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
I am not sure if the following PR follows the rules as you wanted to change CSS positioning of the handler and the PR claims that you have deleted around 128'000 rows of Handsontable code. Can you check taht please?

**Comment by amccampos** [comment]
The 128,000 deleted rows were because I put the /dist folder in .gitignore.
I can revert this back.
Only three files were actually modified: manualRowResize.js,
manualColumnResize.js, and hansontable.css.

2017-08-28 12:16 GMT+01:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Yes, please reverse it.

**Pull request closed without merging**
