### PR TITLE
Add Simplified Chinese translation zh-CN

### PR DESCRIPTION
**Pull request by soakit**
### Context
Simplified Chinese (zh-CN) language support.

### How has this been tested?
No need to test

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
   #4696 

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing the translation. I hope that we will be able to get zh-CN merged with [zh-TW](https://github.com/handsontable/handsontable/pull/4919) together.

Please sign [the CLA](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo/edit#response=ACYDBNhV1MTfdr_NRjtxSKISOkC3HVhagIFXk_ZELGMEB_3L4uIlD2CG9AtqXYs). Without it, we won't be able to publish changes.

**Comment by osinglee** [comment]
Please merge as soon as possible. I need it, thank you

**Comment by AMBudnik** [comment]
Hi @osinglee the translation needs 5 confirmations from the community to get merged. If you found it useful please confirm.

@soakit 
Can you resolve the conflict, please? I can see that the CLA has been already signed. Thanks!

**Comment by soakit** [comment]
I have no idea how to resolve the conflict. no permission?
In addition, the conflicting file is easy to resolve.

**Comment by AMBudnik** [comment]
Hi @soakit 
The `import ruRU from './ru-RU';` is missing from the `src/i18n/languages/index.js` file (and in export as well).

Please use `git merge develop` on your branch to get the latest updates.

**Comment by soakit** [comment]
I deleted my branch very early.
image
You can see my commits, I didn't write any about `ruRU`.
Keep them all if the file of `ru-RU.js` exists. If not, remove the lines in import and export.
@AMBudnik

**Comment by AMBudnik** [comment]
Hi @soakit 
Can you create a new branch? It should be faster. We have just merged zh-TW I really hope that we will be able to merge the China version as well.

**Comment by AMBudnik** [comment]
You can also [allow us to co-author](https://blog.github.com/2018-01-29-commit-together-with-co-authors/).

**Comment by AMBudnik** [comment]
Hi @soakit 

If you do not want to update the PR can we do a similar co-authorship like we did[ here (with French translation)](https://github.com/handsontable/handsontable/pull/5044)?

**Comment by wojciechczerniak** [comment]
This PR was fixed and merged in #5063. Thanks! 🎉

**Comment by adrianszymanski89** [comment]
Hi @soakit @osinglee. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Pull request closed without merging**
