### PR TITLE
Docs: Various edits

### PR DESCRIPTION
**Pull request by kirszenbaum**
This PR:
- Adds info that the `populateFromArray()` method can't change read-only cells (fixing #8493)
- Fixes the description of the `copytable` option (fixing #9380)
- Fixes the description of the `afterDeselect` hook (fixing #8548)
- Makes other minor docs changes (fixing issues linked to this PR)

[skip changelog]

### CODE REVIEW

**Review by AMBudnik — DISMISSED** [review]
@kirszenbaum 

Good bunch of changes 👍 

Approved with some ideas:
* if we mention that the non-editable cells aren't given any `className` IMO we should mention that those with `readOnly` are given `htDimmed` `className`.
* after checking the `indexMapper` at `getFirstNotHiddenIndex` I spotted that the deprecation signature is not very "obvious"

I suggest something like this instead
Screenshot 2022-08-02 at 16 41 43

**Comment by kirszenbaum** [comment]
@AMBudnik

> if we mention that the non-editable cells aren't given any className IMO we should mention that those with readOnly are given htDimmed className.

Thanks! I summed up all differences in a table and moved it upfront ([ce73296](https://github.com/handsontable/handsontable/pull/9724/commits/ce73296dc698158775fde76e9d5de432dce2ba3d)):


> after checking the indexMapper at getFirstNotHiddenIndex I spotted that the deprecation signature is not very "obvious"
If we want to change the styling of the `@deprecated` mark, let's do it across the docs in a separate issue.

**Review by AMBudnik — CHANGES_REQUESTED** [review]
I am unsure if I would put `Can't be changed manually` in those columns as it's the same for both + the table is described to show differences. But that's only a suggestion. What, IMO, has to be changed is that a readOnly cell attaches the `htDimmed` class and here we say that we attach two classes `htDimmed` and `className`.




The readOnly cell is given only `htDimmed` class
Screenshot 2022-08-04 at 10 11 48

**Comment by kirszenbaum** [comment]
@AMBudnik - thanks! Changes made: [ed95697](https://github.com/handsontable/handsontable/pull/9724/commits/ed956978fca8f3f6ee354d2ad24c0ce965da6a2d)

**Review by AMBudnik — APPROVED** [review]

**Pull request merged**
