### PR TITLE
Adjust the context menu items the inability state

### PR DESCRIPTION
**Pull request by budnix**
### Context

This PR adjusts the inactivity state of the context menu items responsible for inserting or removing row or columns. The behavior is based on the following spec: 

### Spec

Menu options activity state (checked checkbox means item is active):
1. Triggered by columns' headers. Both cases: all column headers are selected, some of the column headers are selected
    - [ ] `Insert row above`
    - [ ] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [ ] `Remove row`
    - [x] `Remove column`
2. Triggered by rows' headers. Both cases: all row headers are selected, some of the row headers are selected
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [ ] `Insert column on the right`
    - [ ] `Insert column on the left`
    - [x] `Remove row`
    - [ ] `Remove column`
3. Triggered by corner when there is at least one row and column
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [x] `Remove row`
    - [x] `Remove column`
4. Triggered by corner when there are all rows trimmed but there is at least one column (the filter plugin case)
    - [ ] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [ ] `Remove row`
    - [x] `Remove column`
5. Triggered by corner when there are all columns trimmed but there is at least one row
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [ ] `Insert column on the left`
    - [x] `Remove row`
    - [ ] `Remove column`
6. Triggered by corner when there are all rows and columns trimmed or passed data is empty 
    - [ ] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [ ] `Insert column on the left`
    - [ ] `Remove row`
    - [ ] `Remove column`
7. Triggered by cell click
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [x] `Remove row`
    - [x] `Remove column`

### How has this been tested?

Updated E2E tests to the new behavior.

To emulate rows trimming the _TrimRows_ plugin is used:
```js
{
  data: Handsontable.helper.createSpreadsheetData(5, 5),
  colHeaders: true,
  rowHeaders: true,
  contextMenu: true,
  trimRows: [0, 1, 2, 3, 4],
}
```
For columns trimming emulation the `columns: []` option can be used but then the "Insert columns" option is disabled as the HoT disallow add a new column when it doesn't know about data schema. However, this can be emulated by passing data with 0 columns:
```js
{
  data: Handsontable.helper.createSpreadsheetData(5, 0),
  dataSchema: [], // Unlocks adding new rows through the context menu.
  colHeaders: true,
  rowHeaders: true,
  contextMenu: true,
}
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7060 
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wojciechczerniak** [comment]
🤔 

When we have selected all columns and rows then shouldn't "add column right" be added to the right of the selection? This would be more consistent with selecting columns by headers. Same about rows. I would expect that the row will be added below the selection.

This doesn't change the scenario when we have only the corner visible. "Below" and "Right" are relative to the selection which is `[ -1, -1, -1, -1 ]`. But when we have data trimmed/filtered then we have columns visible and selected by the corner click.

IMO "add below" "add right" are the only options when we have only a corner. When there are columns selected we have "left" and "right" relative to the selection. And if data is not filtered/trimmed then we should have options to add row "above" or "below", relative to the selection as well.

**Comment by budnix** [comment]
> When we have selected all columns and rows then shouldn't "add column right" be added to the right of the selection? This would be more consistent with selecting columns by headers. Same about rows. I would expect that the row will be added below the selection.

@wojciechczerniak While adding a new column (or row) the selection should behave as if it were triggered from columns? So, the newly added column is not highlighted. Or it should return to the state where all cells and headers are selected?
Kapture 2020-07-07 at 14 08 16

**Comment by budnix** [comment]
@wojciechczerniak Please fill the mini spec which I've prepared. Feel free to add more cases to support. `https://github.com/handsontable/handsontable/pull/7082#:~:text=Spec`.

**Comment by wojciechczerniak** [comment]
Both Excel and GS are selecting the newly inserted column. There is a related issue #6993 so maybe we can skip it for now.

I will look into the checklist, thanks 👍

**Comment by wojciechczerniak** [comment]
Here's the checklist. WDYT?

1. Triggered by columns' headers. Both cases: all column headers are selected, some of the column headers are selected
    - [ ] `Insert row above`
    - [ ] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [ ] `Remove row`
    - [x] `Remove column`
2. Triggered by rows' headers. Both cases: all row headers are selected, some of the row headers are selected
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [ ] `Insert column on the right`
    - [ ] `Insert column on the left`
    - [x] `Remove row`
    - [ ] `Remove column`
3. Triggered by corner when there is at least one row and column
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [x] `Remove row`
    - [x] `Remove column`
4. Triggered by corner when there are all rows trimmed but there is at least one column (the filter plugin case)
    - [ ] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [ ] `Remove row`
    - [x] `Remove column`
5. Triggered by corner when there are all columns trimmed but there is at least one row
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [ ] `Insert column on the left`
    - [x] `Remove row`
    - [ ] `Remove column`
6. Triggered by corner when there are all rows and columns trimmed or passed data is empty 
    - [ ] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [ ] `Insert column on the left`
    - [ ] `Remove row`
    - [ ] `Remove column`
7. Triggered by cell click **
    - [x] `Insert row above`
    - [x] `Insert row below`
    - [x] `Insert column on the right`
    - [x] `Insert column on the left`
    - [x] `Remove row`
    - [x] `Remove column`


** We should keep no 7 as it is now. Although, cell context does not fit here at all.

----
Notes:
1. Header active color is a different issue: #7062
2. The selection state after the CRUD operation mentioned in https://github.com/handsontable/handsontable/pull/7082#issuecomment-654812003 is a different issue: #6993

**Comment by aninde** [comment]
> Here's the checklist. WDYT?
 
That checklist is great. Maybe we should use it in our documentation? WDYT @scarletfog?

**Comment by aninde** [comment]
This is a very nice set of requirements. Maybe we should include them in the documentation from version 8? WDYT @scarletfog?

**Comment by scarletfog** [comment]
Sorry @aninde your first message plunged in my mailbox deep under other ones 🙈 
Yep, can be a good idea to have this list directly in the documentation, looks helpful!

**Pull request merged**
