### PR TITLE
Fix row sequence lost after removing all columns

### PR DESCRIPTION
**Pull request by budnix**
### Context

Fix row sequence lost after removing all columns.

### How has this been tested?

Added E2E tests.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6865
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wojciechczerniak** [comment]
Do you think we should do the same after undo remove all rows?

Rows will be restored but columns order might be lost

**Comment by budnix** [comment]
> Do you think we should do the same after undo remove all rows?
> 
> Rows will be restored but columns order might be lost

I've checked the rows and I couldn't reproduce the mentioned issue. In addition, I've written a test for columns and rows.

**Comment by wojciechczerniak** [comment]
> In `7.4.2`, after removing all columns, the row headers remain displayed, and it _kind of_ makes sense...? I'm not 100% sure though. @wojciechczerniak?

When we have `columns` defined it makes sense to keep them. When they are dynamic, we've argued with @wszymanski if we should keep it consistent. But then we have rows which are always dynamic and strictly dependant on the data. So if you remove the data, there are no rows to display, therefore no headers. This is by design that we remove headers for dynamic rows and columns and the deliberately defined columns are kept. 

So WDYT, this or previous approach makes more sense?

**Comment by jansiegel** [comment]
> So WDYT, this or previous approach makes more sense?

Correct me if I'm wrong, but I think in `7.x`, when you removed all the columns, the dataset contained `n` arrays `null`, so technically, there still _were_ `n` rows. But in `8.x`, the dataset is empty, so I guess it makes sense not to keep the row headers.

**Comment by budnix** [comment]
It seems that all bugs described by @jansiegel already existed. I've checked with 7.4.2 and points 1, and 2 don't work in 7.4.2 either. One difference that I found is clicking in the corner and hitting <kbd>CMD<kbd>+<kbd>Z<kbd> do nothing now. 

About point 3 I assume that it works by design. If not I'd leave this for a separate issue as this is not strictly related to the _UndoRedo_ plugin.

**Comment by budnix** [comment]
Within this [commit](https://github.com/handsontable/handsontable/pull/6947/commits/589fda244ca45969d59ff4a96d8d4c695b9e2b07) I've fixed "isListening" state losing so the <kbd>CMD+Z</kbd> should work as in the latest stable version (7.4.2).

**Comment by jansiegel** [comment]
> Within this [commit](https://github.com/handsontable/handsontable/pull/6947/commits/589fda244ca45969d59ff4a96d8d4c695b9e2b07) I've fixed "isListening" state losing so the CMD+Z should work as in the latest stable version (7.4.2).

After 589fda244ca45969d59ff4a96d8d4c695b9e2b07 it works _better_ than in `7.4.2`, <kbd>cmd+z</kbd> works fine without the need to click on the table to regain focus 👌

**Pull request merged**
