### PR TITLE
Adjust HF integration demo

### LINKED ISSUE #8408: New docs: HyperFormula page adjustment
### Description

- [ ] 1. Header `Learn more` should be H2, not H3. https://handsontable.com/docs/hyperformula-integration/#learn-more
- [ ] 2. Demo on https://dev.handsontable.com/docs/next/formula-calculation/#basic-multi-sheet-example needs to be changed to https://jsfiddle.net/hw60ptLj/

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR fixes issues mentioned within the [issue](https://github.com/handsontable/handsontable/issues/8408).

_[skip changelog]_

### How has this been tested?

\-

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. fixes #8408
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by wszymanski — COMMENTED** [review]
Has been demo updated according to second point in the issue?

**Comment by budnix** [comment]
> Has been a demo updated according to second point in the issue?

Yes, it turned out that there are missing only headers with sheet names https://github.com/handsontable/handsontable/pull/8433/files#diff-8c4aea0bcbc7f14c4d5338fca6ffe5257086959f0770f507e041cfed8e1fd909R72.

**Review by wszymanski — DISMISSED** [review]

**Review by aninde — CHANGES_REQUESTED** [review]
> Yes, it turned out that there are missing only headers with sheet names https://github.com/handsontable/handsontable/pull/8433/files#diff-8c4aea0bcbc7f14c4d5338fca6ffe5257086959f0770f507e041cfed8e1fd909R72.

It was also about removing empty columns. You can check it by comparing datasets with my proposed demo https://jsfiddle.net/hw60ptLj/

Unfortunately, this header overlaps the view button when dark theme is enabled
Screenshot 2021-07-16 at 15 22 01

**Review by aninde — APPROVED** [review]
👍

**Pull request merged**
