### PR TITLE
Convert BaseEditor to use ES6 class and arrow function scope

### PR DESCRIPTION
**Pull request by aaronbeall**
### Context
ES5 to ES6 conversion per https://github.com/handsontable/handsontable/issues/5403

Github's diff viewer is unfortunately pretty noisy, the changes were:
- Converted `BaseEditor` constructor function and prototype functions to use ES6 `class` - this was a pure copy paste with no re-ordering or changes except listed below.
- Changed the `extend` method to simply return `class Editor extends BaseEditor {}`
- Replaced `_this` with `this` in arrow functions

### How has this been tested?

`npm test`
I branched from `develop` and found that before changes there are some `e2e` failures when run locally. This PR did not seem to introduce any new ones.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/5403
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
@aaronbeall can you check the tests? Apparently, there is something wrong. I've restarted them 6 times.

**Comment by aaronbeall** [comment]
Hm, definitely looks like there's a problem. I can't get the e2e tests to run properly locally... there are a lot of failures related to scrolling and it never gets to the CI failures. Even on a clean `master` and `develop` branch it does the same thing. Any suggestions?

**Comment by AMBudnik** [comment]
I've asked our developer to do a review when he finishes changes for React wrapper

**Comment by jansiegel** [comment]
The tests are probably failing on this one, because of this line: https://github.com/handsontable/handsontable/pull/5447/files#diff-6c12546315d5a1a24cf343b03ff3ed89R63

In the rewritten version of the `extend` method, you assumed that the "base" class is always `BaseEditor`, and it's not always the case, for example:
- `AutocompleteEditor` extends `HandsontableEditor`
- `HandsontableEditor` extends `TextEditor`
- `TextEditor` extends `BaseEditor`

So, `AutocompleteEditor` expects to inherit not only `BaseEditor`'s methods, but also all the stuff declared in `TextEditor` and `HandsontableEditor` on top of it. After your change, it gets only the things from `BaseEditor`, which results in an error:

> TypeError: this.refreshDimensions is not a function

... and it happens, when:

- `AutocompleteEditor` tries to apply `HandsontableEditor`'s `prepare` method to its own context:
    > HandsontableEditor.prototype.prepare.apply(this, args);
- `HandsontableEditor`'s `prepare` method does the same to the `TextEditor`'s `prepare` method:
    > TextEditor.prototype.prepare.apply(this, [td, row, col, prop, value, cellProperties, ...args]);
- And `TextEditor`'s `prepare` assumes, that the `refreshDimensions` exists:
    > this.refreshDimensions(true)

    While it doesn't, because it was introduced in `TextEditor`, which `AutocompleteEditor` never inherited.

So, **tl;dr;** - changing the method to:
```
extend() {
    return (class Editor extends this.constructor {});
}
```
seems to do the trick :)

**Comment by aaronbeall** [comment]
@jansiegel Nice analysis! That was definitely an oversight on my part, I'm very used to ES6 class patterns I forget a some of the nuances of these older patterns. 

I'm going to go through the PRs and add JSDocs as requested. Obviously I'm not super familiar with this codebase so it'll be a bit slow going but I'll do my best!

**Comment by wojciechczerniak** [comment]
You're still working on this @aaronbeall ?

**Comment by swistach** [comment]
Hi @aaronbeall,
Thank you for your help. Good job! :+1:

We'll finish it on a separated branch.

**Pull request merged**
