### PR TITLE
Fix double-tap issue on iOS

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR fixes [another PR](https://github.com/handsontable/handsontable/pull/7824) that adds support for double-tap actions. There is a bug for mobile browsers that use the WebKit as an engine (excluding the latest Safari that uses a newer version of that engine). The bug causes that a cell editor can not be open using double-tap events. It's fixed by calling the "preventDefault" on the "touchend" events. By doing that, the second tap can be triggered as fast as the user is able to. The technique removes the restriction where the browsers apply the native delay ~300ms (https://webkit.org/blog/5610/more-responsive-tapping-on-ios/).

The "preventDefault" call is not necessary for the newest browsers. However, it provides a second desired effect. The cells that contain interactive elements such as "a" link or "button" elements will not be triggered until the previous highlight cell is the same.

_[skip changelog]_ The PR fixes [another PR](https://github.com/handsontable/handsontable/pull/7824) with the same meaning so the changelog for that PR is not necessary.

### How has this been tested?

I tested the changes - it includes scrolling, dropdown menu checking, filter by condition menu checking, cell editing (double-tap cases when the cell was previously selected or not selected at all), and checking how the interactive elements behave (e.q. cell renderer with `a` - link element).

I tested on iPhone 12 iOS 14.5 with Safari, Chrome, FF, and Edge. iOS simulator iOS 14.3 with Safari. Android 9 simulator with Chrome 69 and 90 and Android 11 with Chrome 83 and 90 and I didn't found any issues.    

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7973
2. #7824
3.

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by wszymanski — APPROVED** [review]
LGFM 👍 I've checked just the code. @aninde please check in on iOS.

**Review by aninde — CHANGES_REQUESTED** [review]
I cannot open dropdown menu on Safari on iOS 13.3.1 with this build. 

On other devices:
- iPad iPadOS 14.5.1- Safari, Chrome
- iPhone iOS 14.5.1 - Safari, Chrome, Firefox
-Samsung Galaxy A51 Android 11 - Samsung Internet, Chrome, Firefox
- Mi - Android 9 - Firefox, Chrome 
dropdown menu, double-tap, editor, submenus of dropdown menu works as charm :)

**Comment by budnix** [comment]
> I cannot open dropdown menu on Safari on iOS 13.3.1 with this build.
> 
> On other devices:
> 
> * iPad iPadOS 14.5.1- Safari, Chrome
> * iPhone iOS 14.5.1 - Safari, Chrome, Firefox
>   -Samsung Galaxy A51 Android 11 - Samsung Internet, Chrome, Firefox
> * Mi - Android 9 - Firefox, Chrome
>   dropdown menu, double-tap, editor, submenus of dropdown menu works as charm :)

iOS 13 is not supported. 

CC @wojciechczerniak

**Comment by wojciechczerniak** [comment]
We had a separate issue for iOS 13 somewhere. But since they fixed it in iOS 14, IMO we should triage it again outside of this PR.

@aninde I'm with @budnix on this one. iOS 13 was not in the scope of the issue here.

**Review by aninde — APPROVED** [review]
👍

**Pull request merged**
