### PR TITLE
Fix comment positioning when HoT is nested in a scrollable element

### PR DESCRIPTION
**Pull request by LeRoi**
### Context
Handsontable does not account for scrollable elements it is nested within, which means that it misaligns comments when outer elements are scrolled. Fix this by summing the amount of scrollLeft and scrollTop and subtracting them from comment position. 

Thorough change description:
Add a new method to the comments plugin which computes the scroll distance (left, top) between the Handsontable element and the document body // nearest parent element with position: fixed, whichever comes first. Employ this method to offset comment text boxes to render them in the correct location while still respecting existing placement logic.

### How has this been tested?
Tested with modifications on an internal build. Can fork + update jsfiddle if there's some external hosting I can use to show a modified handsontable.full.js.

You can repro the error here: http://jsfiddle.net/5h11bfsx/
In the demo area:
1. Hover over comment in C11.
2. Observe that comment appears to right of cell, as expected.
3. Drag right (outer div) scrollbar until C11 is at top of demo area, but still visible.
4. Hover over comment in C11.
5. Observe that comment appears in middle of screen, and not beside C11.
6. Hover over C21.
7. Observe that comment appears beneath table, as opposed to beside C21.

I noticed that the contributions doc asked to add a test. I'm having a difficult time running tests on my end (I run the right npm commands, get to a terminal which displays info followed by many ......., but cannot access the local browser test instances) // am unsure how to simulate scrolling in this test environment. Advice would be heavily appreciated!

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1.

### Checklist:
- [ ] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

Unsure if my code conforms to the project style fully as the link in the contributing section leads to a Wiki with no coding guidelines as far as I can tell. Perhaps I missed something obvious, feel free to link me.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @LeRoi 

please sign the CLA document and change the code to follow our [Contributing Guidelines](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md)

**Comment by LeRoi** [comment]
Hi, @AMBudnik 

I believe I had previously signed the CLA, but I've re-signed it just in case.

I understand I'm currently missing tests for this, but am seeking advice in this regard, see original PR.
I updated the original PR to include a more thorough change description.
Please let me know if I am in violation of any style guidelines. As I noted in the original PR, there does not appear to be a style guide on either the wiki linked from the Contributing Guidelines doc, nor on the general Handsontable documentation site. Very happy to be referred to the right document if I missed it.

Please advise on how to proceed. Thanks.

**Comment by AMBudnik** [comment]
Hi @LeRoi 

developers won't check the PR if is not marked as `ready to review` and I can add the label only after you
1. Add tests
2. Fix the code to get approved by all checks
3. Change the branch to `develop`.

all guidelines can be checked in the Contributing files at https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md

ps. I am really sorry for the CLA. You are right, it has been signed before.

**Comment by AMBudnik** [comment]
I am closing the PR as there aren't any updates for more than 2 weeks.

**Pull request closed without merging**
