### PR TITLE
Added Russian translations (#4696)

### PR DESCRIPTION
**Pull request by arogachev**
### Context

Added :ru: Russian translations. 

### How has this been tested?

No tests are needed here.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Translation

### Related issue

#4696

### Checklist

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you so much for completing the pull translation for Russian and signing CLA.

Now we need to wait for some [feedback from the community](https://github.com/handsontable/handsontable/issues/4854) and we'd be ready to pull the changes to the official version of Handsontable.

**Comment by AMBudnik** [comment]
Thank you all for confirmations. I have asked our devs to take a look at the code and merge it to the official version of Handsontable.

**Comment by Boksh** [comment]
Great!  @AMBudnik react-handsontable will being changed too?

**Comment by AMBudnik** [comment]
The react-handsontable is a wrapper so if you leave the package.json to update the Handsontable version to minors (by default) it will also have the new language option.

**Comment by wszymanski** [comment]
Related to #4933 which is already in development.

**Comment by wszymanski** [comment]
Issue #4933 is merged to `develop`. Thanks for your contribution. I'm merging your PR @arogachev.

**Comment by AMBudnik** [comment]
Hi @arogachev  

Russian translation is now an official part of Handsontable 2.0.0.

Thank you for your input :)

**Comment by AMBudnik** [comment]
@kgorin8 @Boksh 

thank you for your collaboration

**Comment by adrianszymanski89** [comment]
Hi @arogachev. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Pull request merged**
