### PR TITLE
[RTL] Internal API naming

### PR DESCRIPTION
**Pull request by budnix**
### Context

To make the code easier to understand (less confusing) especially in the context of RTL the PR proposes the internal API naming changes. Most of the APIs that use "left"/"right" words can be confused in RTL. In that mode "left" often means "right" and vice versa. The PR changes the naming to "inlineStart"/"inlineEnd" or "start"/"end" depending on the context.

### 1. Changes to the overlays' CSS classes

The CSS classes are changed. The PR adds new names such as `ht_clone_top_inline_start_corner`, `ht_clone_inline_start`, and `ht_clone_bottom_inline_start_corner` simultaneously leaving the old classes in the DOM for backward compatibility.

The commit 7c75528bc6659b655c4dbcd578f58287ab08a2fb (tests 550c3103fa1553dabea3fbbd28006fc2b79daff6).

### 2. Changes to the other CSS class names

The `innerBorderLeft` CSS class is replaced with `innerBorderInlineStart`. The old class is left in the DOM for backward compatibility.

The commit a820796d72c51573a395e00b184d9b2205b13704 (tests f549bd6554a72661941d6b113ef4c8c3a3e1b668).

### 3. Changes internal API access to the Walkontable instance

To emphasize that the Walkontable rendering engine is not a part of public API the property name is changed from `hot.view.wt` to `hot.view._wt`.

The commit 1d3310ca3d44f4aa7a4a70f8713f3d619c37e8ff.

### 4. Changes internal API access to the overlays' instances

The changes (`hot.view._wt`):
 * `.wtOverlays.topLeftCornerOverlay` => `.wtOverlays.topInlineStartCornerOverlay`;
 * `.wtOverlays.leftOverlay` => `.wtOverlays.inlineStartOverlay`;
 * `.wtOverlays.bottomleftCornerOverlay` => `.wtOverlays.bottomInlineStartCornerOverlay`.

The commit 7c75528bc6659b655c4dbcd578f58287ab08a2fb.

### 5. Changes to the `CellCoords` and `CellRange` classes.

The PR updates the method names and implementation logic to follow the new direction-less terminology. To support the methods that point to the specific direction (e.g. `getBottomRightCorner` or `isNorthEastOf` etc.) the above classes from now on expect the constructor argument `isRtl` that allows distinguishing the logic within. For that methods, the "left" is always organoleptically "left". However, in most cases, to support LTR and RTL the following methods should be used: 
   * `getTopStartCorner`;
   * `getTopEndCorner`;
   * `getBottomStartCorner`;
   * `getBottomEndCorner`;
   * `getOuterTopStartCorner`;
   * `getOuterTopEndCorner`;
   * `getOuterBottomEndCorner`;
   * `getOuterBottomStartCorner`.

The methods are part of the new API. Depending on the layout mode they are returning _left_ or _right_ coordinates.

The commit 595892dcb93de3b5a7ca829ec23991671339cc09, d876b2b64e22597973d4235d82e11354c118f44c (tests 91264f4afbc8d83dca028bc67a9e585fd72c5d27).

_[skip changelog]_

### How has this been tested?

I tested the changes locally and cover the proposal with new E2E and unit tests.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. resolves https://github.com/handsontable/handsontable/issues/9130
2.
3.

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jansiegel** [comment]
@budnix 
I'm not sure about the naming of this type of methods:
> getTopStartCorner;
> getTopEndCorner;

Isn't it a little misleading? For example, if I select cells `(0, 0)` to `(2, 2)`, I'd expect `getTopStartCorner` to return `(0, 0`), but when I select the same range in the other direction (so from `(0, 2)` to `(2, 0)`) I'd expect the same method to return `(0, 2)`. I think "start" is a very ambiguous term and when not thinking about it in a context of RTL, it can mean multiple things - in the context of selecting cells, I would instinctively understand it as "the beginning of selection". WDYT?

**Comment by budnix** [comment]
> I think "start" is a very ambiguous term and when not thinking about it in a context of RTL, it can mean multiple things - in the context of selecting cells, I would instinctively understand it as "the beginning of selection". WDYT?

In terms of RTL, all naming that contains _left_/_right_ keywords are renamed to _start_/_end_ or _inline_start_/_inline_end_ names. I've already used to it. Maybe it's all about documentation.

The method `getTopStartCorner` (and others) works as a kind of "floating" alias. No matter in which direction the selection is selected the method returns top-left (0, 0 in your example) coordinates and top-right in RTL (organoleptically right and still 0, 0).

**Comment by jansiegel** [comment]
> > I think "start" is a very ambiguous term and when not thinking about it in a context of RTL, it can mean multiple things - in the context of selecting cells, I would instinctively understand it as "the beginning of selection". WDYT?
> 
> In terms of RTL, all naming that contains _left_/_right_ keywords are renamed to _start_/_end_ or _inline_start_/_inline_end_ names. I've already used to it. Maybe it's all about documentation.
> 
> The method `getTopStartCorner` (and others) works as a kind of "floating" alias. No matter in which direction the selection is selected the method returns top-left (0, 0 in your example) coordinates and top-right in RTL (organoleptically the right and still 0, 0).

Yeah, I get it, I'm just not sure if it isn't misleading 🤔

**Review by jansiegel — APPROVED** [review]
Apart from [my doubts](https://github.com/handsontable/handsontable/pull/9176#issuecomment-1032377801) everything looks good to me 👍

**Pull request merged**
