### PR TITLE
Change the color of the filters OK button

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR changes the styling of the filters OK button to meet a better contrast ratio according to this suggestion: https://github.com/handsontable/dev-handsontable/issues/1509.

~Changing the button's default color can be considered a breaking change.~ The background color is only changed when the user focuses the element through tab navigation (`:focus-visible`). This is not considered as a breaking change but a minor (feature) change.

### How has this been tested?

I tested the changes locally.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1509

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Comment by evanSe** [comment]
We may only want to change the focus ring color instead of the button, will get back to you

**Review by jansiegel — APPROVED** [review]
If this is no longer the case, everything looks fine.

https://github.com/handsontable/handsontable/pull/10558#issuecomment-1782949246

**Comment by evanSe** [comment]
Instead of changing the buttons colours, could we change it to the suggest colours only on focus?

**Comment by budnix** [comment]
> Instead of changing the buttons colours, could we change it to the suggest colours only on focus?

Sure. Can I ask for a border color recommendation?

**Comment by evanSe** [comment]
> > Instead of changing the buttons colours, could we change it to the suggest colours only on focus?
> 
> Sure. Can I ask for a border color recommendation?

I think we can pote

> > Instead of changing the buttons colours, could we change it to the suggest colours only on focus?
> 
> Sure. Can I ask for a border color recommendation?

It would be this change, but only happening on focus
```
.handsontable .htUIInput.htUIButtonOK input {
  background-color: #92dd8d;
  border-color: #7cb878;
  color: #000;
}
```

**Review by jansiegel — APPROVED** [review]

**Comment by AMBudnik** [comment]
The changes can be tested here https://jsfiddle.net/qsedcahb/19/ in the v14.0.0 demo. This is how the new `OK` button looks when focused.

Zrzut ekranu 2023-12-1 o 13 13 02

**Pull request merged**
