### PR TITLE
Fix an issue with the docs:api script crashing.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR should fix the issue described in #8774.

The problem seems to have happened on projects with `walkontable` builds and test helpers pre-generated, as they significantly increased the size of the processed data.

In this PR I'm limiting the number of files being processed in search of JSDocs by cutting out the test files and the dist builds.

<sub>[skip changelog]</sub>

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8774 

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by Siemienik** [comment]
Thank you @jansiegel 🥇 I have a doubt about how should I check if it accomplished the target.

Maybe someone with the issue described in #8774 should try to run `docs:api`?

**Review by Siemienik — COMMENTED** [review]
Thank you @jansiegel 🥇I ran that, and It works.

I have a doubt about how should I check if it accomplished the target (#8774).

Maybe someone with the issue described in #8774 should try to run docs:api?

**Comment by Siemienik** [comment]
I ran again `npm run docs:api` for the `develop` and `feature/issue-8774` branches, then I compare the amount of parsed files. Both are the same, 186.

**Comment by jansiegel** [comment]
@Siemienik 
> I ran again `npm run docs:api` for the `develop` and `feature/issue-8774` branches, then I compare the amount of parsed files. Both are the same, 186.

Yup, but the number of files passed to `jsdoc-api` came down from `782` to `465`.

>I have a doubt about how should I check if it accomplished the target (#8774).
Maybe someone with the issue described in #8774 should try to run docs:API?

You can try generating the `walkontable` and its tests' builds, and then running `docs:api`, so, for example:
```
> npm run build:walkontable
> npm run test:walkontable.dump
> cd docs
> npm run docs:api
```
But you're right, @budnix could you check if this PR fixes the issue for you?

**Comment by budnix** [comment]
@jansiegel @Siemienik I can confirm. I don't have the mentioned error anymore. Good job!

**Comment by budnix** [comment]
However, I have got a lot of internal modules that AFAIK shouldn't be visible in docs:
```
...
Generating `hooksRefRegisterer` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/hooksRefRegisterer.md
Generating `localHooks` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/localHooks.md
Generating `anonymous-nodeData` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/anonymous-nodeData.md
Generating `Core-grid` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/core-grid.md
Generating `calculatedColumns` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/calculatedColumns.md
Generating `calculatedRows` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/calculatedRows.md
Generating `stickyColumnsLeft` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/stickyColumnsLeft.md
Generating `stickyRowsBottom` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/stickyRowsBottom.md
Generating `stickyRowsTop` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/stickyRowsTop.md
Generating `Symbol` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/symbol.md
Generating `module` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/module.md
Generating `JasmineBridgeReporter` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/jasmineBridgeReporter.md
Generating `anonymous` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/anonymous.md
Generating `validateCell` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/validateCell.md
Generating `columnFactory` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/columnFactory.md
Generating `throttle` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/throttle.md
Generating `throttleAfterHits` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/throttleAfterHits.md
Generating `debounce` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/debounce.md
Generating `curry` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/curry.md
Generating `curryRight` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/curryRight.md
Generating `randomString` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/randomString.md
Generating `checkboxRenderer` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/checkboxRenderer.md
Generating `createPriorityMap` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/createPriorityMap.md
Generating `breadthFirst` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/breadthFirst.md
Generating `createUniqueMap` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/createUniqueMap.md
Generating `createUniqueSet` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/createUniqueSet.md
Generating `staticRegister` into: /Users/budnix/Documents/Projects/handsontable-develop/docs/next/api/staticRegister.md
...
```

**Comment by jansiegel** [comment]
@budnix, true, i don't think there's a reason for them to be generated, but they are: https://github.com/handsontable/handsontable/blob/master/docs/10.0/api/jasmineBridgeReporter.md. 

But yes, I think it's another issue, so after closing this PR I can report it separately.

**Review by Siemienik — APPROVED** [review]

**Pull request merged**
