### PR TITLE
Add HyperFormula to the `full` and `full.min` UMD builds.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR:
- adds HyperFormula to the `dist/handsontable.full.js` and `dist/handsontable.full.min.js` builds,
- makes the `hyperformula` dependency copied to the `dist` directory after build (only the js files, languages and license)
- adds `hyperformula` as an `optionalDependency`

### Related issue(s):
1. #7648 

[skip changelog]

### CODE REVIEW

**Review by wojciechczerniak — CHANGES_REQUESTED** [review]
Please check https://github.com/handsontable/handsontable/blob/addHFToUMDBundle/dist/README.md for `hot-formula-parser` references

**Comment by jansiegel** [comment]
> Please check https://github.com/handsontable/handsontable/blob/addHFToUMDBundle/dist/README.md for `hot-formula-parser` references

Oops, forgot to commit 🤦  cd1073e

**Review by wojciechczerniak — APPROVED** [review]
👍

**Review by nikersify — APPROVED** [review]

**Comment by nikersify** [comment]
Merging, since @jansiegel asked me to after review approval

**Pull request merged**
