### PR TITLE
feat: let isCommand can be a function

### PR DESCRIPTION
**Pull request by maketubo**
to replace PR #6584 (solves #6583)

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you @maketubo 

I think that we're all set. I'll mark it as `ready for review`.

ps. I've just confirmed with our CTO that `/dist` would need to be removed from the repository to attach it in the `.gitignore` and we cannot do this.

**Comment by maketubo** [comment]
> Thank you @maketubo
> 
> I think that we're all set. I'll mark it as `ready for review`.
> 
> ps. I've just confirmed with our CTO that `/dist` would need to be removed from the repository to attach it in the `.gitignore` and we cannot do this.
i also found a bug that i will fix it later and create nother pull request.
Merry Christmas!

**Comment by maketubo** [comment]
> Thank you @maketubo
> 
> I think that we're all set. I'll mark it as `ready for review`.
> 
> ps. I've just confirmed with our CTO that `/dist` would need to be removed from the repository to attach it in the `.gitignore` and we cannot do this.

Today I found another bug that i will fix it later and create nother pull request.
And Merry Christmas!

**Comment by pnowak** [comment]
Hi @maketubo 

Could you explain to us the goal of this change? 
Can you show your use case?

**Comment by maketubo** [comment]
Sorry for late to reply. here is my use case. What i need is just make isCommand can be a function and my PR also very simple.
Before :
  we only can set isCommand true or false.
Now:
 we can set isCommand as a function{ // return true or false depend on our business.}
```
function severalRowOprItem(oprType, type, msg1, msg2, clazz){
        const localVars = {
            changeRowNum: 0,
            clickFromInput: true
        };
        return {
            renderer: function(hot, wrapper, row, col, prop, itemValue) {
               //return someCustomsDom;
            },
            disableSelection: false, // Prevent mouseoever from highlighting the item for selection
            isCommand: function () {
               if(localVars.clickFromInput){
                   return false;
               }
               let cci = $(".htMenu").find('.'+clazz);
               let temp = cci ? cci.val() : void 0;
               if( temp.indexOf(".") !== -1 || temp.indexOf("0") == 0){
                   $.message({
                       message: '请输入正确的正整数',
                       type: 'warning'
                   });
                  return false;
               }
               const num = temp.replace(/[^\d]/g, '')
               if (parseInt(num) > 500) {
                  $.message({
                      message: '单次修改的数量请小于500',
                      type: 'warning'
                  });
                  return false;
               }
               cci.val(num);
               return cci.val()>= 1;
            }, // Prevent clicks from executing command and closing the menu,
            callback: function callback(key, normalizedSelection) {
                const latestSelection = normalizedSelection[ Math.max(normalizedSelection.length - 1, 0) ];
                localVars.changeRowNum = $(".htMenu").find('.'+clazz).val();
                let appendPoint = 0;
                if (oprType.indexOf("row") !== -1) {
                    appendPoint = curSheetHot.countRows();
                } else {
                    appendPoint = curSheetHot.countCols();
                }
                if (oprType.indexOf("remove") !== -1) {
                  appendPoint = appendPoint - parseInt(localVars.changeRowNum); 
                }
                $(".htMenu").find('.'+clazz).val("");
                this.alter(
                    oprType,
                    appendPoint,
                    parseInt(localVars.changeRowNum),
                    type
                );
            }
        };
    }
```

**Comment by maketubo** [comment]
Although the changes are small, it brings more free design space.  Now I just recompile and apply to my project and work perfect, the min.js different as follow picture.
image

**Comment by adrianszymanski89** [comment]
Closed due to inactivity and potential conflicts if merged in this state.

**Pull request closed without merging**
