### PR TITLE
Remove travis CI config file

### PR DESCRIPTION
**Pull request by budnix**
### Context

Migration to CodeShip CI.

### CODE REVIEW

**Comment by aninde** [comment]
**Testing notes / Testing release of 7.4.0**
There is no travis config file on `develop` and `release/7.4.0` branch. However, travis-ci is still mentioned on 12 line README.file. Is that correct?

**Comment by wojciechczerniak** [comment]
Nope. We should change the badge to Codeship CI 

🛎 @budnix

**Comment by aninde** [comment]
There is no travis config file on updated 7.4.0 branch, but still, Travis-ci is mentioned on 12 line README.file.

 @jansiegel  does f531150b94c22efc7cd6b641879048a3a7277f4c was merged to 7.4.0 from `develop`?

**Comment by budnix** [comment]
@aninde Fixed within https://github.com/handsontable/handsontable/commit/5922bdc433acde132d9928ae6fd0b9af1b207b6d.

**Pull request merged**
