### PR TITLE
Resolve the issue with `type` sub-properties (`editor` + `renderer`) not being updated with `setCellMeta` calls.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR fixed the issue from #9734 by introducing a new, internally used meta property.
After this change, the automatically-added meta props (like `renderer`, `editor` etc, added when changing the `type` meta) can be overwritten both by setting the actual props in question and setting another `type`.

### How has this been tested?
Added new test cases.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9734 

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jansiegel** [comment]
@budnix If you have any suggestions on how to fix this more elegantly without modifying the principles of the current meta manager, I'm open for suggestions.

**Review by budnix — CHANGES_REQUESTED** [review]
Thanks for the PR. However, I think there is still some work to be done. For example, when the table is initialized with `type: "date"` and after changing the cell type to `text`, the cell contains artifacts from the previous cell type.
Kapture 2022-10-12 at 11 43 58
(`text` cell type contains `date` validator). The same can be spotted for different cell types. For example, switching from the `password` cell type to `text` lefts the `copyable` property as `false`.

**Comment by jansiegel** [comment]
@budnix Correct me if I'm wrong, but it seems like it's been working like this for a long time? I've checked version `4.0`, and it looks like it does leave the previously-used validators, etc behind as well: http://jsfiddle.net/js_ziggle/2hf6ctzv/.

**Comment by budnix** [comment]
> @budnix Correct me if I'm wrong, but it seems like it's been working like this for a long time? I've checked version `4.0`, and it looks like it does leave the previously-used validators, etc behind as well: http://jsfiddle.net/js_ziggle/2hf6ctzv/.

True. Then, I'd have one suggestion. WDYT to rename the property to `_automaticallyAssignedMetaProps`? A similar pattern is used by one of the [meta mods](https://github.com/handsontable/handsontable/blob/develop/handsontable/src/dataMap/metaManager/mods/extendMetaProperties.js#L53) and the _[ManualColumnFreeze](https://github.com/handsontable/handsontable/blob/develop/handsontable/src/plugins/manualColumnFreeze/manualColumnFreeze.js#L130)_ plugin.

**Review by budnix — APPROVED** [review]
👍

**Comment by aninde** [comment]
Works well on every [tested browser](https://app.qase.io/run/HOT/dashboard/161), unit test also pass. I checked locally whether the change from each type to another and back works.

**Pull request merged**
