### PR TITLE
TypeScript .d.ts type definitions improvement

### PR DESCRIPTION
**Pull request by aaronbeall**
### Context

Addresses: https://github.com/handsontable/handsontable/issues/5736
Also fixes: https://github.com/handsontable/handsontable/issues/5225 https://github.com/handsontable/handsontable/issues/5004 https://github.com/handsontable/handsontable/issues/5091 https://github.com/handsontable/handsontable/issues/5046
Includes fixes for https://github.com/handsontable/handsontable/pull/5719 https://github.com/handsontable/handsontable/pull/5721
Relates to: https://github.com/handsontable/handsontable/issues/5094

This is a sweeping refinement of the type definitions. Main goals were:
- Focus on `GridSettings`, `Hooks` and `Core` methods (ie _not plugins_ except where referenced by settings) to make the Handsontable config _completely typed_. 
- Replace ambiguous types like `any` and `object` and `string` (where literals are expected) with meaningful types. Basically I added a bunch of types to represent the various config objects and hook arguments.

Additional refactoring:
- Added type aliases for common types, like `CellValue`, `CellChange`, `RowObject`. Intentionally left these very wide (ex `CellValue = any`) to avoid breaking things, but it improves readability and any future refactoring of these base types. We could potentially use type arguments to make these even tighter based on users' usage.
- Split `GridSettings` up into `GridSettings -> ColumnSettings -> CellMeta -> CellProperties` in order to sort out some of the issues related to https://github.com/handsontable/docs/issues/12. `GridSettings` still has almost everything. I commented these types in the code for the rationale on this breakdown.
- `DefaultSettings` is a class-like object that creates `GridSettings`, so I updated type annotations to reflect this and replaced all annotations of `DefaultSettings` to the correct type settings type (grid, column, cell).
- Split `Hooks` out into `Events` and `Hooks`, where `Events` is just the `Hooks -> Events` in the docs, and `Hooks` the methods available on the `Handsontable.hooks` namespace. 
- Refined `Element` and `Event` where possible.
- Added `this` types where useful, for example in validators and cells callback.
- Added missing top-level `Handsontable.validators` API.

### How has this been tested?

- Added a bunch of new tests to `npm run test:types`, strengthened coverage using `Required<>` map type. Still adding some more to cover nested config objects.
- Tested in IDE and in browser to inspect the runtime behavior the types should model.
- Generated types using [tsd-jsdoc](https://www.npmjs.com/package/tsd-jsdoc) and compared to definitions using the compiler -- found a handful of missing and wrong definitions this way, would be nice to add a script for this.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/5736
2. https://github.com/handsontable/handsontable/issues/5094

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thanks!

**Comment by aaronbeall** [comment]
I just enhanced the `settings.types.ts` test by adding most of the examples in the docs to verify they work.

**Comment by AMBudnik** [comment]
You're really helpful. That's a great job!

**Comment by krzysztofspilka** [comment]
@aaronbeall I'm deeply impressed by the amount of work you put into this.

Could you please shoot me an email at chris(at)handsontable.com? I would like to discuss one thing before we merge these changes. Thanks so much!

**Comment by jansiegel** [comment]
@aaronbeall That's _really_ impressive!

I have one small suggestion, though:
> * Split `Hooks` out into `Events` and `Hooks`, where `Events` is just the `Hooks -> Events` in the docs, and `Hooks` the methods available on the `Handsontable.hooks` namespace.

Internally we tend to use the term "events" as native DOM events, and "hooks" as our internal events. That being said, splitting the hook API and hooks themselves, just like you did, is definitely a good idea.

I think it would be good to move the `Events` interface into the `Hooks` namespace. This way, we avoid the confusion, as `Handsontable.Hooks.Events` is pretty self-explanatory. 

Other than that everything looks great!

**Comment by wojciechczerniak** [comment]
@AMBudnik List of issues that this PR will close:

- [ ] #5052 (PR #5767)
- [ ] #5599 (PR #5767)
- [ ] #5004 (PR #5767)
- [ ] #5225  (PR #5767)
- [ ] #5721 (PR #5767)
- [ ] #5719 (PR #5767)
- [ ] #5736 (PR #5767)
- [ ] #5091 (PR #5767)
- [ ] #5046 (PR #5767)

**Comment by AMBudnik** [comment]
@wojciechczerniak awesome!

**Comment by aaronbeall** [comment]
> Internally we tend to use the term "events" as native DOM events, and "hooks" as our internal events. That being said, splitting the hook API and hooks themselves, just like you did, is definitely a good idea.

> I think it would be good to move the `Events` interface into the `Hooks` namespace. This way, we avoid the confusion, as `Handsontable.Hooks.Events` is pretty self-explanatory.

Yep, sounds good. Done! TBH I wanted to keep the event hooks interface as `Hooks` and name the new top-level API namespace something else, but then it wouldn't follow the naming pattern of all the other top-level APIs.

**Comment by jansiegel** [comment]
@aaronbeall 
> Edit: Hmm... how about putting `Hooks` in `Hooks.Methods`?

Good idea, `Hooks` being just a namespace would be even more consistent with our current documentation structure 👍

**Comment by aaronbeall** [comment]
Done

**Comment by AMBudnik** [comment]
Aaron, thanks to you we got a brand you definition file for the Handsontable 7.0.0 released today.

Thank you :)

**Pull request merged**
