### PR TITLE
Add a new behavior for Cmd/Ctrl + Shift + Arrow keys keyboard shortcuts

### LINKED ISSUE #9365: Change behavior of the keyboard shortcuts that extends the selection
### Description

The issue is about changing the behavior of some keyboard shortcuts that allow expanding, changing, or somehow modifying cells' selection. The issue is part of the [Epic issue](https://github.com/handsontable/handsontable/issues/9361) and here are the expected results:

Shortcut | Expected behavior
-- | --
Cmd/Ctrl + Shift + Arrow up | Extend the selection of cells to the first cell of the current column 
Cmd/Ctrl + Shift + Arrow down | Extend the selection of cells to the last cell of the current column 
Cmd/Ctrl + Shift + Arrow left | Extend the selection of cells to the left-most cell of the current row 
Cmd/Ctrl + Shift + Arrow right | Extend the selection of cells to the right-most cell of the current row 
Shift + Page up | Extend the selection of cells for one screen up 
Shift + Page down | Extend the selection of cells for one screen down

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR changes the behavior of the Home/End, Ctrl/Cmd + Home/End keyboard shortcuts. Now it works as follows:

Shortcut | Expected behavior
-- | --
Cmd/Ctrl + Shift + Arrow up | Extend the selection of cells to the first cell of the current column. Only the last selection layer is taken into account while extending the selection. 
Cmd/Ctrl + Shift + Arrow down | Extend the selection of cells to the last cell of the current column. Only the last selection layer is taken into account while extending the selection. 
Cmd/Ctrl + Shift + Arrow left | Extend the selection of cells to the left-most cell of the current row. Only the last selection layer is taken into account while extending the selection. 
Cmd/Ctrl + Shift + Arrow right | Extend the selection of cells to the right-most cell of the current row. Only the last selection layer is taken into account while extending the selection. 
Shift + Page up | Extend the selection of cells for one screen up 
Shift + Page down | Extend the selection of cells for one screen down 

Some edge-cases, limitations, or additional new behavior:
 * `Cmd/Ctrl + Shift + Arrow up/down` Does not have any effect when the last selection layer selects at least one column header
No effect:
Kapture 2022-04-12 at 10 23 40
There is an effect (the last selection layer selects a cell):
Kapture 2022-04-12 at 10 27 59
 * `Cmd/Ctrl + Shift + Arrow left/right` Does not have any effect when the last selection layer selects at least one row header
No effect:
Kapture 2022-04-12 at 10 32 52
There is an effect (the last selection layer selects a cell):
Kapture 2022-04-12 at 10 33 38
 * `Shift + Page up/down` With new behavior, the viewport scrolling works like in Google Spreadsheet and Excel, where the viewport offset is preserved while paging the table.
Page down:
Kapture 2022-04-12 at 10 43 11
Page up:
Kapture 2022-04-12 at 10 43 52

Additionally, I added RTL support for Jasmine ASCII table matcher within the PR. This causes to update some E2E tests not related to the PR's topic (1b6a03042e2f09c340ff6226ef56ec6b6e4861b8).

### How has this been tested?

I tested the changes locally and covered the new behavior with new E2E tests.

### Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. fixes #9365

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Review by wszymanski — APPROVED** [review]
The behaviour that `Shift+PageUp` doesn't look intuitively for me (the first seen cell on the below image is `C48` and shortcut moves selection to `C22`), but I can see that Excell works similarly (totally the same?). I assume that it meets project criteria.

https://user-images.githubusercontent.com/141330/163982313-6246cc35-28be-4bbe-8bc9-1625f0dc522e.mp4

**Comment by budnix** [comment]
> The behaviour that `Shift+PageUp` doesn't look intuitively for me (the first seen cell on the below image is `C48` and shortcut moves selection to `C22`), but I can see that Excell works similarly (totally the same?). I assume that it meets project criteria.

Exactly, the same behavior can be spotted in Google Spreadsheets and Excel.

**Comment by aninde** [comment]
Everything is correct, but I noticed that `cmd + alt + arrows` still work the same as `cmd + shift + arrows`. Shouldn't we block this as it is not specified in the secification?

**Review by aninde — COMMENTED** [review]
https://github.com/handsontable/handsontable/pull/9388#issuecomment-1103787652

**Comment by budnix** [comment]
> Everything is correct, but I noticed that `cmd + alt + arrows` still work the same as `cmd + shift + arrows`. Shouldn't we block this as it is not specified in the secification?

On macOS, there is no ALT. I've tried `Cmd+Option+Arrows`, and there is no effect. Only native behavior works (switching tabs on Chrome). On Windows I've tried `Ctrl+Alt+Arrows` with the same results as on macOS - nothing changed, only native browser reaction.

**Comment by aninde** [comment]
> > Everything is correct, but I noticed that `cmd + alt + arrows` still work the same as `cmd + shift + arrows`. Shouldn't we block this as it is not specified in the secification?
> 
> On macOS, there is no ALT. I've tried `Cmd+Option+Arrows`, and there is no effect. Only native behavior works (switching tabs on Chrome) and that is good. On Windows I've tried `Ctrl+Alt+Arrows` with the same results as on macOS - nothing changed.

True, I checked wrong demo (cashe in the browser). Everythings works as expected. Demo with this version https://jsfiddle.net/goxf2bn9/.

**Review by aninde — APPROVED** [review]

**Pull request merged**
