### PR TITLE
New docs: Fix production docker build

### PR DESCRIPTION
**Pull request by Siemienik**
### Context
Production build should not reference into `next` version. That was and failed production build. This PR fix it.

### How has this been tested?
```
npm run docs:docker:build:production
# should run successfully
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8178 
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by budnix** [comment]
@Siemienik Can you sync the PR with the latest changes of the `feature/issue-7624` branch? I see a lot of errors comes from the eslint and I want to be sure that this PR won't introduce any new issues.

**Review by budnix — CHANGES_REQUESTED** [review]
On my stack I've got another error:
image

**Comment by Siemienik** [comment]
> On my stack I've got another error:

Hey, You run `docs:build`. However, these changes concern `docs:docker:build:production`.


AD. the error - some packages are missed,  I suppose `npm install` might resolve it.

**Comment by budnix** [comment]
> > On my stack I've got another error:
> 
> Hey, You run `docs:build`. However, these changes concern `docs:docker:build:production`.
> 
> AD. the error - some packages are missed, I suppose `npm install` might resolve it.

Seems to work after reinstall dependencies 👍

**Review by budnix — APPROVED** [review]

**Pull request merged**
