### PR TITLE
Updated style setters based on proper css style

### PR DESCRIPTION
**Pull request by droda59**
Changed style setters according to CSSStyle validations.

### Related issue(s):
1.https://github.com/handsontable/handsontable/issues/5291

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @droda59 

Could you please sign our [CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)? Without this signature I won't be able to pull the code to the official version of Handsontable.

**Comment by droda59** [comment]
Hi Aleksandra, I just signed it, thank you

**Comment by jansiegel** [comment]
@droda59, could you change the target branch to `develop`, and most preferably apply your changes to a more recent version of the file, so we could avoid merging conflicts? Thanks!

**Comment by jansiegel** [comment]
Closing this because of the merge conflicts. Work continued in #5624.

**Pull request closed without merging**
