### PR TITLE
nl_NL language support.

### PR DESCRIPTION
**Pull request by slidertom**
### Context

Applies NL language support.

### Types of changes
Additional language file : NL

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing this PR.

**Comment by slidertom** [comment]
What have to be done to unblock merging?

**Comment by AMBudnik** [comment]
Hi @slidertom 

the PR (besides the confirmation from the community) is missing a new (empty) line at the end of the document.

**Comment by AMBudnik** [comment]
Thank you for doing the changes. Now all tests pass

**Comment by webjazznl** [comment]
As a Dutch native speaker, I say let's roll...

**Comment by slidertom** [comment]
Can be something done to unblock merging? :)

**Comment by wojciechczerniak** [comment]
@slidertom We're waiting for community. Currently we have 1 vote here and 3 votes in #5156. This gives us 4 out of 5 votes needed to merge.

**Comment by AMBudnik** [comment]
Great! Thanks for merging.

**Comment by AMBudnik** [comment]
Hi @slidertom @webjazznl 

Dutch is now the official language of Handsontable Pro 6.1.0+

Thank you for your effort to create and check it

**Comment by adrianszymanski89** [comment]
Hi @slidertom. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Comment by slidertom** [comment]
Sorry, I can not help....

**Comment by webjazznl** [comment]
Of course u can... what is your question?

**Comment by AMBudnik** [comment]
@webjazznl cool!
We're in the last stage of introducing this functionality https://github.com/handsontable/handsontable/issues/10112 and are gathering five phrases in all the languages that we support at the moment. Could you please help us to translate them? 

* Copy with header
* Copy with headers
* Copy with group headers
* Copy header only
* Copy headers only

**Pull request merged**
