### PR TITLE
Add before/after hooks for undo and redo

### LINKED ISSUE #1587: Undo after removing a row doesn't fire afterChange
I am using an Ajax dataset, so when I remove a row I also then fire off (using the beforeRemoveRow event) an Ajax call to delete the corresponding record from the database.  However, if I then undo that remove row, it appears back in the table like it should, but doesn't fire any events so I can't send another request to re-add it to the database.

Ideally it would fire an afterChange event for all the cells in the row, so that I can use the autocommit function to then send the entire row back to the database.

### PR DESCRIPTION
**Pull request by tmichel**
This pull request adds four new hooks. Namely:
- beforeUndo
- afterUndo
- beforeRedo
- afterRedo

In all cases a copy of the `action` object is passed to the handler. A new `type` property has been added to the Action classes so we can determine what kind of action was undone/redone. The type property can be one of the following values: 
- change
- create_row
- remove_row
- create_col
- remove_col

`beforeUndo` and `beforeRedo` can cancel the operation by returning `false`.

Every hook has the same signature:

``` js
$container.handsontable({
  beforeUndo: function (action) {
    // ...
  }
});
```

The properties of `action` parameter depend on which action was undone/redone. The possible properties:
- data (change, remove_row, remove_col)
- type (always)
- index (create_row, create_col, remove_row, remove_col)
- amount (create_row, create_col)

This pull request fixes #1587.

### CODE REVIEW

**Comment by optimix** [comment]
FYI, hooks.execute() fails if beforeUndo & beforeRedo is not provided.

**Comment by vo-va** [comment]
@tmichel Hi, could you update your pull-request with my (commit) https://github.com/vo-va/handsontable/commit/93ecf304cf0ee1431e85e1b71e7501953b88b1de I just made slightly changes to make your pull request work with 0.12.4 release.

**Comment by tmichel** [comment]
@vo-va I pulled in your changes. Thanks for fixing the merge conflicts. I haven't had time to clean it up properly.

**Comment by vo-va** [comment]
@tmichel Thank you. I don't know why but my commit failed tests, on my computer all tests are passed fine. And I even test my commit again with Travis CI here is the [log](https://travis-ci.org/vo-va/handsontable/builds/49194470) (just added little comment for make new commit). Could you rerun build in Travis CI for pass the tests?

**Comment by tmichel** [comment]
@vo-va I don't know what was wrong but now the build passed. I ran without errors on my machine as well. Very strange.

**Comment by rich-glow** [comment]
I would love to see this functionality added so I can react to undeleting rows.

What is the state of this PR? What do we need to do to get this merged?

**Comment by tmichel** [comment]
@rich-glow I think there is not much to do. There is a small merge conflict with `master`. Either I can merge master back into my branch so it merges without conflict or the other way around and somebody has to merge the feature branch manually back to master.

**Comment by mpusarla** [comment]
We wanted to enable the undo functionality after this fix is merged in. Hope this will be available soon.

**Comment by tmichel** [comment]
@jansiegel or @warpech I think there is real demand for this feature. What do I have to do to get this merged?

**Comment by rich-glow** [comment]
+1 @tmichel it's super useful :)

**Comment by jakedeichert** [comment]
I think this is a really important change. It's been almost a year since the last comment. Has there been any decisions regarding this change?

**Comment by AMBudnik** [comment]
Hi 
@tmichel @jakedeichert  @rich-glow @mpusarla @vo-va @optimix @mariotacke 
I just added this idea to our Roadmap. You can vote for it here: 
https://trello.com/c/CAL4syZb/43-add-before-after-hooks-for-undo-and-redo

**Comment by AMBudnik** [comment]
Thank you for leaving your votes and sharing your opinions.

 We have added the [`beforeUndo`](https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:beforeUndo), [`afterUndo`](https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:afterUndo), [`beforeRedo`](https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:beforeRedo) and [`afterRedo`](https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:afterRedo)

**Pull request closed without merging**
