### PR TITLE
Fix: fix getSourceDataAtCol always get undefined issue

### PR DESCRIPTION
**Pull request by chenbojian**
### Context

Filter plugin of handsontable-pro depends on getSourceDataAtCol to load data. But when we use function as the data column setting, it will get all value as undefined. This will make filter plugin not work properly. An example is posted in https://github.com/handsontable/handsontable-pro/issues/14

### How has this been tested?

Yes

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature or improvement (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. https://github.com/handsontable/handsontable-pro/issues/14

### Checklist:

- [x] My code follows the code style of this project,
- [] My change requires a change to the documentation.

### CODE REVIEW

**Comment by chenbojian** [comment]
Any question about this PR? @AMBudnik

**Comment by AMBudnik** [comment]
Hi @chenbojian 

I can see that you did not signed the [CLA](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo/edit#response=ACYDBNhV1MTfdr_NRjtxSKISOkC3HVhagIFXk_ZELGMEB_3L4uIlD2CG9AtqXYs). Please sign it

**Comment by chenbojian** [comment]
I have assigned that, [This](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo/edit#response=ACYDBNiV23YmXbRcZMYKX0jxPxX7OUgqS1z8Yb_Fdz3VJNpfWT-l__zRcI8o0dQ) is me.

**Comment by AMBudnik** [comment]
Thank you the status or the PR has been changed

**Comment by chenbojian** [comment]
Any reason that this is still not reviewed?

**Comment by AMBudnik** [comment]
Sorry. Recently, we have been missing some hands to work. Until the end of January, we are planning to review all the PR (or at least the ones that are waiting for a longer period of time).

**Comment by pnowak** [comment]
Hi.

In the meantime, language support has come, so please merge your develop branch and re-PR. Then we will be able to test Your solution.

Thanks.

**Comment by chenbojian** [comment]
I have updated my code with the newest develop branch. Please help test that.

**Comment by AMBudnik** [comment]
Thank you for an update @chenbojian 
We should be ready to check it at the beginning of this week.

**Comment by chenbojian** [comment]
Can you help review and merge this? I am waiting for new release to remove my own patched code in our project.

**Comment by AMBudnik** [comment]
Hi @chenbojian 

sorry for keeping you waiting. One of our colleagues has been asked to review this PR but as we were preparing a breaking change release we needed all hands to make it work.

**Pull request merged**
