### PR TITLE
Translations for Norwegian Bokmål

### PR DESCRIPTION
**Pull request by TheSimoms**
### Context

Added Norwegian (Bokmål) translation.

### How has this been tested?

Checked that the change conforms with your code style. Other than that, no tests are required, as this is just a translational change.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):

None that I am aware of.

### Checklist:
- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you very much for your feedback @TheSimoms 
I'd be happy to see this translation.

To pull the language translation we need to get at least 5 positive feedback from other users. That is why I created a post at https://github.com/handsontable/handsontable/issues/4694

**Comment by fosils** [comment]
I am a native-speaking Norwegian and I can confirm that these transactions are correct.

**Comment by AMBudnik** [comment]
Thank you very much @fosils

**Comment by AMBudnik** [comment]
We just got 5th confirmation so we're ready to review the code :)

**Comment by AMBudnik** [comment]
Thank you @TheSimoms @fosils 

Norwegian translation has been added to the official version of Handsontable and it is available from v 4.0.0

**Comment by adrianszymanski89** [comment]
Hi @TheSimoms. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Comment by fosils** [comment]
@adrianszymanski89 Sorry if I am butting in here, but here are the three translations. I am a native Norwegian:
- Copy with headers: Kopier med overskrifter
- Copy with group headers: Kopier med gruppeoverskrifter
- Copy headers only: Kopier kun overskriftene

**Comment by TheSimoms** [comment]
@fosils Thanks, that looks good to me 👍

**Comment by adrianszymanski89** [comment]
Hi @fosils & @TheSimoms  

Thank you for the translation. In the meantime, we've made some changes to the specification. The current version looks like this:

- Copy with header
- Copy with headers
- Copy with group headers
- Copy header only
- Copy headers only

In cases where there is the singular and plural form, it should be done as an `array`, like here:

https://github.com/handsontable/handsontable/blob/feature/issue-2288/handsontable/src/i18n/languages/en-US.js#L52-L54

If you could update your PR, that would be great :)

**Comment by TheSimoms** [comment]
@adrianszymanski89 Here are the translations.

    Copy with header: Kopier med overskrift
    Copy with headers: Kopier med overskrifter
    Copy with group headers: Kopier med gruppeoverskrifter
    Copy header only: Kopier kun overskriften
    Copy headers only: Kopier kun overskriftene

**Comment by adrianszymanski89** [comment]
@TheSimoms 

Thank you!

**Pull request merged**
