### PR TITLE
Sorting of checkboxes will work + fixed not proper way of displaying some empty cells

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

Sorting of checkboxes doesn't work. We described some requirements for the bug fix:

- [x] Values such as empty string (`''`) and `undefined` will become unchecked checkbox (consistency with other data types)

113283103-1eb24680-92e8-11eb-9687-c764dcff935d

- [x]  We will display above values as an unchecked checkboxes - the same as for `null` (not as "fully" empty cells - alternative solution); It's worth to mention that `delete` and `backspace` keys on the cell of type `checkbox` doesn't remove checkbox, but just uncheck it.

`Note:` This approach won't make breaking change and what's more won't complicate sorting (there will be no need to determine how "fully" empty cell behave when there has been applied sorting).

- [x] The `sortEmptyCells` option will configure how empty cells are sorted. As an "emptyCell" we will recognize cells with `undefined`, `null` and `''` values.
- [x] We will do sorting of `#bad-value` the same as do it GS.
- [ ] There may be needed refactor of checkbox renderer (move validation to another place) and change in validation process to make it similar to another data types and to GS. However, it should be done within another task, as it is a breaking change.

Now
image

- [x] Empty cells and unchecked cells won't be moved between themselves. Sorting will behave as stable sorting algorithm for them.
- [x] Sorting will work for `checkedTemplate` and `uncheckedTemplate`.
- [x] Docs for sorting checkboxes updated within https://github.com/handsontable/docs/issues/305.

### How has this been tested?

Manual tests with different `checkedTemplate`, `uncheckedTemplate` and `sortEmptyCells` configurations and different values.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #4047

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Review by Osky772 — COMMENTED** [review]
I wonder if we can extend checkboxes' "empty cell" behavior with zero and non-zero numbers. `0` would indicate `unchecked` checkboxes and non-zero numbers `checked` checkboxes?

**Review by Osky772 — APPROVED** [review]
I don't have any comments, the code looks awesome and it's working 🙌

**Comment by wszymanski** [comment]
> I wonder if we can extend checkboxes' "empty cell" behavior with zero and non-zero numbers. `0` would indicate `unchecked` checkboxes and non-zero numbers `checked` checkboxes?

As an empty cell we consider only values `''`, `null` and `undefined` by default. In my opinion type of data should not affect it. User still can do it by defining `checkedTemplate` and `uncheckedTemplate`.

**Comment by wojciechczerniak** [comment]
Second that ☝️

**Review by aninde — APPROVED** [review]
@wszymanski Very good job as I couldn't find regression errors! Works on all browsers we support, including IE 11 on Windows 10.

**Pull request merged**
