### PR TITLE
Support dataSchema callback for array-based data

### PR DESCRIPTION
**Pull request by YipYipX4**
Added 4 lines of code to support the dataSchema setting when using an array-based data source.  The dataSchema setting can be a template array or a callback function that returns an array.  In either case, the array will be cloned.

### CODE REVIEW

**Comment by YipYipX4** [comment]
Here's a better description of my changes:

In the createRow method there is different code executed for different types of source data.  When the source data is an array (of arrays), then the existing code would simply create an array of nulls for the new row (one for each visible column -- I think this logic has a bug because it is not taking into consideration that some columns may not be displayed, but I did not touch this existing code).  

I didn't want nulls.  I wanted to provide some default values for each new row, so I added the "dataSchema" setting, but it didn't work, so I had to modify the handsontable source code.

I simply added an "if" statement to check if the user provided a "dataSchema" setting in the settings object.  If so, then I call the existing getSchema method (which handles calling dataSchema if it is a function).  I expect to get an array (which can include values for hidden columns), and I clone it to ensure we aren't always referring to the same data.

To be clear, the new logic only executes if the user provided a dataSchema setting while using an array-based data source (which previously would have no effect).

```javascript
    if (this.instance.dataType === 'array') {
      if (this.instance.getSettings().dataSchema) {
        row = JSON.parse(JSON.stringify(this.getSchema()));  // Clone template array
      } else {        
        //... did not change this code ...
      }
    } else if (this.instance.dataType === 'function') {
      //...
```

Please accept this pull request.  Thanks!

**Comment by YipYipX4** [comment]
I created an issue for this:
https://github.com/handsontable/handsontable/issues/2456

**Comment by halfnibble** [comment]
I am in favor of this change.

We need a simpler method to have pre-populated cells in new rows.

**Comment by halfnibble** [comment]
Would this also resolve this issue? Or no?

https://github.com/handsontable/handsontable/issues/446

**Pull request merged**
