### PR TITLE
Fix #3914: nestedRows plugin not reloading data

### LINKED ISSUE #3914: nested rows doesn't work with loadData
### Description
I have a table with NestedRows plugin enabled. The table is initialized with hierarchical data.
I remove all rows: hot.alter('remove_row', 0, hot.countRows());
I add one row with nested rows.
I call hot.rerender()
I get  Uncaught TypeError: Cannot read property '__children' of undefined
The expected behaviour was that this table shows only the one row with its children that was added after removing all previous rows.

### Steps to reproduce

See above and use the JSFiddle provided.

### Demo
http://jsfiddle.net/6qhtp77q/

### Your environment
* Version: handsontable-pro-1.7.4
* Browser Name and version: Chrome 54.0.2840.100 (64-bit)
* Operating System: Debian Linux 8

### PR DESCRIPTION
**Pull request by frankie567**
### Context
When using `nestedRows` plugin, loading a new set of data won't refresh the table.

It turns out the nested rows `DataManager` never gets the new data, it always keeps a copy of the original set.

As we see [here](https://github.com/handsontable/handsontable/blob/90752fda8be5ac6b2708e0f2de8809d51dc1be4f/src/plugins/nestedRows/data/dataManager.js#L25), it is initialized with the source data, but never get reassigned after.

### How has this been tested?
Added two E2E tests.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

Solution I found was to listen to `afterLoadData` hook in order to update the `DataManager` data and rebuild its internal cache. Not sure if it's the best way to go, but it sounds quite reasonable to me.

### Related issue(s):
1. #3914 

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

ESLint passes. Added a minimal JSDoc to the hook callback, following the style of the others.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for providing the pull request.

Can you change the branch to `develop` and sign [our CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)? Without that I won't be able to schedule a code review.

**Comment by frankie567** [comment]
Hi @AMBudnik! All done 👍

**Comment by AMBudnik** [comment]
Thank you.

**Comment by AMBudnik** [comment]
Hey @frankie567 

we've just release v 7.2.0 with this fix. Thank you for contributing :)

**Pull request merged**
