### PR TITLE
Translations for Spanish Spain

### PR DESCRIPTION
**Pull request by thaednevol**
### Context
Spanish support

### How has this been tested?
No. Because this is just a translational change.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #4696
2.
3.

### Checklist:
- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you very much for sharing the Spanish version of our labels and signing CLA.
I have [made a topic](https://github.com/handsontable/handsontable/issues/4764) that will hopefully help us to gather 5 confirmations faster.

**Comment by alexon1234** [comment]
Seems like is necessary that an approved review, approve the translation

**Comment by alexon1234** [comment]
@AMBudnik One thing this PR is only trying to merge handsontable/master branch into handsontable/development branch.

There is no user branch

**Comment by AMBudnik** [comment]
Hi @thaednevol 
We just wanted to review the code but the translation that you did is gone and Github does not show the changes that you've made. 

Can I ask you to create the PR once again? Just please create a new repository (from our cloned `develop` branch) and change the files there.

**Comment by AMBudnik** [comment]
Hi @thaednevol 

are you still interested in sharing the code? I really would like to see it being a part of the next official version.

**Comment by AMBudnik** [comment]
I am afraid that I need to close this PR as there is no reply from the Author and the PR cannot be merged in the current build.

**Comment by adrianszymanski89** [comment]
Hi @thaednevol. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Pull request closed without merging**
