### PR TITLE
Issue 5608 getCell should not return undefined

### PR DESCRIPTION
**Pull request by aaronbeall**
### Context

Fixes https://github.com/handsontable/handsontable/issues/5608

### How has this been tested?

`npm run test:e2e`

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/5608

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hey @aaronbeall 

Can I ask you to add some tests?

**Comment by aaronbeall** [comment]
I added test coverage for the -3 and -4 exit codes.

I don't see those Travis tests failing locally when I run `e2e` but I do see these:

> 3) TextEditor should hide whole editor when it is higher then header
> 3.1) Expected -9999 NOT to be around -77 (between -78 and -76)
> 3.2) Expected -9999 NOT to be around -1 (between -2 and 0)

Seems related to my changes, but having a hard time understanding how exactly.

**Comment by aaronbeall** [comment]
Travis is green!

I also wanted to ask: is returning an error code really useful? Seems to make it more confusing and no code was actually handling an error code.

**Comment by AMBudnik** [comment]
> I also wanted to ask: is returning an error code really useful?

to be honest I really do not know. But our CTO already scheduled the PR to be reviewed so I hope they will be able to share more info.

**Pull request merged**
