### PR TITLE
`transform` `scale` PR IE `updateSettings`/window resize problem hot fix

### PR DESCRIPTION
**Pull request by nikersify**
### Context
It seems like with #7496 a problem was introduced on IE11 and below, where running `updateSettings` or resizing the browser window, causing the table to repaint, would cut out a column with the config option `data` set to `Handsontable.helper.createSpreadsheetData(4, 2)` (or similar).

In short, the problem was caused by IE not adding `div` elements to `<table>`'s the same way modern browsers do.

See the comment added inside the `preciseOuterWidth` function's body for more info.

### How has this been tested?
Tested manually on IE.

[skip changelog]

### CODE REVIEW

**Review by wszymanski — CHANGES_REQUESTED** [review]
Huh, it seems that provided code hasn't been tested on `IE` within previous PR.

I suggest to:

- adding "dummy element" to wrapper (`div` being parent of created temporary table).
- remove workaround

**Comment by nikersify** [comment]
We've reached a consensus with @wszymanski to make a change to only run `calculateScaleX` on the wrapper element, instead of `<table>`, which should fix the issue on IE without any workarounds.

**Comment by wszymanski** [comment]
To not loose context after some time I'm just writing that code should be tested on `IE 9+`. We have seen that choosing constant `scaleX` may be not the best solution for different IE browsers.

**Review by wszymanski — CHANGES_REQUESTED** [review]
To not loose context after some time I'm just writing that code should be tested on `IE 9+`. We have seen that choosing constant `scaleX` may be not the best solution for different IE browsers.

**Comment by nikersify** [comment]
Closing due to abandonment.

**Pull request closed without merging**
