### PR TITLE
Adds `afterAutofill` hook

### PR DESCRIPTION
**Pull request by jeremy-smith-maco**
### Context

Adds new hook for when callbacks are required after autofill has been completed.

### How has this been tested?

Tested locally.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6135
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
That's a good idea but we also need tests and typescript definitions, @jeremy-smith-maco

**Comment by jeremy-smith-maco** [comment]
Should be fixed now @AMBudnik

**Comment by AMBudnik** [comment]
looks perfect to me! I'm adding the 'review' label.

**Comment by AMBudnik** [comment]
@jeremy-smith-maco can you add in the **Related issue(s):**
 paragraph that it relates to issue no #6135 ?

**Comment by jeremy-smith-maco** [comment]
Updated @AMBudnik

**Comment by jeremy-smith-maco** [comment]
Added @pnowak

**Pull request merged**
