### PR TITLE
Shorter Translations for French - France

### PR DESCRIPTION
**Pull request by buggythepirate**
Translation for French - France

Fixed the french translation from #4775 (see also #4843). Problem:  handsontable has a maximum number of characters allowed per entry. This translation works around this limit.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #4775
2. #4843
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing @buggythepirate !

**Comment by AMBudnik** [comment]
I've updated https://github.com/handsontable/handsontable/issues/4777

Can I count on your feedback @niio972 @behamon for the French translation?

**Comment by wojciechczerniak** [comment]
Hi @buggythepirate, we've recently put some effort into removing this limitation: #4933 and it was released within 2.0.0 release. Unfortunately #4775 was already closed and went off our radar.

@AMBudnik @wszymanski  Maybe we should just check #4775 again instead voting on new translation? We can decide with @buggythepirate which version of translation is preferred.

**Comment by AMBudnik** [comment]
Sounds good to me @wojciechczerniak As we already have 2 confirmations for the old PR and the Author is the same I do not see any obstacles

**Comment by wszymanski** [comment]
Merged https://github.com/handsontable/handsontable/pull/5044

**Pull request closed without merging**
