### PR TITLE
Improving React Developer Experience

### PR DESCRIPTION
**Pull request by NOtherDev**
### Context

Implementing all the points as discussed in RFC #10767. 

### How has this been tested?

* new features covered with passing unit tests
* all existing unit tests still passing
* all the demo projects work correctly

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. RFC #10767
2. Each of the commits was covered by a separately reviewed PR: https://github.com/handsontable/handsontable/pulls?q=is%3Amerged+is%3Apr+author%3A%40me+

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [x] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by evanSe** [comment]
One thing to note when importing the packaged version of this is that the types are in different places so we get such an error (you can try it with `0.0.0-next-d093c11-20240307`)

image

usually, the d.ts files are in the root https://www.npmjs.com/package/@handsontable/react?activeTab=code

but in the case of the special pre-publish package I prepared they are here
https://www.npmjs.com/package/@handsontable/react/v/0.0.0-next-d093c11-20240307?activeTab=code

**Comment by evanSe** [comment]
@NOtherDev so looking at whats available in the updated documentation http://localhost:8080/docs/react-data-grid/cell-editor/ the following is what I would like to see

- super being called behind the scenes in the `useHotEditor` we should be able to hide this from the user
- the current `setValue` and `getValue` is not exposed to the user as they are conceptually different from react
- pass a configuration object to the `useHotEditor` rather than a function

image

rest of the example

image


Maybe we can also add an improved example to the list of things to do 😄 as the old one is not very nice.

**Comment by NOtherDev** [comment]
@evanSe Here's the PR to sync with the new guides structure - basically merge with `develop`: https://github.com/handsontable/handsontable/pull/10848

**Comment by evanSe** [comment]
> @evanSe Here's the PR to sync with the new guides structure - basically merge with `develop`: #10848

did not seem to work, might be worth a rebase

**Comment by NOtherDev** [comment]
Yeah, sorry @evanSe, fixed. Forgot I can do it directly here 🙂

**Comment by NOtherDev** [comment]
> One thing to note when importing the packaged version of this is that the types are in different places so we get such an error (you can try it with `0.0.0-next-d093c11-20240307`)
> 
> image
> usually, the d.ts files are in the root https://www.npmjs.com/package/@handsontable/react?activeTab=code
> 
> but in the case of the special pre-publish package I prepared they are here https://www.npmjs.com/package/@handsontable/react/v/0.0.0-next-d093c11-20240307?activeTab=code

@evanSe Actually, I think I'm not following fully. Is this about the failing Visual tests? I can see that the test tries to use `@handsontable/react@latest`, which does not resolve to `0.0.0-next-d093c11-20240307` (as this is `next`, not `latest` version), so the demo project does not compile with the not-updated React wrapper. Should I fix the `latest` reference to `next`? Or how should this issue be handled?

**Comment by evanSe** [comment]
> > One thing to note when importing the packaged version of this is that the types are in different places so we get such an error (you can try it with `0.0.0-next-d093c11-20240307`)
> > image
> > usually, the d.ts files are in the root https://www.npmjs.com/package/@handsontable/react?activeTab=code
> > but in the case of the special pre-publish package I prepared they are here https://www.npmjs.com/package/@handsontable/react/v/0.0.0-next-d093c11-20240307?activeTab=code
> 
> @evanSe Actually, I think I'm not following fully. Is this about the failing Visual tests? I can see that the test tries to use `@handsontable/react@latest`, which does not resolve to `0.0.0-next-d093c11-20240307` (as this is `next`, not `latest` version), so the demo project does not compile with the not-updated React wrapper. Should I fix the `latest` reference to `next`? Or how should this issue be handled?

with previous versions of the wrapper the type definitions were published in the root directory and now instead they are in `src/`, something is probably broken in a build process so no need to worry about it

**Comment by NOtherDev** [comment]
Hey guys @evanSe @budnix @jansiegel - is there anything I can do to help moving this PR forward? 
The longer it waits the more conflicts will there be to resolve - I've already resolved docs conflicts once and there's more now.

**Comment by evanSe** [comment]
> Hey guys @evanSe @budnix @jansiegel - is there anything I can do to help moving this PR forward? The longer it waits the more conflicts will there be to resolve - I've already resolved docs conflicts once and there's more now.

@jansiegel has already had a review and is generally happy with the state of the pull request. Currently, we cannot merge it as we are planning on doing another release soon (14.3 on April 16th). This change is considered breaking, so we can only merge it with develop after that date.

No need to worry about any merge conflicts, I will manually update them 😃

**Review by jansiegel — CHANGES_REQUESTED** [review]
I have two main notes:
1. There's a problem with the types. I'm getting this error when importing `@handsontable/react`:
```
Could not find a declaration file for module '@handsontable/react'. '/node_modules/@handsontable/react/es/react-handsontable.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/handsontable__react` if it exists or add a new declaration (.d.ts) file c
```
2. Declaring the "new" renderers and editors under the "editor/renderer" props blocks the user from utilizing the vanilla-based renderers and editors (they can currently be provided that way). Not sure if it's a big issue, though.

**Comment by NOtherDev** [comment]
> 1. There's a problem with the types. I'm getting this error when importing `@handsontable/react`:
> 
> ```
> Could not find a declaration file for module '@handsontable/react'. '/node_modules/@handsontable/react/es/react-handsontable.mjs' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/handsontable__react` if it exists or add a new declaration (.d.ts) file c
> ```
 
@evanSe You mentioned it is related with the build process change of the TS declarations, am I right?

> 2. Declaring the "new" renderers and editors under the "editor/renderer" props blocks the user from utilizing the vanilla-based renderers and editors (they can currently be provided that way). Not sure if it's a big issue, though.

Native ones are still available via `hotRerender` and `hotEditor` respectively.

**Comment by jansiegel** [comment]
> Native ones are still available via `hotRerender` and `hotEditor` respectively.

Oh, alright, I missed that 👍

**Review by budnix — COMMENTED** [review]
Everything looks good except the types. As @jansiegel said, there are some errors in TS. The `types": "./index.d.ts"` entry (and `exports` field) in the `package.json` points to the `index.d.ts` file in the root of the package, but they are missing.

**Comment by evanSe** [comment]
> Everything looks good except the types. As @jansiegel said, there are some errors in TS. The `types": "./index.d.ts"` entry (and `exports` field) in the `package.json` points to the `index.d.ts` file in the root of the package, but they are missing.

Cheers, will fix this tomorrow

**Comment by NOtherDev** [comment]
> Cheers, will fix this tomorrow

@evanSe Is there anything I can help to push it forward?

**Comment by evanSe** [comment]
> > Cheers, will fix this tomorrow
> 
> @evanSe Is there anything I can help to push it forward?

@NOtherDev Sorry did not see your message! Not at the moment, I was cleaning up the pull request and it should get released in the next version of Handsontable (15.0)

**Review by jansiegel — APPROVED** [review]
Looks good 👍

**Review by budnix — APPROVED** [review]

**Comment by jansiegel** [comment]
Closing after merging https://github.com/handsontable/handsontable/pull/11212 to `develop`.

**Pull request closed without merging**
