### PR TITLE
add zoom capacity on setOverlay

### PR DESCRIPTION
**Pull request by elioth010**
this option can make zoom in the container view, like excel zoom in sheet.

### CODE REVIEW

**Comment by krzysztofspilka** [comment]
Thanks for making this pull request, we'll look into it as soon as we can.

**Comment by elioth010** [comment]
@krzysztofspilka  this work only with the overlays bar i'm try to understand well how you create the clone div because when the page make zoom into container the clone is more little than table when i fixed from better way i create a new pull request.

**Comment by krzysztofspilka** [comment]
@elioth010 you may want to wait till we release version 0.13.1 as it'll introduce a breaking change to the structure of Handsontable. I'm very conservative when it comes to merge pull requests but we'll look into it.

**Comment by elioth010** [comment]
@krzysztofspilka Ok i'm waiting for release thanks.

**Comment by mburbea** [comment]
You can probably avoid the Jquery code by just going `element.style.zoom`

**Comment by elioth010** [comment]
@mburbea You have right i'm gona make a new pull request over all these changes thanks.

**Comment by elioth010** [comment]
@krzysztofspilka i have a question, what method is called on scroll vertical to render more rows this is the only i need know to add completely the zoom feature, because in the zoom out over 25% of zoom the scroll not show all records. Thanks.

**Comment by krzysztofspilka** [comment]
@jansiegel could you help us here?

**Comment by mburbea** [comment]
You will need to add an event handler on modifyRowHeight. Here you will
need to multiply the default row height by the zoomfactor. (E.g. the
default row heigjt is 23. And you are zoomed to 1.25 so return 23*1.25).
That should work.

**Comment by elioth010** [comment]
@mburbea Hi Michael, i think than i fixed this is my solution for now maybe found a better way to add this feature for the moment i make a change:
<code>
//in createRowsCalculator i add the zoom
 this.rowHeaderWidth = NaN;
  //get the zoom in the container
  var zoom = this.instance.wtTable.instance.wtTable.holder.parentNode.parentNode.style.zoom;
  if(zoom == ""){
	  zoom = 1;
  }
  var height;
  if (this.instance.wtSettings.settings.renderAllRows) {
    height = Infinity;
  }
  else {
    height = this.getViewportHeight();
  }

  var pos = this.instance.wtScrollbars.vertical.getScrollPosition() - this.instance.wtScrollbars.vertical.getTableParentOffset();
  if (pos < 0) {
    pos = 0;
  }

  var fixedRowsTop = this.instance.getSetting('fixedRowsTop');
  if(fixedRowsTop) {
    var fixedRowsHeight = this.instance.wtScrollbars.vertical.sumCellSizes(0, fixedRowsTop);
    pos += fixedRowsHeight;
    height -= fixedRowsHeight;
  }

  var that = this;
  return new WalkontableViewportRowsCalculator(
    height,
    pos,
    this.instance.getSetting('totalRows'),
    function(sourceRow) {
  //apply the factor 
      return that.instance.wtTable.getRowHeight(sourceRow)*zoom;
    },
    visible ? null : this.instance.wtSettings.settings.viewportRowCalculatorOverride,
    visible ? true : false
  );
};
</code>

and this show all records in the minimum scroll handled, i put like minimum 25%, for getScrollPosition i do the same thin only in the contrary i divide the zoom over the container like the scrollbars are out of the container for the moment work well.

**Comment by jansiegel** [comment]
@elioth010, @krzysztofspilka 
> what method is called on scroll vertical to render more rows

On each scroll event a rendering method is called, which checks if all needed rows/columns are rendered, and if not, recalculates the appropriate row/col indexes using the `WalkontableViewportRowsCalculator` and `WalkontableViewportColumnsCalculator`. 

You might want to check https://github.com/handsontable/handsontable/blob/f6913f2fa8549c9a4f67d053128a015a7fe9ee9c/src/3rdparty/walkontable/src/table.js#L100
and 
https://github.com/handsontable/handsontable/blob/f6913f2fa8549c9a4f67d053128a015a7fe9ee9c/src/3rdparty/walkontable/src/viewport.js#L275

**Comment by AMBudnik** [comment]
Hi @elioth010 

Thank you very much for sharing the pull request with us!

Yesterday we have changed the Contributing policy, a new file can be found [here](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md). As you can see the first obligatory step is to sign a CLA document that will allow us to check your code and (if it meets project requirements) merge it to Handsontable.

As most of the PR in our repository are 3 months+ old we have decided to close them all and reopen immediately after the author confirms that all the steps of the [Contributing file](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) have been accomplished. 
In the same time, I am really sorry that we have waited so long to provide the correct pull request process. I hope that now we will be able to build the perfect library together :)

ps. if you have added more than one pull request please share all their numbers in one post. Thanks in advance!

**Comment by HACK1989** [comment]
@elioth010 I wanna know the handsontable in 6.2.2 which supported zoom-in ?

**Comment by AMBudnik** [comment]
Hi @HACK1989 there are still some issues related to zooming
https://github.com/handsontable/handsontable/issues/5203
https://github.com/handsontable/handsontable/issues/5943

**Pull request closed without merging**
