### PR TITLE
SVG borders: Respond to dynamic changes in selection border col…

### PR DESCRIPTION
**Pull request by warpech**
### Context

This PR is a response to the comment https://github.com/handsontable/handsontable/issues/6467#issuecomment-566078889. It the selection borders, selection corner (desktop) and selection handles (mobile) to respond to the dynamic changes of width and color setting.

For example, use the below code in Handsontable to set border of the currently selected cell to be "1px green":

```js
hot.selection.highlight.cell.settings.border.width = 1;
hot.selection.highlight.cell.settings.border.color = 'green';
hot.render();
```

Default selection settings:

```js
hot.selection.highlight.cell.settings.border.width = 2;
hot.selection.highlight.cell.settings.border.color = '#4b89ff';
hot.selection.highlight.fill.settings.border.width = 1;
hot.selection.highlight.fill.settings.border.color = '#ff0000';
hot.selection.highlight.areas.forEach((selection) => {
  selection.settings.border.width = 1;
  selection.settings.border.color = '#4b89ff';
});
hot.render();
```

☢️ However, there is one serious pitfall: `selection.highlight.areas` objects are instantiated only after they are used for the first time. So you can only set them after the end user made an area selection (multiple area selections) for the first time.

### How has this been tested?
I added an automated test for desktop and mobile.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/6467#issuecomment-566078889
2. https://github.com/handsontable/handsontable/issues/6538
3. https://github.com/handsontable/handsontable/issues/2487

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by aninde** [comment]
I checked everything, including commits from the beginning of December, which repaired case 5 (white spaces in colors) and case 6 (colors order). https://github.com/handsontable/handsontable/pull/6157#issuecomment-562557048.
 I didn't find regression and other bugs, but I had a problem reproducing a new feature. With the help of @warpech  I was able to write it in the function and only in this way it worked in my environment. I need to debug those to make a demo. Right now I can show on gif working of `selection.highlight.areas` 
```
function changeSelection() {
        hot.selection.highlight.cell.settings.border.width = 2;
        hot.selection.highlight.cell.settings.border.color = 'red';
        hot.selection.highlight.fill.settings.border.width = 2;
        hot.selection.highlight.fill.settings.border.color = 'pink';

        hot.selection.highlight.cell.settings.border.cornerVisible = false; //example from #6538
        hot.selection.highlight.cell.settings.border.lineStyle = true; //example from #6538

        hot.selection.highlight.areas.forEach((selection) => {
            selection.settings.border.width = 2;
            selection.settings.border.color = 'green';
        });
        hot.render()
    }
    window.changeSelection = changeSelection;
    window.hot = hot;
```
changeSelection-usage-svg-ff

**Comment by aninde** [comment]
I found also that `selection.highlight.fill.settings.border` hides under fixed / frozen col / row. But this problem only occurs on this PR, not on https://github.com/handsontable/handsontable/pull/6594. On below Prntscr row 1 & 2 are fixed.
Screenshot 2020-01-08 at 16 26 39

**Comment by aninde** [comment]
Despite the fact that this version built from this Pr contains [commits that fix the color order](https://github.com/handsontable/handsontable/pull/6157#issuecomment-562557048), just like the PR https://github.com/handsontable/handsontable/pull/6594, there are clearly differences between them with the fixed options.

This version has a bug. On the fixed custom border, which is hardened in the code and corresponds to this border, e.g.`custom border-bottom` for the `fixedRowsTop bottom border`, is displayed not according to the order specified in the requirements. Lighter applies to darker at the same thicknesses. This can be seen after event, mouse click or scrolling. This does not appear on https://github.com/handsontable/handsontable/pull/6594.

#### Code:
```

customBorders.push({
                row: i,
                col: j,
                top: {
                    width: 3,
                    color: 'black',
                },
                left: {
                    width: 3,
                    color: 'black',
                  },
                  bottom: {
                    width: 3,
                    color: 'yellow',
                  },
                  right: {
                    width: 3,
                    color: 'pink',
                  }
            })
```
#### Case 1 - after clicking by mouse
Left is #6593, right is #6594 
image
Screenshot 2020-01-09 at 14 15 52
Screenshot 2020-01-09 at 14 15 25

#### Case 2 - scrolling
6593-chrome-stage2

**Comment by aninde** [comment]
> I found also that:
> 
>     1. `selection.highlight.fill.settings.border` hides under fixed / frozen col / row and over But this bug only occurs on this PR, not on #6594. On below Prntscr row 1 & 2 are fixed.
> 
>     2. Hovewer `fill-border` - _pink line_, can cover `customBorder` is they have same thickness. This occurs only here. To the very custom borders we had assumptions that something thicker and darker was to be on top. Should this not be consistent with this?
>        Screenshot 2020-01-08 at 16 26 39

`FillHandle` and `hightlight.fill` are under fixed border on stable 7+v. too. https://jsfiddle.net/jrkbe6dt/ It is not really regression, but it works different then on #6594. On #6594 they are on top of the fixed border. We have no assumptions, so it's hard for me to know if it's a bug or not a bug.

`v. 7.3.0` https://jsfiddle.net/jrkbe6dt/
image (5)

**Comment by warpech** [comment]
As discussed on the today's status meeting, I will merge this PR without review to the "master" PR https://github.com/handsontable/handsontable/pull/6157, because having a single source-of-truth PR is easier both for code reviewer and the tester.

**Pull request merged**
