### PR TITLE
Add missing react next demo packages

### PR DESCRIPTION
**Pull request by leriel**
### Context
Please do not merge this pull request. I am creating it only to better understand packages spread across the repo. As i am preparing to create PR that's going to overwrite much of this demo

What i did:
1. Clone repo
2. cd examples/next/docs/react/demo/
3. npm install
4. npm run start
5. npm run build
6. npm run test

Steps 4 and 5 failed with 
```
[eslint] Failed to load config "react-app" to extend from.
```
Because of failed build i could not run tests. When i added `eslint-config-react-app` i could start, build, and run tests.
As i understand this, `eslint-config-react-app` package is currently missing from this demo. However, given how it's present in every demo package-lock.json, i understand i may be missing a step

```
npm --version
9.8.0
node --version
v20.5.0
```

I understand that "react-scripts" (https://github.com/handsontable/handsontable/blob/develop/examples/next/docs/react/demo/package.json#L25) have `eslint-config-react-app` dependency. For some reason, latter does not install.

Thanks

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
8.
9.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by leriel** [comment]
Hi @evanSe, nice to meet you! :) 

Much like you, i discovered vite based projects are treated differently by stackblitz - they are being assigned webcontainer environment. Reason why i haven't closed this PR and opened next is, because unfortunately stackblitz /github endpoint hangs up on cloning some of my branches :/

[This](https://github.com/leriel/handsontable/tree/react-next-demo-vite/examples/next/docs/react/demo) is react demo with react-app-rewired replaced with vite. Back when it still did clone, it worked xD [Currently it hangs on cloning](https://stackblitz.com/github/leriel/handsontable/tree/react-next-demo-vite?file=package.json)

It has:
* all tests retained and all tests passing
* changed from ts to js (for simplicity, no issue having vite/ts though)

This is more simple example that still clones to this day and demonstrates working hot+vite: https://stackblitz.com/github/leriel/stackblitz-vite-test/tree/handsontable?file=package.json


I later [discovered](https://stackblitz.com/github/leriel/stackblitz-test/tree/cra?file=README.md) that plain CRA does work on stackblitz. [Here](https://stackblitz.com/github/leriel/handsontable/tree/react-next-demo-cra) is stackblitz link to my branch, which has just rewired replaced with CRA, but again it hangs cloning. Branch [here](github.com/leriel/handsontable/tree/react-next-demo-cra)

Let me know if opening PR with swap to either CRA or vite helps you. Until they can be actually cloned by stackblitz, it doesn't seem like it would help though. I can change hot+vite to ts as well

**Comment by leriel** [comment]
As for Angular demo, there is actually a [way to make it work with vite](https://stackblitz.com/github/hiepxanh/angular-vite-example?file=src%2Fmain.ts,tsconfig.json). I'm not sure how valuable would that be for you (i would suspect angular community is 99,9% ng based), but i'm happy to hack up angular+vite demo :)

**Comment by evanSe** [comment]
@leriel, thanks for the detailed information! 😄 In the coming days, I will investigate further and let you know if I manage to resolve any of the cloning issues. So far, StackBlitz and the custom things they are doing can be super confusing!

**Comment by leriel** [comment]
@evanSe sure, glad to help! If you want me to try things with those branches i mentioned, just ping me :)

**Pull request closed without merging**
