### PR TITLE
Added some extra shortcuts to fulfill specification (it should work the same in HOT 11.0.x)

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

I changed it [according to specification](https://docs.google.com/spreadsheets/d/1fEMjQzM0AiPa9SZh68yKvMRDcsWsfRyXsAY7y4khY0s/edit#gid=0). It's a temporary solution, not the target behaviour.

[skip changelog]

### How has this been tested?

Manual tests

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9323 
2. #9327

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jansiegel** [comment]
@wszymanski 
I don't really know what is the desired result here.

1. #9327 :
    1. The title states it's about the combination of `Shift + Page Up/Down`
    2. The description mentions the combination `Shift + Fn + Arrow Up/Down`
    3. The gifs show the usage of `Cmd + Page Up/Down`
    
    It's not clear to me which of the combinations are we fixing and what is the expected result for them?
    Generally from what I can tell:
    1. `Shift + Page Up/Down` seems to work as in `11.x` (the selection gets moved a page up/down)
    2. `Shift + Fn + Arrow Up/Down` also works the same as it does in `11.x` but I'm not sure why we're testing combinations with the `fn` key, as it's pretty obscure, and there are multiple other combinations that need fixing which are actually probable real-life scenarios.
    3. `Cmd + Page Up/Down` **doesn't** work as it does in `11.x` - in `11.x` after pressing the combination two cells get selected - the one that was selected initially and the one the selection gets moved to after pressing the combination.
    
    And if we're checking combinations with `fn`, we might as well test the `alt/option` key, in which case:
    1. `Alt + Page Up/Down` **doesn't** work as it does in `11.x` - it does nothing
    2. `Alt + Shift + Page Up/Down` also does nothing

2. #9323
    1. `Cmd + Shift + Arrow Keys` work like in `11.x`
    2. It's not specified anywhere, but `Alt + Arrow Keys` blocks the selection movement, and it didn't in `11.x`
    
    
BTW - Can we assign those issues to the `12.0.0` release, so they won't get lost?

**Comment by aninde** [comment]
> @wszymanski @aninde I don't really know what is the desired result here.
> 
> 1. [[12.0.0] Restoring operation of Shift + Page up/down #9327](https://github.com/handsontable/handsontable/issues/9327) :
>    
>    1. The title states it's about the combination of `Shift + Page Up/Down`
>    2. The description mentions the combination `Shift + Fn + Arrow Up/Down`

There is no `Page up` and `Page down` button on the built-in macbook keyboard. The `Fn + Arrow up / down` combination replaces it, hence its inclusion on the list.

>    3. The gifs show the usage of `Cmd + Page Up/Down`

You're right, I'm so sorry and I'm swapping gifs. I record the combinations `Shift + Fn + Arrow up` on them to prove my above comment. https://github.com/handsontable/handsontable/issues/9327

>    It's not clear to me which of the combinations are we fixing and what is the expected result for them?
>    Generally from what I can tell:
>    
>    1. `Shift + Page Up/Down` seems to work as in `11.x` (the selection gets moved a page up/down)
>    2. `Shift + Fn + Arrow Up/Down` also works the same as it does in `11.x` but I'm not sure why we're testing combinations with the `fn` key, as it's pretty obscure, and there are multiple other combinations that need fixing which are actually probable real-life scenarios.

For version from the original post they weren't working for me on Chrome 100.0.4896.30 as I reported.

>    3. `Cmd + Page Up/Down` **doesn't** work as it does in `11.x` - in `11.x` after pressing the combination two cells get selected - the one that was selected initially and the one the selection gets moved to after pressing the combination.
>    
>    And if we're checking combinations with `fn`, we might as well test the `alt/option` key, in which case:
>    
>    1. `Alt + Page Up/Down` **doesn't** work as it does in `11.x` - it does nothing
>    2. `Alt + Shift + Page Up/Down` also does nothing

Yes, I tested some `ALT + someting` combination, but but we agreed that they are out of scope and the issue was closed.
https://github.com/handsontable/handsontable/issues/9321
> 2. [[12.0.0] Cmd ⌘ + Shift ⇧ + Arrow keys don't work #9323](https://github.com/handsontable/handsontable/issues/9323)
>    
>    1. `Cmd + Shift + Arrow Keys` work like in `11.x`
>    2. It's not specified anywhere, but `Alt + Arrow Keys` blocks the selection movement, and it didn't in `11.x`

As above https://github.com/handsontable/handsontable/issues/9321

> BTW - Can we assign those issues to the `12.0.0` release, so they won't get lost?

Of course.

**Comment by aninde** [comment]
I built and tested it on safari 15.3 (17612.4.9.1.8) macOS 12.2.1 (21D62) and Chrome 10 99.0.4844.74 / Windows 10.

Case https://github.com/handsontable/handsontable/issues/9323  `Cmd + Shift + Arrow keys` and `Ctrl + Shift + Arrow` keys works as we established on macOS. extended the selection by 1 (one) cell only in each direction. 
Both Cmd + and Ctrl + works on macOS.

Case https://github.com/handsontable/handsontable/issues/9327 works as expected also. Moving selection page up / down was restored. 

Ctrl + Home
Ctrl + End
Shift + Page up
Shift + page down
Shift + Home
Shift + End
Cmd + Home (tested on Chrome, on Safari, this is an assigned shortcut)
Cmd + End
work on macOS and Windows the same as in v11.X

Cmd + Page up and CMD + Shift + Page down works differently, and probably it's a breaking change or a bug.  In this version, there is no action after this. 
>    3. `Cmd + Page Up/Down` **doesn't** work as it does in `11.x` - in `11.x` after pressing the combination two cells get selected - the one that was selected initially and the one the selection gets moved to after pressing the combination.

> Yes, you're correct. In practice, this shortcut allowed the user to select data by `area hightlight`, but it did not copy all the selected ones, so I wonder if it makes any practical sense.
The same goes for `Cmd / Ctrl + Shift + Page up`. It also doesn't work in v12.
We don't have these abbreviations specified, so I think they are out of scope as well, like combinations with `Alt`.

**Comment by jansiegel** [comment]
> Yes, you're correct. In practice, this shortcut allowed the user to select data by area hightlight, but it did not copy all the selected ones, so I wonder if it makes any practical sense.

The copying worked like with any other non-consecutively selected cells, so I don't think it's a reason to ditch it altogether...?

**Comment by wszymanski** [comment]
> > Yes, you're correct. In practice, this shortcut allowed the user to select data by area hightlight, but it did not copy all the selected ones, so I wonder if it makes any practical sense.
> 
> The copying worked like with any other non-consecutively selected cells, so I don't think it's a reason to ditch it altogether...?
> 
> > We don't have these abbreviations specified, so I think they are out of scope as well, like combinations with Alt.
> 
> We may not have it specified now, but I think we should. `Cmd + [shortcut for any cell selection]` should probably work similarly to `cmd + click`?

I would do it within new issue and PR.

**Pull request merged**
