### PR TITLE
Improve the docs:version script

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR improves the `rollup-a-version.js` script (`npm run docs:version`). It adds `inquirer` package to the script. The package leads the user by hand by prompting the questions when they use the script.

The validation from now on allows only passing version in `X.Y` pattern.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8247
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by Siemienik — CHANGES_REQUESTED** [review]
It works great for interactive mode 🥇 

However, it stops working as a command:
```
 npm run docs:version 9.3
```

Could you please fix it?

**Comment by budnix** [comment]
> It works great for interactive mode 🥇
> 
> However, it stops working as a command:
> 
> ```
>  npm run docs:version 9.3
> ```
> 
> Could you please fix it?

No problem 👍  Where it's used as a command?

**Comment by Siemienik** [comment]
>Where it's used as a command?

In the readme:

https://github.com/handsontable/handsontable/blob/feature/6f9765057bee2c420a50134624e54702380cc183/docs/README-EDITING.md#versioning

**Comment by budnix** [comment]
> > Where it's used as a command?
> 
> In the readme:
> 
> https://github.com/handsontable/handsontable/blob/6f9765057bee2c420a50134624e54702380cc183/docs/README-EDITING.md#versioning

Oh, I thought that you mean non-interactive aka no TTY shell (added within https://github.com/handsontable/handsontable/pull/8255/commits/6f9765057bee2c420a50134624e54702380cc183). I'd change the content of the README to use only `npm run docs:version` and then use interactive prompts to release a new version. IMO it's more secure, convenient for release master. The same is done for HoT release scripts (e.g. https://github.com/handsontable/handsontable/blob/feature/issue-7624/scripts/release.mjs#L18).

**Comment by Siemienik** [comment]
image
image

Non-interactive mode does not work for me.

Ok, let's revert it to a version with only interactive mode. Then update a readme. It should be simplest and enough convenient.

**Comment by budnix** [comment]
> Non-interactive mode does not work for me.

in TTL-less shell it should work (like GH Action, Docker - without `-t`), so it's ready for some process automatization. You can try `node .vuepress/tools/version/rollup-a-version.js 9.2 | cat`.
> Ok, let's revert it to the version with only interactive mode. Then update a readme. It should be simplest and enough convenient.

I've updated the README (99fdab7c7d036a0b09f3b91f83ce5d796e6453b4).

**Review by Siemienik — APPROVED** [review]
Thank you 🥇

**Pull request merged**
