### PR TITLE
Injection of HTML tag to the first `h1` element on a page

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

At first, I've checked a lot of `markdown-it` plugins (including checking how the most promising `markdown-it-header-sections` works), examining whether writing a loader is a good approach for doing it, checking `markdown-it` options such as `typographer`, or native `VuePress'` `markdown` key including examining options such as `extractHeaders`. 

Finally, I've chosen writing own `markdown-it plugin` [using its API](https://markdown-it.github.io/markdown-it).

[skip changelog]

### How has this been tested?

I've tested it by running scripts such as:

- `DOCS_VERSION=next DOCS_FRAMEWORK=react npm run docs:start:no-cache`,
- `DOCS_VERSION=next DOCS_FRAMEWORK=javascript npm run docs:start:no-cache`
- `npm run docs:build:no-cache` 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9515

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wszymanski** [comment]
> @wszymanski
> 
> 1. For some reason, when I run the docs using the docker script:
> 
> ```
> npm run docs:review e06d7a59556d62c8dedc91fc33bd5a26780f97a3
> ```

It's worth to check whether staged version is built without cache. I've seen the same problem while building with cache.

**Comment by jansiegel** [comment]
> > @wszymanski
> > 
> > 1. For some reason, when I run the docs using the docker script:
> > 
> > ```
> > npm run docs:review e06d7a59556d62c8dedc91fc33bd5a26780f97a3
> > ```
> 
> It's worth to check whether staged version is built without cache. I've seen the same problem while building with cache.

Makes sense. We'll need to swap the `build` command to `build:no-cache` for all the CI anyway.

**Comment by jansiegel** [comment]
> 1. For some reason, when I run the docs using the docker script:
> 
> ```
> npm run docs:review e06d7a59556d62c8dedc91fc33bd5a26780f97a3
> ```
> 
> The `<span>` value is always `JavaScript Data Grid`, regardless of the chosen docs version

Looks like [03cbde5](https://github.com/handsontable/handsontable/pull/9546/commits/03cbde50d9fed9aee812521a19f67324865dca4c) fixed it 👍

**Review by jansiegel — APPROVED** [review]

**Comment by wszymanski** [comment]
I'll wait for @warpech's [confirmation](https://github.com/handsontable/handsontable/pull/9546#pullrequestreview-997748221).

**Comment by wszymanski** [comment]
> I'll wait for @warpech's [confirmation](https://github.com/handsontable/handsontable/pull/9546#pullrequestreview-997748221).

It was confirmed on today's meeting by @warpech.

**Pull request merged**
