### PR TITLE
Fix error thrown on cell element refocus

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR fixes an error that was thrown while trying to focus on the not-rendered cell element. The PR updates the code of the `FocusManager` to wait for the viewport scroll to complete before the element is retrieved and focused. 

_[skip changelog]_ (hotfix)

### How has this been tested?

I updated the tests and added a few ones.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1593

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jansiegel** [comment]
@budnix, the error no longer gets thrown, but IME does not work when moving from the fixed bottom rows upwards, when the cells above had not been loaded. 

imefastedit1

imefastedit2

**Comment by budnix** [comment]
> @budnix, the error no longer gets thrown, but IME does not work when moving from the fixed bottom rows upwards, when the cells above had not been loaded.

I have a problem reproducing this problem 🤔 For my simplified setup, it works.
Kapture 2023-11-27 at 15 17 08

**Comment by jansiegel** [comment]
@budnix, seems like a mix of `imeFastEdit`, `fixedRowsBottom` and `fixedColumnsStart` is not working: https://jsfiddle.net/js_ziggle/gwyebk63/

**Comment by AMBudnik** [comment]
@jansiegel I found a similar thing here `imeFastEdit`, `fixedRowsBottom`, and the lack of scroll to the last non-frozen cell with `CMD + END` https://jsfiddle.net/9gpodwrh/1/ (in the latest build from 27.11). It doesn't work on Chrome on macOS but works well on Windows. Should it be reported separately in a new issue?

**Comment by budnix** [comment]
> @jansiegel I found a similar thing here `imeFastEdit`, `fixedRowsBottom`, and the lack of scroll to the last non-frozen cell with `CMD + END` https://jsfiddle.net/9gpodwrh/1/ (in the latest build from 27.11). It doesn't work on Chrome on macOS but works well on Windows. Should it be reported separately in a new issue?

I think I found [a fix](https://github.com/handsontable/handsontable/pull/10611/commits/4648bb390b71d14f86766f351448b0b3eaac4a42). On my side, it was reproducible only when I throttled the CPU by four times or more.

**Comment by budnix** [comment]
> @budnix, seems like a mix of `imeFastEdit`, `fixedRowsBottom` and `fixedColumnsStart` is not working: https://jsfiddle.net/js_ziggle/gwyebk63/

I think I found [a fix](https://github.com/handsontable/handsontable/pull/10611/commits/4648bb390b71d14f86766f351448b0b3eaac4a42). On my side, it was reproducible only when I throttled the CPU by four times or more.

**Review by jansiegel — APPROVED** [review]
Looks fine now 👍

**Pull request merged**
