### PR TITLE
Fixed an issue where redundant row has been added during copy/paste operations in some case

### PR DESCRIPTION
**Pull request by wszymanski**
### Context
We try to act like Google Spreadsheet for the case described in the issue. However, there was a bug. I've totally rewritten the logic of `populateValues` method. So far, it has been assuming in advance whether selection or populated data is bigger (we try just populate data or repeat it within a selection.

I removed this part of the code as it's impossible to assume the above relationship before checking whether some cells have `skipRowOnPaste`/`skipColumnOnPaste` option defined as `true`.

### How has this been tested?
CopyPaste plugin enabled and option `copyPasteEnabled` set for `HiddenRows` and `HiddenColumns` plugins. Tested also with `maxRows` and `maxCols` option to check whether introduced `while` isn't problematic.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #5961
2. #6743

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wszymanski** [comment]
I will think about adding a new test as it seems that #6743 will be fixed by doing refactor 💪

**Comment by wszymanski** [comment]
Some tests may not pass. It's a problem with the current `develop` branch which has been merged.

**Review by swistach — APPROVED** [review]
Seems to work as expected 👍

Do we need actually the same test scenarios in each plugin?

**Comment by wszymanski** [comment]
> Seems to work as expected 👍
> 
> Do we need actually the same test scenarios in each plugin?

I'm afraid that yes. The question is absolutely justified as actually they work almost the same -just on the other axis. Although, I think that their end to end work should be protected.

**Pull request merged**
