### PR TITLE
Improve typescript in react demo

### PR DESCRIPTION
**Pull request by adrianspdev**
### Context
This PR contains typescript improvement for react demo v14.1.0

### How has this been tested?
manul tests

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/dev-handsontable/issues/1454

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [x] Update RendererProps type, and remove ts @ts-ignore
- [x] Replace custom types with types from handsontable

[skip changelog]

### CODE REVIEW

**Review by evanSe — APPROVED** [review]

**Review by jansiegel — CHANGES_REQUESTED** [review]
Looks good to me 👍 

Could you copy these changes to the `/next/` examples, so they are kept with the next versions?

**Comment by evanSe** [comment]
@adrianspdev we might wait merging this until https://github.com/handsontable/handsontable/pull/10768 is merged.

**Comment by jansiegel** [comment]
@adrianspdev Could I ask you to resolve the conflicts with the current `develop`? (Basically, `examples/14.1.0` don't exist anymore, so you can scrap the changes to those files).

**Comment by evanSe** [comment]
@adrianspdev I would rebase off develop and only include commits you did

**Review by evanSe — APPROVED** [review]

**Review by jansiegel — APPROVED** [review]

**Pull request merged**
