### PR TITLE
Improve navigation and accessibility of Column menu with filtering

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR improves the navigation and accessibility of the Dropdown menu (also known as the Column menu) with filtering. Most of the effort has been put into improving the navigation of filter components. From now on, it is possible to navigate through them using the <kbd>Tab</kbd> and <kbd>Shift+Tab</kbd> shortcuts.

I consider the PR as a breaking change as many default behaviors of the menus and filter components are changed.

#### General Overview
Kapture 2023-10-20 at 12 41 09

#### Switching between different navigation modes
Once the user goes into the "focus" mode (i.e., by pressing <kbd>Tab</kbd> or clicking in the focusable component), it's impossible to select another regular menu item using the arrow keys until the whole menu is focused again. For example:

Kapture 2023-10-20 at 12 45 14

#### Escaping the menu
No matter what item is selected (regular or focusable one), the <kbd>Escape</kbd> key always closes the menu.

Kapture 2023-10-20 at 12 48 41

#### Changing the component's values
The <kbd>Enter</kbd> and <kbd>Space</kbd> keys trigger the "by condition" menus. The same keys are used to accept the condition.

Kapture 2023-10-20 at 12 51 43

The <kbd>ArrowDown</kbd> key when Search input is focused can be used to switch the focus to the listbox component.

Kapture 2023-10-20 at 13 02 08

Once the listbox component is focused, there is a possibility to check or uncheck using <kbd>Enter</kbd> or <kbd>Space</kbd> the specified items. The <kbd>Tab</kbd> or <kbd>Tab</kbd>+<kbd>Shift</kbd> can be used to switch the focus to the next or previous element.

### How has this been tested?

I tested the changes locally, I covered the fixes with new E2E and visual tests.

### Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1464
2. fixes https://github.com/handsontable/dev-handsontable/issues/1484 (also for Dropdown menu)

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Review by jansiegel — CHANGES_REQUESTED** [review]
Looks good, but I have two notes:
1. The fact that the part with the checkboxes (the list of the values) is accessible only when the user is focused on the search input wouldn't be clear to me, but I'm not sure if it's how it's supposed to be? (that's not the point that requires any changes)
2. I think the option to open the filtering menu using the `ctrl/cmd + enter` stopped working. Or am I doing something wrong?

**Comment by budnix** [comment]
> * The fact that the part with the checkboxes (the list of the values) is accessible only when the user is focused on the search input wouldn't be clear to me, but I'm not sure if it's how it's supposed to be? (that's not the point that requires any changes)

It's by design

> * I think the option to open the filtering menu using the `ctrl/cmd + enter` stopped working. Or am I doing something wrong?

I synced the latest changes with `feature/accessibility` and the keyboard shortcut started working.

**Review by jansiegel — APPROVED** [review]
👍

**Comment by AMBudnik** [comment]
Works as a charm even with other elements on the page. Demo for v14.0.0 https://jsfiddle.net/qsedcahb/14/

Zrzut ekranu 2023-12-1 o 12 06 28

**Pull request merged**
