### PR TITLE
Fixed bug where number of columns rendered in the viewport wasn't proper

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

We had typo in `viewportColumnCalculatorOverride` function which is responsible for calculating number of displayed columns. After change, start point for rendering typically starts earlier. Thus, number of rendered columns has been increased.

I went though all test and checked whether everything looks good. I adapted them to the new behavior. I did also change in tests for scrolling to make them independent of number of cells rendered in the viewport.

### How has this been tested?

Tested some use cases related to scrolling table horizontally (also with `CollapsibleColumns` plugin enabled). I checked performance using the `performance-lab`. It seems that most of the tests related to movement in viewport has similar performance. Just some tests shows bigger differences.

Much more faster:

Screenshot 2021-03-11 at 13 20 08
Screenshot 2021-03-11 at 13 22 01

A little bit slower:

Screenshot 2021-03-11 at 13 17 16
Screenshot 2021-03-11 at 13 22 21

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6115

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by budnix — COMMENTED** [review]
I've checked the code and I have nothing to add 🥇  

However, I've checked the performance and it seems that in some cases it can be worse than before. Mostly when something happens in the middle or on the last rows/cols the table feels more laggy (because now the number of rendered columns increases with distance from coords `0, 0`?). 

For example:
Navigating with the arrow down key from the middle of the table
image
(~18% worse)

Navigating with the arrow up key from the bottom of the table
image
(~22% worse)

The same happens for navigating on another axis. 

On the other hand, there are some cases where for sure the performance is better:
For example, for navigating the arrow left key from the most bottom-right table's cell (which is an exception)
image
drastically reduces the delay in the table rendering.
(~500% better)

Another example is editing the cell. For the cells edited in the area nearest the `0, 0` coords the performance is better for about 30-40%. But for cells edited in the middle, the situation goes worse. There is about  ~15% and for the last cells ~25% worse performance.

For other tests such as scrolling, using Page Up/Down keys I didn't notice significant changes.

Maybe within this task, we should revise the `'auto'` option of the `viewportColumnRenderingOffset` setting? WDYT?

cc @wojciechczerniak

**Comment by wszymanski** [comment]
> For other tests such as scrolling, using Page Up/Down keys I didn't notice significant changes.
> 
> Maybe within this task, we should revise the `'auto'` option of the `viewportColumnRenderingOffset` setting? WDYT?

Thanks for insightful check. You came to almost the same conclusions (probably phrase: `A little bit slower` used above wasn't the best) 🙂 In some use cases a table is much faster, in some it is slower.

Maybe some revision is needed as providing solution which isn't better for all cases doesn't sound good. However, it definitely extends scope of the task. Should we put it on hold (as it may not have the biggest priority - we focus on regressions), release it or do something more, @wojciechczerniak ?

**Comment by wojciechczerniak** [comment]
> Maybe within this task, we should revise the `'auto'` option of the `viewportColumnRenderingOffset` setting? WDYT?

What do you have in mind @budnix?

@wszymanski I didn't had a scope for this task. It was up for an investigation what we need to do to fix this. If the road to merging this leads us through `viewportColumnRenderingOffset` then we should follow.

As for the priority, I will have to ask you both @wszymanski @budnix. I have a feeling that using wrong calculator in `tableView.js` may force us to chase our own tail when fixing other issues. We're building other features and bug fixes on the wrong assumptions and results. Therefore, creating bugs all over the other places. But I'm not sure how serious this may be.

**Comment by budnix** [comment]
> > Maybe within this task, we should revise the `'auto'` option of the `viewportColumnRenderingOffset` setting? WDYT?
> 
> What do you have in mind @budnix?
> 

Under the `'auto'` option there is implemented a simple algorithm that tells the Walkontable how many columns it has to generate. The farther from the `0, 0` coordinates the viewport is the more columns the Walkontable generates. It's linear. It was developed some time ago. I believe that this can be tweeted (maybe as a non-linear algorithm) so both areas of the table viewport could perform well.

**Comment by wszymanski** [comment]
> @wszymanski I didn't had a scope for this task. It was up for an investigation what we need to do to fix this. If the road to merging this leads us through `viewportColumnRenderingOffset` then we should follow.

The task is about removing typo and this bug was fixed. However. the change shows that performance results are unexpected. The offsets was introduced probably for performance reasons and change shows that option 'auto' for the `viewportColumnRenderingOffset` (and probably the same for `viewportRowRenderingOffset`) even though this mechanism hasn't been touched.

**Comment by wojciechczerniak** [comment]
Ok, I think I see it now. You've changed tests where Handsontable is `width: 200` and `height: 200`. Without the change in HoT dimensions, we expect to have more columns in the DOM. Should be roughly the same? This will also put more work after closing cell editor as @budnix pointed out.

I think reviewing calculator should be a part of this PR, and since we now have time to  close as many PRs as possible, we should finish this as well 🎉 

---

My type on the offset here:
https://github.com/handsontable/handsontable/blob/73cdfc829c68d1e3ac38a9aadf1f400d83329c9f/src/tableView.js#L880
IMO `12` is way to big offset modifier for columns. Consider this: if `12` is fine for rows where average row height is 24px, then (with base eq `1`) total offset is 12x24=288px, but for average column width of 100px it will be 1200px (if average column is 150px we have 1800px 😮 ). I think that this value should be proportional to the average size. We should target scroll pixel offset, not the number of elements. If we target for, lets say, ~300px of scroll "backup" then for columns the modifier would be only `3`, top. We may reduce it to half from 12 and check the performance, then try lower values.

If the above is correct then when we have fixedColumns:
https://github.com/handsontable/handsontable/blob/73cdfc829c68d1e3ac38a9aadf1f400d83329c9f/src/tableView.js#L867-L869
setting arbitrary `10` for offset also creates 1000px of offset. Should be adjusted as well.

---

I'm not sure the `center` logic is correct: https://github.com/handsontable/handsontable/blob/73cdfc829c68d1e3ac38a9aadf1f400d83329c9f/src/tableView.js#L879
This can be reduced to `const center = calc.endColumn`. I would say it's not the center 😉  Apart from unnecessary op, we may actually try fixing it and see the performance.

**Comment by wszymanski** [comment]
> Ok, I think I see it now. You've changed tests where Handsontable is `width: 200` and `height: 200`. Without the change in HoT dimensions, we expect to have more columns in the DOM. Should be roughly the same?

There were wrong start point, that's why less columns have been rendered. Some offset columns haven't been rendered to the left of the first visible column. We expect more columns to be placed before first rendered column 🙂

> I think reviewing calculator should be a part of this PR, and since we now have time to close as many PRs as possible, we should finish this as well 🎉
> 
> My type on the offset here:
> https://github.com/handsontable/handsontable/blob/73cdfc829c68d1e3ac38a9aadf1f400d83329c9f/src/tableView.js#L880
> 
> 
> IMO `12` is way to big offset modifier for columns. Consider this: if `12` is fine for rows where average row height is 24px, then (with base eq `1`) total offset is 12x24=288px, but for average column width of 100px it will be 1200px (if average column is 150px we have 1800px 😮 ). I think that this value should be proportional to the average size. We should target scroll pixel offset, not the number of elements. If we target for, lets say, ~300px of scroll "backup" then for columns the modifier would be only `3`, top. We may reduce it to half from 12 and check the performance, then try lower values.

Nice investigation. Default column width is equal to `50px`. So, There should be 2 times less columns than rows (according to default row height set to `24px`) for offset (when we would keep current logic). I've tried how it works for that constant `6` (commit https://github.com/handsontable/handsontable/pull/7625/commits/3150679728647a0091bd6d62de5402330909a3e0) and we can see definitely better performance results for most cases.

`arrow-left.most-bottom-right`

Screenshot 2021-03-25 at 13 12 58

`arrow-down.middle`

Screenshot 2021-03-25 at 13 44 57

`arrow-up.most-bottom-right`

Screenshot 2021-03-25 at 13 46 19

`editing-cell.most-top-left`

Screenshot 2021-03-25 at 13 39 15

`editing-cell.bottom-right`

Screenshot 2021-03-25 at 13 40 59

`editing-cell.middle`

Screenshot 2021-03-25 at 13 43 02

However, as you said, approach for calculating offset could be changed. I will experiment with it.

**Comment by wszymanski** [comment]
It seems that tests should be changed for maximum of `6` offset columns, also starting from the start of the table. Within the PR, there was fixed problem of typo in calculator and boosted calculator for columns to deliver similar performance, comparing to the `develop`. [Another issue](https://github.com/handsontable/handsontable/issues/7674) is prepared for more performance improvements.

**Pull request merged**
