### PR TITLE
Add Missing Import

### PR DESCRIPTION
**Pull request by mohithg**
### Context

The missing import for isObjectEquals is fixed here

### How has this been tested?

Error is thrown when table is sorted on clicking on table column

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1.
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by mohithg** [comment]
@budnix Here is the fix for https://github.com/handsontable/handsontable/issues/4367. Let me know if I need to add tests

**Comment by AMBudnik** [comment]
Hi @mohithg 

thanks for spotting this. 

Please sign the [CLA document](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1) and switch the branch to `develop` to allow us to merge the pull request.

Thanks in advance!

**Comment by mohithg** [comment]
Hi @AMBudnik 
Signed the CLA Document and changed the branch to develop.
Thanks!

**Comment by AMBudnik** [comment]
Great! Thank you

**Comment by budnix** [comment]
Thanks, @mohithg!

**Pull request merged**
