### PR TITLE
If there are no table rows, don't try and grab the HTML elements for them

### PR DESCRIPTION
**Pull request by TRManderson**
If a table hasn't been rendered yet and thus has no child elements (or its DOM element has somehow been disposed of), the console fills up with logs about `rowFilter` being null.

This should preserve existing behaviour (if `this.TBODY.childNodes` has no elements, there will never be a result) but also prevent errors in the situation described above.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @TRManderson 

please remember to add some tests.

**Comment by TRManderson** [comment]
Just left the office for the day, I'll see if I can come up stuff some tomorrow :)

**Comment by AMBudnik** [comment]
Great, thanks.

**Comment by AMBudnik** [comment]
Hi @TRManderson 

I am not able to add the `ready for review` label for PRs without tests. Can you add it, please?

**Comment by AMBudnik** [comment]
I need to close this PR as there is no reply for more than 2 weeks. Feel free to leave a comment if you are still interested in this PR.

**Comment by TRManderson** [comment]
While I understand why you closed the issue, it poses a slightly philosophical question: Is it better to close a PR with a fix but no tests than it is to keep broken code in your library?

All this PR does is prevents an issue by returning with a failure code right before an error occurs, which is a fairly obvious change. This is apparently [causing issues on your own website](https://github.com/handsontable/handsontable.com-v1/issues/4)?

Just be aware that by closing PRs without tests you're choosing to retain code that is known to be broken. The situation with [one of my other PRs](https://github.com/handsontable/handsontable/pull/4423) is similar. I'm not going to comment further.

**Comment by AMBudnik** [comment]
I can understand that this can be confusing but we are learning from the past. Some time ago we have decided that we can't accept pull requests without tests and we hardly keep trying to have all our code covered. 

In the past when we checked pull requests without tests it made us do the double work. We had to add tests by our own and in most cases, it ended up with a situation that the pull requests have been changed more than expected. 

What I haven't written before is the fact that when we fix issues that are reported on Github we check all linked resources, even the closed pull requests so your work may help us. It just won't be pulled as a commit.

**Pull request closed without merging**
