### PR TITLE
Jsdoc-convert - dynamic type list

### PR DESCRIPTION
**Pull request by Siemienik**
### Context
Blocked by: #8590 
Blocks: #8609 

In this PR I remove the whitelist of files. Instead of that. The `jsdoc-convert` tool parses the whole `src` dir, groups by `memberof` property, and finally render each type separately to `.md` file.

This PR also split two liabilities (I mean parsing jsdoc and rendering markdown) into separate steps, which allows getting all types at once, and then rendering markdown. That makes It has knowledge about each parsed type during markdown generation, and it proper links between types.

<details>
Draft todos:
* [X] PR description
* [x] resolves //todo (#8609)
* [x] extract parse (#8609)
* [x] extract render (#8609)
</details>

[skip changelog]

### How has this been tested?
Generated API references and compare with `/9.0/api/`
Run a broken link checker

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. #8335 
2.
3.

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Review by budnix — CHANGES_REQUESTED** [review]
I try to generate a new API `npm run docs:api` but I've got an error:
image

**Comment by Siemienik** [comment]
Could you provide me a little more information, I haven't got any errors.

1. What OS do you use?
2. All dependencies were installed?


<details>
<summary> The correct output </summary>

```bash
> handsontable-documentation@0.0.0 docs:api
> node .vuepress/tools/jsdoc-convert/index.mjs

Parsing jsdoc comments...
Jsdoc comments parsed successfully.
Parsed 185 API Refs pages.
Generating `Border` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/border.md
Generating `ViewportColumnsCalculator` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/viewportColumnsCalculator.md
Generating `ViewportRowsCalculator` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/viewportRowsCalculator.md
Generating `Walkontable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/walkontable.md
Generating `Event` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/event.md
Generating `ColumnFilter` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnFilter.md
Generating `RowFilter` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/rowFilter.md
Generating `BottomOverlay` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/bottomOverlay.md
Generating `BottomLeftCornerOverlay` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/bottomLeftCornerOverlay.md
Generating `LeftOverlay` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/leftOverlay.md
Generating `TopOverlay` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/topOverlay.md
Generating `TopLeftCornerOverlay` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/topLeftCornerOverlay.md
Generating `Overlays` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/overlays.md
Generating `CellsRenderer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/cellsRenderer.md
Generating `ColGroupRenderer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/colGroupRenderer.md
Generating `ColumnHeadersRenderer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnHeadersRenderer.md
Generating `Renderer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/renderer.md
Generating `RowsRenderer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/rowsRenderer.md
Generating `Scroll` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/scroll.md
Generating `Selection` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/selection.md
Generating `Settings` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/settings.md
Generating `Table` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/table.md
Generating `ColumnUtils` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnUtils.md
Generating `NodesPool` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/nodesPool.md
Generating `SharedOrderView` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/sharedOrderView.md
Generating `OrderView` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/orderView.md
Generating `ViewSize` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/viewSize.md
Generating `ViewSizeSet` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/viewSizeSet.md
Generating `RowUtils` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/rowUtils.md
Generating `Viewport` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/viewport.md
Generating `Core` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/core.md
Generating `DataMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataMap.md
Generating `Options` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/options.md
Generating `EditorManager` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/editorManager.md
Generating `BaseEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/baseEditor.md
Generating `DateEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dateEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dateEditor.md
Generating `TextEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/textEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/textEditor.md
Generating `EventManager` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/eventManager.md
Generating `AutoColumnSize` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/autoColumnSize.md
Generating `Autofill` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/autofill.md
Generating `AutoRowSize` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/autoRowSize.md
Generating `BasePlugin` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/basePlugin.md
Generating `BindRowsWithHeaders` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/bindRowsWithHeaders.md
Generating `CollapsibleColumns` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/collapsibleColumns.md
Generating `ColumnSorting` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnSorting.md
Generating `ColumnStatesManager` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnStatesManager.md
Generating `ColumnSummary` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnSummary.md
Generating `Endpoints` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/endpoints.md
Generating `CommentEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/commentEditor.md
Generating `Comments` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/comments.md
Generating `DisplaySwitch` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/displaySwitch.md
Generating `CommandExecutor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/commandExecutor.md
Generating `ContextMenu` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/contextMenu.md
Generating `Cursor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/cursor.md
Generating `ItemsFactory` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/itemsFactory.md
Generating `CopyPaste` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/copyPaste.md
Generating `CustomBorders` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/customBorders.md
Generating `DragToScroll` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dragToScroll.md
Generating `DropdownMenu` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dropdownMenu.md
Generating `ExportFile` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/exportFile.md
Generating `ConditionUpdateObserver` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/conditionUpdateObserver.md
Generating `Filters` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/filters.md
Generating `Formulas` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/formulas.md
Generating `HiddenColumns` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/hiddenColumns.md
Generating `HiddenRows` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/hiddenRows.md
Generating `ManualColumnFreeze` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/manualColumnFreeze.md
Generating `ManualColumnMove` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/manualColumnMove.md
Generating `ManualColumnResize` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/manualColumnResize.md
Generating `ManualRowMove` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/manualRowMove.md
Generating `ManualRowResize` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/manualRowResize.md
Generating `AutofillCalculations` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/autofillCalculations.md
Generating `SelectionCalculations` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/selectionCalculations.md
Generating `MergedCellCoords` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/mergedCellCoords.md
Generating `MergedCellsCollection` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/mergedCellsCollection.md
Generating `MergeCells` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/mergeCells.md
Generating `MultiColumnSorting` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/multiColumnSorting.md
Generating `MultipleSelectionHandles` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/multipleSelectionHandles.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/multipleSelectionHandles.md
Generating `NestedHeaders` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/nestedHeaders.md
Generating `StateManager` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/stateManager.md
Generating `SourceSettings` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/sourceSettings.md
Generating `NestedRows` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/nestedRows.md
Generating `ContextMenuUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/contextMenuUI.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/contextMenuUI.md
Generating `HeadersUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/headersUI.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/headersUI.md
Generating `RowMoveController` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/rowMoveController.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/rowMoveController.md
Generating `PersistentState` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/persistentState.md
Generating `Search` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/search.md
Generating `TrimRows` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/trimRows.md
Generating `UndoRedo` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/undoRedo.md
Generating `Highlight` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/highlight.md
Generating `SelectionRange` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/selectionRange.md
Generating `Transformation` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/transformation.md
Generating `TableView` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/tableView.md
Generating `ChangesObservable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/changesObservable.md
Generating `ChangesObserver` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/changesObserver.md
Generating `IndexMapper` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/indexMapper.md
Generating `NodeStructure` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/nodeStructure.md
Generating `LinkedList` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/linkedList.md
Generating `CellCoords` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/cellCoords.md
Generating `CellRange` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/cellRange.md
Generating `BottomOverlayTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/bottomOverlayTable.md
Generating `BottomLeftCornerOverlayTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/bottomLeftCornerOverlayTable.md
Generating `LeftOverlayTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/leftOverlayTable.md
Generating `MasterTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/masterTable.md
Generating `TopOverlayTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/topOverlayTable.md
Generating `TopLeftCornerOverlayTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/topLeftCornerOverlayTable.md
Generating `DataSource` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataSource.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataSource.md
Generating `AutocompleteEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/autocompleteEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/autocompleteEditor.md
Generating `CheckboxEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/checkboxEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/checkboxEditor.md
Generating `DropdownEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dropdownEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dropdownEditor.md
Generating `HandsontableEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/handsontableEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/handsontableEditor.md
Generating `NumericEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/numericEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/numericEditor.md
Generating `PasswordEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/passwordEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/passwordEditor.md
Generating `SelectEditor` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/selectEditor.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/selectEditor.md
Generating `Hooks` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/hooks.md
Generating `LooseBindsMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/looseBindsMap.md
Generating `StrictBindsMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/strictBindsMap.md
Generating `Menu` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/menu.md
Generating `FocusableWrapper` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/focusableWrapper.md
Generating `DataProvider` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataProvider.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataProvider.md
Generating `Csv` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/csv.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/csv.md
Generating `ActionBarComponent` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/actionBarComponent.md
Generating `ConditionComponent` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/conditionComponent.md
Generating `OperatorsComponent` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/operatorsComponent.md
Generating `ValueComponent` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/valueComponent.md
Generating `ConditionCollection` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/conditionCollection.md
Generating `DataFilter` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataFilter.md
Generating `InputUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/inputUI.md
Generating `LinkUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/linkUI.md
Generating `MultipleSelectUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/multipleSelectUI.md
Generating `RadioInputUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/radioInputUI.md
Generating `SelectUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/selectUI.md
Generating `BacklightUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/backlightUI.md
Generating `GuidelineUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/guidelineUI.md
Generating `DataManager` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataManager.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/dataManager.md
Generating `CollapsingUI` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/collapsingUI.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/collapsingUI.md
Generating `Storage` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/storage.md
Generating `TouchScroll` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/touchScroll.md
Empty output detected, file omitted: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/touchScroll.md
Generating `MergeCellsAction` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/mergeCellsAction.md
Generating `UnmergeCellsAction` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/unmergeCellsAction.md
Generating `AggregatedCollection` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/aggregatedCollection.md
Generating `MapCollection` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/mapCollection.md
Generating `HidingMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/hidingMap.md
Generating `IndexesSequence` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/indexesSequence.md
Generating `IndexMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/indexMap.md
Generating `LinkedPhysicalIndexToValueMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/linkedPhysicalIndexToValueMap.md
Generating `PhysicalIndexToValueMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/physicalIndexToValueMap.md
Generating `TrimmingMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/trimmingMap.md
Generating `Queue` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/queue.md
Generating `Stack` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/stack.md
Generating `GhostTable` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/ghostTable.md
Generating `Interval` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/interval.md
Generating `SamplesGenerator` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/samplesGenerator.md
Generating `global` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/global.md
Generating `TreeNode` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/treeNode.md
Generating `module.exports` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/module.exports.md
Generating `Handsontable.Core` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/handsontable.Core.md
Generating `VisualSelection` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/visualSelection.md
Generating `exports` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/exports.md
Generating `hooksRefRegisterer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/hooksRefRegisterer.md
Generating `localHooks` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/localHooks.md
Generating `anonymous-nodeData` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/anonymous-nodeData.md
Generating `calculatedColumns` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/calculatedColumns.md
Generating `calculatedRows` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/calculatedRows.md
Generating `stickyColumnsLeft` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/stickyColumnsLeft.md
Generating `stickyRowsBottom` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/stickyRowsBottom.md
Generating `stickyRowsTop` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/stickyRowsTop.md
Generating `Core-grid` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/core-grid.md
Generating `Symbol` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/symbol.md
Generating `module` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/module.md
Generating `JasmineBridgeReporter` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/jasmineBridgeReporter.md
Generating `anonymous` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/anonymous.md
Generating `validateCell` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/validateCell.md
Generating `columnFactory` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/columnFactory.md
Generating `throttle` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/throttle.md
Generating `throttleAfterHits` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/throttleAfterHits.md
Generating `debounce` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/debounce.md
Generating `curry` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/curry.md
Generating `curryRight` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/curryRight.md
Generating `randomString` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/randomString.md
Generating `checkboxRenderer` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/checkboxRenderer.md
Generating `createPriorityMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/createPriorityMap.md
Generating `breadthFirst` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/breadthFirst.md
Generating `createUniqueMap` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/createUniqueMap.md
Generating `createUniqueSet` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/createUniqueSet.md
Generating `staticRegister` into: /Users/siemienik/WebstormProjects/handsontable/docs/next/api/staticRegister.md
OK!
```
</details>

**Comment by budnix** [comment]
> Could you provide me a little more information, I haven't got any errors.
> 
> 1. What OS do you use?
> 2. All dependencies were installed?

Sure! macOS (latest), Node 16.6.1, npm 7.20.3.
I tried with dependencies installed by `npm i` command and `npm ci` as well. In both cases, I have the same error. I tried with the latest changes on this branch,

**Comment by Siemienik** [comment]
It is quite strange for me, I cannot reproduce it. Could you try to remove node_modules and install dependencies once again?
I'm seriously curious what happens

**Review by budnix — APPROVED** [review]
> It is quite strange for me, I cannot reproduce it. Could you try to remove node_modules and install dependencies once again?
> I'm seriously curious what happens

I've checked on the clean environment (Debian image) and it worked. I assume that the problem is with my PC.

**Comment by Siemienik** [comment]
@budnix Thank you for the investigation 👍 And confirming that it works 😄

**Pull request merged**
