### PR TITLE
Extend the Github Actions workflow for deploying examples to `gh-pages`.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR extends the idea from @Osky772's [initial PR](https://github.com/handsontable/handsontable/pull/7661).

After these changes, the script should:
1. React to `push`es to `develop`, if the modified files include changes to `./examples/`
2. React to manual dispatching (with one input - the handsontable/wrappers version)
3. Build the needed packages and pass them as artifacts, if the requested version was `next`
4. Deploy the examples to `gh-pages` with a structure resembling the one used in `examples`:
      ```
      ├─[version]/
      │  ├─ docs/
      │  │  ├─ [framework]/
      │  │  │  ├─ [example name]/
      ```
      ~This structure is stored **at the root**, not in the `examples` directory - I'm not sure what is the desired structure here, @warpech?~ Edit: modified to structure to be placed inside an `examples` subdirectory instead of the root.

Most of the workflow is the logic behind the building and juggling the built artifacts for the `next` scenario, the actual deployment logic is pretty straightforward.

~For this workflow, I'm caching and uploading/downloading the `node_modules` directories as artifacts. It looks like the caching available in the `actions/setup-node` action doesn't do much here (unlike the testing workflow, where it's noticeable, that the dependency installation time is largely reduced after the initial `install` call). It looks like it saves up to 3 minutes of the overall workflow time.~
After some discussions with @budnix, we've decided to go with `actions/cache` to cache `node_modules` instead of the artifact approach.

Also, I removed the testing part from the original PR, as I think it would make the deployment take way too much time + this should be a part of the testing workflow.

**IMPORTANT:** Currently the `gh-pages` branch contains a `.gitignore` file that prevents the examples from being deployed - that needs to be changed for this PR to work properly.

### How has this been tested?
Tested multiple scenarios on a forked repository.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7661 
2. #9058 

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by budnix — CHANGES_REQUESTED** [review]
I try to run the workflow manually on my forked version of hot and I've got `Missing script: "link-packages"` errors. Is this normal? 

I typed the `11.0.0` version in the form. Here is the [run](https://github.com/budnix/handsontable/runs/4615977562?check_suite_focus=true).

**Comment by jansiegel** [comment]
> I try to run the workflow manually on my forked version of hot and I've got `Missing script: "link-packages"` errors. Is this normal?
> 
> I typed the `11.0.0` version in the form. Here is the [run](https://github.com/budnix/handsontable/runs/4615977562?check_suite_focus=true).

There was a script missing indeed, corrected in https://github.com/handsontable/handsontable/pull/9057/commits/33047b29398430bc1958b329ed732e803ec6c553.

**Review by budnix — APPROVED** [review]
I've tested the changes on my fork and it seems to work. Thanks 👍

**Comment by jansiegel** [comment]
@budnix Thx!
@warpech I'm gonna need your input on the `gh-pages` examples structure before merging.

**Comment by warpech** [comment]
I discussed with @jansiegel on Slack, that I confirm this as a desired path structure: `https://handsontable.github.io/handsontable/examples/11.0.1/docs/vue/basic-example/`

**Pull request merged**
