### PR TITLE
fix: fix ChangeSource Type Error with ContextMenu

### LINKED ISSUE #10261: ChangeSource Type Error :  ContextMenu.clearColumns ->  ContextMenu.clearColumn
### Description

the type defination is not match document.

Here is the code:
https://github.com/handsontable/handsontable/blob/648dcfa03a4c64bf5a86c84ac39775477bd53301/handsontable/types/common.d.ts#L54

Here is the document:

https://handsontable.com/docs/react-data-grid/events-and-hooks/#definition-for-source-argument

### Demo

image

### Your environment
* Handsontable version: 12.3.1

### PR DESCRIPTION
**Pull request by arvinxx**
### Context

Fix types Error
close #10261 #9566

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #10261 
2. #9566
3.

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by arvinxx** [comment]
@AMBudnik  hi, i'm done.

**Comment by AMBudnik** [comment]
Thank you. 

We are already closed with the next release (v13.0.0) issue list, but I will set the code review for another will. I will keep you updated.

**Review by budnix — APPROVED** [review]
Looks good 👍 Thanks!

**Comment by budnix** [comment]
One more thing @arvinxx. Can I ask you to add a changelog file to the PR? It can be easily generated by executing the `npm run changelog entry` command in the monorepo root directory.

**Comment by arvinxx** [comment]
@budnix I have update with the changelog

**Comment by AMBudnik** [comment]
changed merged and released in Handsontable v13.1.0

**Pull request merged**
