### PR TITLE
Add handsontable manager into build proccess

### PR DESCRIPTION
**Pull request by Siemienik**
This RP is part of #7624 (#7626)

I add handsontable-manager into the build process. Additionally, I performed refactoring here to split code into files, keep dependency flow one-directional and remove duplicates.

### CODE REVIEW

**Comment by Osky772** [comment]
```
```

**Comment by Osky772** [comment]
In `docs/README.md` there is a sentence:
```
examples.js             # Handle live code preview and jsfiddle button
```

but there is no `examples.js` file

**Review by Osky772 — APPROVED** [review]
It's working great! 👍

**Comment by Siemienik** [comment]
> but there is no `examples.js` file

Updated in: c611b0c

thanks!

**Pull request merged**
