### PR TITLE
Annotate Events functions types with this: Core as they are always bound

### PR DESCRIPTION
**Pull request by NOtherDev**
### Context

The TypeScript types exposed by Handsontable does not specify the type of `this` pointer for the Events methods, while they are always called by `runHooks` method of `Core` and they are always bound to `Core` instance. Lack of this type annotation leads to implicit `any` typing that is forbidden in TypeScript strict mode.

Current state:
image

State after the proposed change:
image

### How has this been tested?

N/A - just a typing change

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #10813 - WIP for TypeScript enhancements in React wrapper as discussed [in RFC](https://github.com/handsontable/handsontable/discussions/10767)

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by evanSe — APPROVED** [review]

**Review by evanSe — CHANGES_REQUESTED** [review]
This is a really annoying one I think we might want to completely avoid, not all plugin hooks are called with `Core` as context and it is going to be a real pain to determine the context so I am fine if we need to break some typescript rules when writing our tests.

I would close the pr and make the necessary modifications on other pr if needed.

**Comment by NOtherDev** [comment]
OK got it @evanSe. I'm fine closing it. We can always override at the caller side with:

```
init={function (this: Core) {
  mockElementDimensions(this.rootElement, 300, 300);
}}
```

Although note that this happens not only in the test code, but it will happen in any TS-enabled client codebase that provides the hooks via settings.

**Review by evanSe — APPROVED** [review]
Actually, it is all correct 😄

**Comment by evanSe** [comment]
I will merge shortly

**Comment by evanSe** [comment]
Closing and opening as a new pr as rebasing was not easy from a remote repo https://github.com/handsontable/handsontable/pull/11039

**Pull request closed without merging**
