### PR TITLE
Docs: fixing links

### PR DESCRIPTION
**Pull request by kirszenbaum**
This PR:
- Fixes links mentioned in #8783

[skip changelog]

### CODE REVIEW

**Comment by kirszenbaum** [comment]
@Siemienik - I fixed all the links mentioned in #8783 (thanks for the list), except those two:

- @/api/collapsingUI.md
- @/api/dataManager.md

I think they're both automatically generated from [here](https://github.com/handsontable/handsontable/blob/master/src/plugins/nestedRows/utils/rowMoveController.js#L13-L39)), and I'm not sure what's wrong there, can you take a look? Thanks!

**Comment by budnix** [comment]
> @Siemienik - I fixed all the links mentioned in #8783 (thanks for the list), except those two:
> 
> * `@/api/collapsingUI.md`
> * `@/api/dataManager.md`
> 
> I think they're both automatically generated from [here](https://github.com/handsontable/handsontable/blob/master/src/plugins/nestedRows/utils/rowMoveController.js#L13-L39), and I'm not sure what's wrong there, can you take a look? Thanks!

I think that these MD files will be fixed within https://github.com/handsontable/handsontable/pull/8796.

**Review by Siemienik — CHANGES_REQUESTED** [review]
I have only one comment, could you remove from this PR changes in the `dist` folder. AFAIK, these files are only changed during the release process.

All rest LGTM, thank you :)

**Review by Siemienik — APPROVED** [review]

**Comment by Siemienik** [comment]
Great job, thank you :)

**Pull request merged**
