### PR TITLE
Normalize scrolling on Microsoft Edge.

### PR DESCRIPTION
**Pull request by pnowak**
### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #4320 
2. #4771 

### Checklist:
- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by watnab** [comment]
Thank you for your work.

However `wheelDeltaY` should possibly be inverted in tableView.js even though `deltaY` is inverted in overlays.js.

If `deltaY` is inverted in tableView.js:
* Safari, Chrome(, and Opera) will ignore the change because there is `!isChrome() && !isSafari()`. -> OK
* Edge may ignore the change because `wheelDeltaY` will be truthy. -> Edge should be changed.
* The wheel direction of IE11, Firefox may be inverted. -> Other browsers should not be changed.

I'm sorry I had made a mistake in #4320 :
> ~~Applying -1 to event.deltaY may solve the issue.~~

**Comment by watnab** [comment]
> There is still a problem with a scroll on left overlay.

Sorry I failed to find the problem.

Does "left overlay" mean "fixed columns on the left side"?

What is the problem?

E. g.,
- The wheel direction is still inverted on left overlay.
- The wheel event is ignored on left overlay.
- Wheeling on left overlay causes an exception.

**Comment by pnowak** [comment]
@watnab Thank you for your help.

**Comment by swistach** [comment]
@watnab we decided to create a new issue with a scroll on firefox. It's present since 0.32.0. Related issue: #4532

**Comment by watnab** [comment]
@pnowak @swistach Thank you for your works.

> Sorry I failed to find the problem.
> a new issue with a scroll on firefox.
> #4532 

I understood.

**Pull request merged**
