### PR TITLE
Add export to CustomBorders

### PR DESCRIPTION
**Pull request by GordonSmith**
rollup.js fails with the following error without it:
```
{ Error: 'default' is not exported by ..\..\node_modules\handsontable\es\plugins\customeBorders\customeBorders.js
    at error (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:8390:3)
    at Module.trace (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:8487:10)
    at Module.traceExport (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:8526:29)
    at NamespaceVariable.module.getExports.concat.forEach.name (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:5561:36)
    at Array.forEach (native)
    at NamespaceVariable (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:5560:55)
    at Module.namespace (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:8436:31)
    at Module.trace (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:8481:24)
    at ModuleScope.findVariable (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:8093:22)
    at Identifier.bind (C:\Users\gordon\git\hpcc-js\node_modules\rollup\dist\rollup.js:6996:31)
  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 1184,
  loc:
   { file: 'C:\\Users\\gordon\\git\\hpcc-js\\node_modules\\handsontable\\es\\plugins\\index.js',
     line: 21,
     column: 7 },
  frame: '19: import Search from \'./search/search\';\n20: import TouchScroll from \'./touchScroll/touchScroll\';\n21: import UndoRedo from \'./undoRedo/undoRedo\';\n           ^\n22: import Base from \'./_base\';' }
```

### Context
RollupJS is unable to bundle the plugin unless it has an export declaration

### How has this been tested?
I added the missing ```export default``` and re-ran rollupjs in my project

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1.
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @GordonSmith 

Please change the branch, add tests and if you did not do it [sign the CLA.](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md)

**Comment by GordonSmith** [comment]
* I have signed the CLA
* which branch do I change it to?
* Where are your existing rollupjs tests hosted (or webpack or bundles in general)?

**Comment by GordonSmith** [comment]
@AMBudnik Is there anything else I need to do?  (this is just a a singe missing line from one of your plugins)

**Comment by AMBudnik** [comment]
As mentioned at https://github.com/handsontable/handsontable/pull/4572

please add a test

**Comment by GordonSmith** [comment]
...done.

**Comment by budnix** [comment]
Thanks for PR!

**Pull request merged**
