### PR TITLE
Introduced `separated` attribute for label options (`label` DOM element may wrap `input` or be placed next to it)

### PR DESCRIPTION
**Pull request by bud-e**
### Context

From now label & input(checkbox) are separated from each other when `separated` attr used.
User can apply the various style/css to checkbox without affecting the label.

### How has this been tested?

Tested it on some of the demos to ensure that it working proper without affecting others.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) (https://github.com/handsontable/handsontable/issues/3172)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/3172

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for doing the investigation over this issue and sharing the code

**Comment by wszymanski** [comment]
Hello, @bud-e. I have to say "good job". Nice tests, it works properly. I'll try to sync code with `develop` and merge it after just small refactor.

**Review by wszymanski — DISMISSED** [review]
@bud-e Good job 👏  I did small refactor and synced code with new `develop`. In new process there is one more QA step, @aninde will check how code works. After her review, if everything is okey, the PR should be merged.

**Review by wszymanski — APPROVED** [review]

**Comment by aninde** [comment]
@bud-e great job. Thank you for your effort :)

I checked tests and this feature on every browser that we support. Works fine. I'm giving +1. 
@wszymanski you can merge it. 

Demo with example https://jsfiddle.net/aninde/dtk8wpoh/

Tested on latests browsers:
macOS 11.2: Chrome 90.0.4430.40, Chrome 89.0.4389.90, Safari 14.0.3, Firefox 87.0, Edge 89.0.774.63, Opera 74.0.3911.203 
Windows 10 Edge 89.0.774.54, IE 11, Chrome 89.0.4389.90, Firefox 86 & 87
iOS 14.4 Safari, Chrome, 
iPad 14,  Safari, Chrome,

**Review by aninde — APPROVED** [review]

**Pull request merged**
