### PR TITLE
Fixed an issue where using updateSettings() has been breaking column sorting in specific cases

### PR DESCRIPTION
**Pull request by wszymanski**
### Context
There was re-initialization of the column meta cache which hasn't taken into account the fact that `columns` property expand the displayed dataset. A callback for `afterGetColHeader` hook tried to get meta related to the indicator from a not existing element in the map.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7228 

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by budnix — APPROVED** [review]
Now the `updateSettings` works 💪 

I'm not sure why the tests are placed into the "workaround regression check" (https://github.com/handsontable/handsontable/blob/0cae566c44313380359dc5c138906de715ca89f0/src/plugins/columnSorting/test/columnSorting.e2e.js#L2621) clause. The TODO says that the whole `describe` may be removed in the future - IMHO shouldn't. I'd remove that TODO line.

**Review by budnix — CHANGES_REQUESTED** [review]
https://github.com/handsontable/handsontable/pull/7257#pullrequestreview-485656862

**Comment by wszymanski** [comment]
Currently, we have a workaround for getting the first cell setting as the inheriting of non-primitive cell meta values doesn't work. We use an index mapper for storing column meta for non-primitive meta (`columnSorting` may be an object).

https://github.com/handsontable/handsontable/blob/4a63e9fe22b994c1e70c6e351046dccf47e1bda6/src/plugins/columnSorting/columnSorting.js#L93-L99

It should be removed. Column meta should provide settings for a single cell properly. Probably those tests won't be needed anymore after removing the workaround. WDYT?

**Comment by budnix** [comment]
> Currently, we have a workaround for getting the first cell setting as the inheriting of non-primitive cell meta values doesn't work. We use an index mapper for storing column meta for non-primitive meta (`columnSorting` may be an object).
> 
> https://github.com/handsontable/handsontable/blob/4a63e9fe22b994c1e70c6e351046dccf47e1bda6/src/plugins/columnSorting/columnSorting.js#L93-L99
> 
> It should be removed. Column meta should provide settings for a single cell properly. Probably those tests won't be needed anymore after removing the workaround. WDYT?

Sound reasonable 👍

**Review by budnix — APPROVED** [review]

**Pull request merged**
