### PR TITLE
Add script for generating legacy docs versions

### LINKED ISSUE #8252: New Docs: An array versions auto-generation
It'd be nice to do something with docs versions list that is used in the old docs to show all available versions. That list is currently updated manually https://github.com/handsontable/handsontable/blob/feature/issue-7624/docs/.vuepress/public/scripts/hot-versions.js and affects only the select element from the old docs.

image

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR adds a script that automates the generation of the content for the `hot-versions.js` file. That file is used by the older docs engine for generating the options for the version selector switcher. That file needs to be updated after each new docs version.

I had in my mind two approaches to solve the issue. 
1. Add the `hot-versions.js` file to ignore and regenerate its content every time when the docker image is built. But then while developing documentation the `npm` script would have to check if the file exists and regenerate its content if needed. This would require implementing an auth via GH Token that would unnecessarily complicate the stack.
2. Make the `hot-versions.js` file committable (as it is now) and generate its content only when the new version is created (via `npm run docs:version`). In that case, the GH token is not necessary as for unauthenticated requests there is a limit of 60 requests per hour - which is way beyond what's needed.

To not complicate the stack with env variables I choose the second approach.

_Edit:_
The `git` package is used here to fetch HoT releases to build an array of the HoT versions (with patch) for the older docs engine. Within the new engine, the patch fragments are not stored anywhere.

_[skip changelog]_

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. fixes #8252
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wojciechczerniak** [comment]
Do we need all the versions for legacy docs? Simple approach of listing versioned directories in new docs could be sufficient. 

Another thought: if we hook up to VuePress build process, we can generate the file without additional steps. Rather nice to have, and simplification for the build flow

**Comment by budnix** [comment]
> Do we need all the versions for legacy docs? Simple approach of listing versioned directories in new docs could be sufficient.

The file is consumed only by the old docs engine. Listing the directories would solve only versions >=9.0.0. 

> Another thought: if we hook up to VuePress build process, we can generate the file without additional steps. Rather nice to have, and simplification for the build flow

As the same as above. The file is not designed to work with new docs. It maintains the old docs pages. 

The file is temporary and in the next upcoming versions could be removed.

**Comment by wojciechczerniak** [comment]
> > Do we need all the versions for legacy docs? Simple approach of listing versioned directories in new docs could be sufficient.
> 
> The file is consumed only by the old docs engine. Listing the directories would solve only versions >=9.0.0. New documentation does not have the problem, there the versions are generated as you 

Yeah, I know. And we could generate the list for the dropdown by appending new docs by directory to the old mapping as we already know it, and don't have to request them from git. Also we're adding `9.0.1` next to `9.0.0` to the list in this PR, so we're going to list this documentation multiple times and redirecting to the same URL? Might be misleading

> The file is temporary and in the next upcoming versions could be removed.

But legacy documentation won't have newer versions of docs in the dropdown then? It can be removed 18 months from 9.0.0 release, which was just recently. This file is going to stick with us for some time

**Comment by budnix** [comment]
> > > Do we need all the versions for legacy docs? Simple approach of listing versioned directories in new docs could be sufficient.
> > 
> > 
> > The file is consumed only by the old docs engine. Listing the directories would solve only versions >=9.0.0. New documentation does not have the problem, there the versions are generated as you
> 
> Yeah, I know. And we could generate the list for the dropdown by appending new docs by directory to the old mapping as we already know it, and don't have to request them from git. Also we're adding `9.0.1` next to `9.0.0` to the list in this PR, so we're going to list this documentation multiple times and redirecting to the same URL? Might be misleading

You're right with `git`. It is not necessary to fetch the releases from the remote. I can grab the versions from the current directories plus `const` as an array of legacy versions (I'd extract [this](https://github.com/handsontable/handsontable/blob/feature/issue-8252/docs/.vuepress/theme/components/Versions.vue#L36) to config).

But what about the list of the versions for the old engine? If we don't want to update that list, the latest version is `9.0.0` and stays like this then the script/code that updates the `hot-versions.js` file would not be necessary.

Or we can update that list so if anyone gets old docs it will be always possible to navigate between the engines. The redirect rules on the server-side will make sure that it works properly.
image

**Comment by wojciechczerniak** [comment]
We've agreed that keeping `octokit` as a dependency and generating full list of patch versions will be consistent with the legacy documentation design and the best design for documentation readers.

**Review by wojciechczerniak — DISMISSED** [review]
👍

**Comment by budnix** [comment]
@wojciechczerniak I need re-review after syncing with develop branch https://github.com/handsontable/handsontable/pull/8497/commits/778b4bd3e637d20ebd82a2439d0d4374cecdd534.

**Review by wojciechczerniak — APPROVED** [review]

**Pull request merged**
