### PR TITLE
Enabling column sorting with multi column sorting won't crash the table anymore

### PR DESCRIPTION
**Pull request by wszymanski**
### Context
As the title says, there was a regression. From now, `columnSorting` is disabled when `multiColumnSorting` is enabled. It corresponds to the way how it worked for UI before Handsontable `8.0.0`.

There was a warning for such a situation, I've done it yet more precise.

### How has this been tested?
Manual tests when both plugins are enabled.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #7415

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by swistach — CHANGES_REQUESTED** [review]
I see a similar issue if you enable `multiColumnSorting` and try to enable `columnSorting` by `updateSettings`.

image

**Review by swistach — COMMENTED** [review]
I noticed a tiny glitch after doing the following steps:
- initialize Handsontable with `multiColumnSorting:  true`,
- sort out 2/3 columns with pressed <kbd>CTRL</kbd>
- run `updateSettings({ columnSorting: true })`

And result - numbers stay in `:after`, arrows dissapear:
image

Is it expected behaviour?

**Comment by wszymanski** [comment]
> Is it expected behaviour?

The answer is obvious, but this is another bug besides the scope. Described by you glitch is probably architecture problem as `ColumnSorting` and `MultiColumnSorting` cooperation haven't been considered too widely. It can be noticed since Handsontable `<=7', while the #7415 bug is typical regression.

I would only focus on the regression.

**Review by swistach — APPROVED** [review]
Please open another issue with a glitch I mentioned in the previous comment. At the moment I think we can go further.

**Pull request merged**
