### PR TITLE
Fix description for afterPluginsInitialized [DOCS]

### PR DESCRIPTION
**Pull request by scarletfog**
### Context
afterPluginsInitialized needed additional info.

### Types of changes

- [x] A change in the documentation.

### Related issue(s):
https://github.com/handsontable/docs/issues/49

### CODE REVIEW

**Review by AMBudnik — COMMENTED** [review]
Would

var container = document.getElementById('example1'),
    hot;

  Handsontable.hooks.add('afterPluginsInitialized', function() {
    //action
  });

  hot = new Handsontable(container, {
    manualColumnMove: true,
  });

be too much for an example?

**Review by pnowak — APPROVED** [review]
LGTM 👍

**Comment by scarletfog** [comment]
@AMBudnik I made it really short so it does not stand out too much from other examples on the page.

**Review by AMBudnik — APPROVED** [review]
True 👍

**Pull request merged**
