### PR TITLE
[RTL] Minor fixes for  Top and Bottom overlays

### LINKED ISSUE #8761: [RTL] BottomOverlay
### Description

When I set `dir='rtl'` the bottom overlay displayed incorrectly on the left of the website. It should display on the right, below the table.

### Steps to reproduce

Following this [configuration](https://github.com/Siemienik/handsontable-storybooks/blob/10bd304f4ae389538f62abc136a1cb531f5a4acd/vanilla/configurations.js#L436-L440) 

```js
configurations.FixedRowsBottom = {
    data: Handsontable.helper.createSpreadsheetData(60, 10),
    licenseKey: "non-commercial-and-evaluation",
    fixedRowsBottom: 1
};
```
I got: 
image

### PR DESCRIPTION
**Pull request by Siemienik**
### Context

This PR updates the positions for top and bottom overlays when RTL mode is on.
Additionally, I did refactoring. I added jsdoc `@property` to improve the IntelliSense experience

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. #8760 
2. resolves: #8764
3. resolves  #8761

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Review by budnix — CHANGES_REQUESTED** [review]
Can I ask you to add an E2E test (or tests) for Walkontable that would check if the overlays are correctly placed in RTL mode?

It's worth noticing that the PR affects the overlay's position only in the case when the window object is scrollable not when the components element is scrollable (the hot has defined `width` and `height` options).

**Comment by Siemienik** [comment]
Thanks for the review!

**Comment by budnix** [comment]
@Siemienik What about missing tests? https://github.com/handsontable/handsontable/pull/8940#pullrequestreview-821492922.

**Review by budnix — CHANGES_REQUESTED** [review]
https://github.com/handsontable/handsontable/pull/8940#issuecomment-986827552

**Comment by budnix** [comment]
The PR is merged into the https://github.com/handsontable/handsontable/pull/8940 where all overlays misalignment will be fixed.

**Pull request closed without merging**
