### PR TITLE
Fixed documentation for programmatically showing a comment

### PR DESCRIPTION
**Pull request by OmarElabd**
### Context
commentPlugin.editor.setCommentAtCell is not the correct function call, this may have been from updating to a new api.

### Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ X] My code follows the code style of this project,
- [ X] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @OmarElabd 

Thank you for sharing your pull request.

Please sign the CLA document and change the code to follow our [Contributing Guidelines](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

**Comment by OmarElabd** [comment]
Signed

**Comment by budnix** [comment]
Hi @OmarElabd our [policy](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) says that all PRs must be merged into `develop` branch. Could you switch to that branch so that I can merge your changes?

**Comment by OmarElabd** [comment]
I submitted a new pull request to develop #4405

**Pull request closed without merging**
