### PR TITLE
Merged `feature/react-docs` with `develop`

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

Merged with develop up to a0058dffccaa3774fddc39b905fe36b3d0101417.

[skip changelog]

### CODE REVIEW

**Review by warpech — CHANGES_REQUESTED** [review]
There is at least one non-content problem left: The method `getBuildDocsVersion` is mentioned in a few places, but it does not exist anymore on the  `feature/react-docs` branch.

@wszymanski also, the check's don't pass. Is that expected by you?

**Review by warpech — APPROVED** [review]
The PR looks good to me know. I smoke tested the docs locally using `npm run docs:review edbfc808b5dde287d35627cf441c3b3726b4a921` and it worked.

**Comment by wszymanski** [comment]
> Edit: `getBuildDocsVersion` is only mentioned in `/docs/12.1/api/sidebar.js`, which can be ignored, because this branch will not be used with 12.1 docs.

I finally updated it for purpose of safe rollback. The branch finally looks promising. Thanks @warpech @kirszenbaum for every suggestion and change. I'll merge when test will pass.

**Comment by wszymanski** [comment]
Screenshot 2022-07-20 at 16 38 41

@kirszenbaum Is it a bug how http://localhost:8080/docs/next/javascript-data-grid/installation/#overview page looks like?

**Comment by kirszenbaum** [comment]
@wszymanski - no, weird.

The entire file should look like this: https://gist.github.com/kirszenbaum/620f8129d20a09635aade30e483ba4a0#file-installation

The bit that needs to change: https://gist.github.com/kirszenbaum/620f8129d20a09635aade30e483ba4a0#file-installation-L82-L108

**Comment by wszymanski** [comment]
> @wszymanski - yes, weird.
> 
> As discussed, the `installation.md` file should look like this: [gist.github.com/kirszenbaum/a6b5dd647a82b16c4b1eae76a72c4ff7](https://gist.github.com/kirszenbaum/a6b5dd647a82b16c4b1eae76a72c4ff7)
> 
> The `vue3-modules` file should looke like this: [gist.github.com/kirszenbaum/abc184352f527a184618532c11caf22c](https://gist.github.com/kirszenbaum/abc184352f527a184618532c11caf22c)

I pushed changes https://github.com/handsontable/handsontable/pull/9684/commits/c0b18df7868f8c2861bc9bd07ad58d9173cbf96c. I will wait until the tests pass

**Pull request merged**
