### PR TITLE
Add Czech language

### PR DESCRIPTION
**Pull request by Ashus**
### Context
This adds support for Czech language to Handsontable

### How has this been tested?
It builds locally.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Additional language file or change to the existing one (translations)

### Related issue(s):
None.

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:
- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @Ashus 

Thank you very much for filling our language base with the Czech language. Could you please [alter the branch to `developer`](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md)? Contributing guide states that

>Always target your PR at the develop branch, not the master branch.

**Comment by Ashus** [comment]
Sorry about that, it is changed now.

**Comment by AMBudnik** [comment]
Great! Thank you very much. I will ask the dev team to review your PR.

**Comment by budnix** [comment]
@Ashus Can I ask you to add a changelog entry to this PR? Basically, to do that you need to execute the `npm run changelog entry` command in the root directory, follow the instructions and commit the generated file. Here you can find an explanation of [how it works](https://github.com/handsontable/handsontable/tree/develop/.changelogs).

**Comment by Ashus** [comment]
Changelog entry added. I had to use cygwin console though.

**Comment by budnix** [comment]
@kirszenbaum Can I ask you to add the Czech language to the documentation?

**Comment by kirszenbaum** [comment]
> @kirszenbaum Can I ask you to add the Czech language to the documentation?

@budnix - done: https://github.com/handsontable/handsontable/pull/9353

**Comment by warpech** [comment]
@Ashus, do you recommend that we refer to the name of the country as Czech Republic or Czechia? The name is used on the pages as https://handsontable.com/docs/api/options/#language

**Comment by Ashus** [comment]
@warpech, after discussing Wikipedia, I think Czechia is better as it is geographical and not political name.

**Comment by adrianszymanski89** [comment]
Hi @Ashus. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Pull request merged**
