### PR TITLE
Add default font size, color and family

### LINKED ISSUE #8661: Add a default font size, color and family
### Description

I noticed the inconsistency in CSS properties. For instance, we declare the specific styles of headers, selection, menus, etc. but at the same time, we miss such basic properties as a `font-family` and `font-size`.

Our goal is to make sure, that the default instance of Handsontable deployed on a clean page will look attractive without any extra work needed from the developer.

New global styles (make sure they apply to menus - context, column, dropdown) and accessories such as license key notification are provided below:
```
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Helvetica Neue", Arial, sans-serif;
font-size: 13px
font-weight: normal
color: #373737
```

Links color (`<a>`)
`color: #104acc`

### Result preview:
Screen Shot 2021-08-19 at 15 00 50

Consider removing additional styling from code snippets in our docs:
https://github.com/handsontable/handsontable/blob/master/docs/.vuepress/theme/styles/handsontable.styl

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR changes the default `font-size`, `font-family`, `font-weight`, and `color` for all elements within the `.handsontable` CSS class.

New styles:
```css
.handsontable {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Helvetica Neue", Arial, sans-serif;
  font-size: 13px;
  font-weight: normal;
  color: #373737;
}
```

Links color (`<a>`)
```css
color: #104acc;
```

Moreover, the PR updates the `puppeteer` package that uses the latest Chrome version. Thanks to that I was able to stabilize the tests and get rid of usage (from some places) of the `toBeArountValue` jasmine matches. The previously installed version of the `puppeteer` uses Chrome v80, now it's v93.

### How has this been tested?

I tested on different browsers and platforms and didn't found any new tests that fail.

|                       | macOS | Windows 10 (VM) | Ubuntu 20.04.2 LTS (VM) | Ubuntu 20.04.2 LTS (docker) |
|-----------------------|-------|-----------------|-------------------------|-----------------------------|
| Chrome 93 (puppeteer) | pass  | pass            | pass                    | pass                        |
| Chrome 92             | pass  | pass            | pass                    |                             |
| Firefox 91            | pass  | pass            | pass                    |                             |
| Safari 14.1.2         | pass  |                 |                         |                             |
| Edge 92               |       | pass            |                         |                             |

I tested in IE11 but as on the `master` as on the PR's branch, some test just fails. The count of failing tests is the same.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. fixes #8661
2.
3.

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by krzysztofspilka** [comment]
@aninde @wszymanski best if you could test in on mobile too, thx!

**Review by wszymanski — COMMENTED** [review]
I've checked it on MacOS using Chrome, Opera, FF, Safari. I've been using various configurations and it looks good! I haven't run tests on all browsers.

However, I've noticed that custom styles for documentation (`/docs` directory) weren't changed. Shouldn't it be done? What about custom styles for https://github.com/handsontable/handsontable.com-v2 - another issue?

**Comment by budnix** [comment]
> However, I've noticed that custom styles for documentation (`/docs` directory) weren't changed. Shouldn't it be done? What about custom styles for https://github.com/handsontable/handsontable.com-v2 - another issue?

Thanks for asking! Yes, I didn't change the styles in docs as it would break the docs for the 9.0 version. Currently, styles in docs are global for all versions. 

I checked the handsontable.com project and didn't found any redundant styles that would refer to PR changes.

**Review by wszymanski — APPROVED** [review]

**Review by krzysztofspilka — APPROVED** [review]

**Review by aninde — APPROVED** [review]
It looks good on all Handsontable-supported browsers (Chrome, Safari, FF, Edge, IE, Opera), as well as on mobile and iPad.

**Review by aninde — CHANGES_REQUESTED** [review]
One little thing caught my eye The ontent of the `collapsibleIndicator` buttons appears not centered in this version of CSS.

Screenshot 2021-09-03 at 14 02 40

Demo: https://jsfiddle.net/jcLtvmzq/1/

**Comment by budnix** [comment]
> It looks good on all Handsontable-supported browsers (Chrome, Safari, FF, Edge, IE, Opera), as well as on mobile and iPad.

Thanks! Fixed within https://github.com/handsontable/handsontable/pull/8681/commits/0ab085bed957330a36263a7ab3e4b3ef9176c40d.

**Comment by budnix** [comment]
> One little thing caught my eye. The content of the `collapsibleIndicator` buttons appears not centered in this version of CSS.
> 
> Screenshot 2021-09-03 at 14 02 40
> 
> Demo: https://jsfiddle.net/jcLtvmzq/1/

Thanks! Fixed within 0ab085b.

**Review by wszymanski — APPROVED** [review]

**Comment by budnix** [comment]
@aninde 🏓

**Review by aninde — APPROVED** [review]
Thank you! Works as expected on mobile & desktop browsers.

**Comment by zsyh** [comment]
How to revert this change? I don't like the new font.

**Comment by zsyh** [comment]
I find a method, whether correct or not, I share it here
```
.handsontable{
    font-size: 17px!important;
}

.handsontable a{
    color: #0000EE!important;
}

.handsontable a:visited
{
    color:#551A8B!important;
}

```

**Pull request merged**
