### PR TITLE
Add copyHeaders to copy and paste functionality

### PR DESCRIPTION
**Pull request by Moffmo**
### Context
Feature request to add column and row headers on copy and paste.

### How has this been tested?
I have tested manually and it was working when I set the settings in a demo script.
I was unable to create e2e unit test as the browser does not allow me to paste into a textbox. TextCopyable area does not help as my modifcations are done after getRangedData.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #2288
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by Moffmo** [comment]
#2288

**Comment by AMBudnik** [comment]
Hi @Moffmo 

Thank you for signing the CLA document. Your PR still needs some adjustments as the tests failed. Please take your time to investigate it

**Comment by Moffmo** [comment]
Running npm run test works for me locally. The travis CI build is not telling me any information about what the error is or what test it was running?

Also I have not changed anything to do with moment.js however I have created a vulnerable dependency path - could you assist?

**Comment by AMBudnik** [comment]
Hi @Moffmo 

unfortunately, this exceeds my ability to help, but I think that you will be able to compare your code with new copy-paste functionality and then decide if your solution can be helpful. We should be able to push a new version by the end of this week. Can we do it like this?

**Comment by AMBudnik** [comment]
Hi,

I am just checking by to let you know that the new copyPaste plugin has been released. If you'd have any concerns please let me know. In the meanwhile, I am closing the PR.

**Comment by AMBudnik** [comment]
Hi @Moffmo 

I just pinged you in the main issue but also wanted to update this pull request - the Copy with Headers functionality is officially released in Handsontable v12.3.0

Thank you for your input.

**Pull request closed without merging**
