### PR TITLE
Set max height for code preview tabs

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR sets the max height for the code preview tab.

The example https://handsontable.com/docs/column-filter/#filter-as-you-type:

#### Before:
image

#### After:
image

_[skip changelog]_

### Related issue(s):
1. https://github.com/handsontable/handsontable.com-v2/issues/135

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Comment by kirszenbaum** [comment]
@budnix - works fine, but looks a bit different on my side (on Chrome, built locally with `npm run docs:review 7a365ec34761af90d177646be752c8c0084b8848` and with cache reloaded):

1. In the light theme, the scrollbars are black, which makes them hard to spot:


2. In the dark theme, the scrollbars have different widths:

**Comment by budnix** [comment]
> 1. In the light theme, the scrollbars are black, which makes them hard to spot:

It's weird 🤔  Because I didn't change anything related to the theme, styles or so. Just added max-height for the code preview that forces showing horizontal scrollbar.

> 2. In the dark theme, the scrollbars have different widths

True. The scrollbar sizes were different for different axis. I fixed that within https://github.com/handsontable/handsontable/pull/9338/commits/363c116bafa525e0819a7f7f5faab6dcbd14a73b.

**Comment by kirszenbaum** [comment]
@budnix
1. The light-theme scrollbars are still black on my side (Chrome, MacOS). Same on Safari. Maybe it's sth with my local docs build.

2. The widths look fine now!

**Comment by budnix** [comment]
> 1. The light-theme scrollbars are still black on my side (Chrome, MacOS). Same on Safari. Maybe it's sth with my local docs build.

Ok, I'm able to reproduce the problem on Safari 👍  It turned out that it's not a new problem, the current docs have the same issue. I'll fix that in this PR as the change causes more scrollbars to appear making the problem more significant to fix.

**Comment by budnix** [comment]
@kirszenbaum I've prepared a fix https://github.com/handsontable/handsontable/pull/9338/commits/3f17b210204f1fe0beaefd4dcc899d0d1e3b9325 but it should work only for Chrome (I guessing). For Safari (at least 15.3) the page refresh is needed. This is the browser issue. The same glitch is reproducible on [Vue docs](https://vuejs.org/guide/introduction.html), or [Jest](https://jestjs.io/docs/snapshot-testing).

Within the commit, I reverted the OS-dependent scrollbar. On Windows, the scrollbar design on a light theme was rendered in Windows-style on dark in macOS style 🤷  Now the styles are unified.

#### Before
image image

#### After
image image

**Comment by kirszenbaum** [comment]
@budnix - I've built the docs using `npm run docs:review 3f17b210204f1fe0beaefd4dcc899d0d1e3b9325` again, emptied cache, and it looks like this on my side:

#### Chrome version 99.0.4844.83
chrome

#### Safari version 15.4 (17613.1.17.1.6)
safari

**Comment by budnix** [comment]
> @budnix - I've built the docs using `npm run docs:review 3f17b210204f1fe0beaefd4dcc899d0d1e3b9325` again, emptied cache, and it looks like this on my side:

To sum up. There are 2 issues.
 * The native scrollbars do not switch their color scheme after switching the theme button (only on Safari). However, after the page is refreshed everything is back to normal. This one is not easy to fix ([see](https://github.com/handsontable/handsontable/pull/9338#issuecomment-1077596566)). One of the solutions could be to restyle the native scrollbars to our own style independent of OS (like [Jest](https://jestjs.io/docs/snapshot-testing)).
 * The native scrollbars in the light theme are very dark[1]. I guess Chrome tries to match the color scheme to the scrollable element background. The solution will be the same as for the first issue. Add custom styling. However, with custom styling, we can lose the ability to give users the scroll feeling depending on their OS.

@kirszenbaum Have I included everything?
@warpech I need your help to make a decision.

[1]
Kapture 2022-03-29 at 10 16 25

**Comment by budnix** [comment]
@kirszenbaum, I've pushed some fixes to the scrollbar styling. Can you re-check the PR?

**Comment by kirszenbaum** [comment]
@budnix - on Chrome (macOS), everything looks smooth, dark theme or light theme :)

Same on Safari, with one tiny exception in the dark theme (the white square in the bottom-right corner). AFAIC it's good enough for me, just letting you know:


Do you think we should properly test it on all browsers? @aninde FYI

**Review by kirszenbaum — APPROVED** [review]

**Comment by budnix** [comment]
> Same on Safari, with one tiny exception in the dark theme (the white square in the bottom-right corner).

Yeap, I noticed that. I believe it's a browser bug. I wasn't able to find a workaround for this. Hopefully, it only happens once while switching the theme. After the page refreshes everything is back to normal.

**Pull request merged**
