### PR TITLE
Remove the `enzyme` dependency from the React wrapper.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR removes the `enzyme` dependency from `@handsontable/react`'s dependencies, replacing it with the native `react-dom/test-utils`.

### How has this been tested?
Run all the test cases.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9151 

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [x] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by Siemienik — DISMISSED** [review]
I could check is that It works locally - I run tests, all passes. It is also the same for the CI - all is green.
However I don't feel like an expert on this part of knowledge, maybe someone else should check it also?

**Review by budnix — CHANGES_REQUESTED** [review]
Thanks for the tests simplification. To make it even more simplified WDYT about moving the tests suite setup to one place. Something like https://github.com/handsontable/handsontable/compare/feature/issue-9151...feature/issue-9151-cr?

**Comment by jansiegel** [comment]
> Thanks for the tests simplification. To make it even more simplified WDYT about moving the tests suite setup to one place? Something like [feature/issue-9151...feature/issue-9151-cr](https://github.com/handsontable/handsontable/compare/feature/issue-9151...feature/issue-9151-cr).

@budnix A CR-PR, haven't seen that before 😆 Good idea! Could you make a PR to this branch, so we can merge it?

**Comment by budnix** [comment]
> Could you make a PR to this branch, so we can merge it?

Sure! https://github.com/handsontable/handsontable/pull/9205.

**Review by budnix — APPROVED** [review]
👍

**Pull request merged**
