### PR TITLE
Hello World App for the new docs (Angular)

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

Provided demos showing capabilities of Handsontable.

- [x] Angular

Link to the CodeSandbox: https://codesandbox.io/s/handsontable-angular-data-grid-hello-world-app-50pb7

[skip changelog]

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8206
2. #7624

### CODE REVIEW

**Review by Siemienik — COMMENTED** [review]
All looks good for me. Please update the description above a Hello World.

> The demos for Angular and Vue are coming in June 2021, stay tuned!

to

> The demo for Vue is coming in June 2021, stay tuned!

**Comment by Siemienik** [comment]
I reviewed and note some proposals as a `TODO` comments
https://codesandbox.io/s/handsontable-angular-data-grid-hello-world-app-forked-9vq02?file=/src/app/app.component.ts:261-289

**Comment by wszymanski** [comment]
@Siemienik The code was updated and synced with #develop branch.

**Review by Siemienik — DISMISSED** [review]
Thank you for applying my requests to the demo.
LGTM. 🥇

**Review by wojciechczerniak — APPROVED** [review]
I see a warning about `HTMLTableDataCellElement` and `HTMLTableHeaderCellElement`, this element type is deprecated according to MDN. A more general `HTMLTableCellElement` should be used instead?

**Comment by wszymanski** [comment]
> I see a warning about `HTMLTableDataCellElement` and `HTMLTableHeaderCellElement`, this element type is deprecated according to MDN. A more general `HTMLTableCellElement` should be used instead?

Changed in every project. Thanks.

**Review by Siemienik — APPROVED** [review]

**Pull request merged**
