### PR TITLE
Feature/issue 5913

### PR DESCRIPTION
**Pull request by apegadoboureghida**
### Context

@tjgambs  described the whole context in #5913

### How has this been tested?

Linux: Tested on Chrome and Firefox (which was originally failing)
Windows 10: Tested on high-resolution monitor on Edge and Chrome
Mac: Tested on Firefox, Chrome and Safari (all of which were originally failing)
All of the operating systems/browsers that were effected in @tjgambs issue are working as expected with this small modification.

We also tested to make sure that #4498 was not broken. We prevent the stuttering experienced in retina displays while also solving the scrolling issue by removing the .parentNode.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/5913
2. https://github.com/handsontable/handsontable/issues/4498
3. https://github.com/handsontable/handsontable/issues/4651

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for adding the changes and signing CLA.

**Comment by veeru1087** [comment]
@apegadoboureghida - Please resolve the conflict. We badly need this bug to be fixed.

**Comment by veeru1087** [comment]
@apegadoboureghida any update?

**Comment by apegadoboureghida** [comment]
@veeru1087 I keep resolving the conflicts as they appear.

**Comment by wojciechczerniak** [comment]
Sorry @apegadoboureghida for another conflict to resolve, we've missed previous fix. I've pinged @pnowak to merge this first thing in the morning. Thank you for the bug fix.

**Comment by apegadoboureghida** [comment]
Don't worry, @wojciechczerniak, happy to help!

**Pull request merged**
