### PR TITLE
Move the examples scattered between multiple Codesandbox accounts to the repo.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR moves all the Codesandbox examples used in the docs and moves them to the repo's `examples` directory.
These examples were stored on multiple Codesandbox accounts, which made it really hard to keep track and update them when necessary.

### Things done in this PR

- [x] 1. Moved the examples to `examples/next`
- [x] 2. Generated the examples to `11.0.0` based on these changes.
- [x] 3. Temporarily added `--if-present` flag to the `examples:test` script, as none of the moved examples have them prepared yet.
- [x] 4. Made necessary modifications to the dependency structure and/or configuration for the examples to work both locally and on Codesandbox.
- [x] 5. Set the version of Handsontable and the wrappers to `latest` for the `next` "package" - the version-based "packages" should assign the appropriate versions automatically.
- [x] 6. Updated the Codesandbox embed snippets with the new examples' urls.
- [x] 7. Temporarily added the `--legacy-peer-deps` flag to the examples' installation script.

### Things left to do
1. Think about moving away from Codesandbox, as it seems to be _**extremely**_ unstable at this point. I spend the vast majority of the time of this task on tweaking dependency versions, configs that worked fine outside Codesandbox, investigating the source of odd errors (many of those in internal Codesandbox scripts) and simply waiting on the sandboxes to reload.<br>
2. Rewriting the examples to utilize the same dependencies and general example structure. <br> For this PR, I've only taken all of them as they were and moved them to the `examples` subdirectory + done some necessary updates to make them work in Codesandbox (see point 1). <br> Many of the examples contain unused, outdated, or misconfigured dependencies, making it harder for the users to get an idea of what's going on, which is the exact opposite of what the _example_ should be.<br>
3. Design and implement test cases for the examples (see point 3 in the _Things done in this PR_ section)
4. Automate the Codesandbox embed snippets url version changes for the documentation.
5. **The `Hello World` example in the current (and thus, the next) documentation seems to have stopped working, it needs to be fixed.**
-------

### How has this been tested?
Run `npm run test` from the `examples` directory.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8927 

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jansiegel** [comment]
### To the reviewers:

Testing the docs with updated embed URLs is a little more tricky than usual - the new paths point to the `develop` branch, which doesn't contain the moved examples yet (they will be merged after the release).

To make them appear in the documentation locally, before running `docs:start`, you'd need to temporarily replace all mentions of
```
github/handsontable/handsontable/tree/develop/examples/next
```
with 
```
github/handsontable/handsontable/tree/feature/issue-8927-for-11-0/examples/next
```

in the `docs/next` directory.

**Review by wojciechczerniak — APPROVED** [review]
👍

**Comment by warpech** [comment]
Stupid question - how do I even run these examples (locally or on CodeSandbox) if they require yet unpublished package `11.0.0`?

Locally, I was able to run some examples (such as React Hello World) by substituting `11.0.0` with `10.0.0`.

On CodeSandbox, I was not able to run much. 90% chance of crash in the building process.

**Comment by jansiegel** [comment]
> Stupid question - how do I even run these examples (locally or on CodeSandbox) if they require yet unpublished package `11.0.0`?
> 
> Locally, I was able to run some examples (such as React Hello World) by substituting `11.0.0` with `10.0.0`.
> 
> On CodeSandbox, I was not able to run much. 90% chance of crash in the building process.

@warpech,

I've tested if all of them build locally (using their `build` commands) and run locally _some_ of them (using their `start`/`serve` commands).

As for Codesandbox, I tested all of them using the `github -> githubbox` trick, and they all worked (except for the `Hello World` example for React). Of course, some of them required multiple refreshes/running them on different browsers/waiting for several minutes, because of the Codesandbox instability.

We have a Github Actions workflow for automatic deployment of the examples to `gh-pages` (and [a PR with my review pending](https://github.com/handsontable/handsontable/pull/7661), which is _On Hold_ for quite some time now, I don't exactly remember why, to be honest), which we could utilize (after testing) to preview examples, and possibly embed them in the docs, correct @wojciechczerniak?

**Comment by wojciechczerniak** [comment]
> We have a Github Actions workflow for automatic deployment of the examples to `gh-pages` (and [a PR with my review pending](https://github.com/handsontable/handsontable/pull/7661), which is _On Hold_ for quite some time now, I don't exactly remember why, to be honest), which we could utilize (after testing) to preview examples, and possibly embed them in the docs, correct @wojciechczerniak?

Correct!

**Pull request closed without merging**
