### PR TITLE
Update jwalton/gh-find-current-pr to a development version

### PR DESCRIPTION
**Pull request by warpech**
### Context

This PR updates an action `jwalton/gh-find-current-pr` used in our workflow to a development version https://github.com/jwalton/gh-find-current-pr/pull/21, which fixes our problem #9678.

I have reviewed other changes before this SHA https://github.com/jwalton/gh-find-current-pr/commits/65d225dc3075efac1d37658e44c10edcc9999e87 and they look ok.

This PR also removes the redundant file `docs/.nvmrc` which referred to an old version of Node.

### How has this been tested?

All checks pass (apart from npm audit), which is fixed on develop.

To test if this PR actually works as promised, it needs to be merged to `feature/react-docs`.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9678
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

[skip changelog]

### CODE REVIEW

**Review by jansiegel — CHANGES_REQUESTED** [review]
As you mentioned yourself, @warpech, this one's hard to test, but the fix in the `gh-find-current-pr` package seems to match the problem described in the connected issue, so that looks fine to me.

But it looks like this PR removes the wrong `.nvmrc` - `./.nvmrc` is gone, but [`docs/.nvmrc` still exists](https://github.com/handsontable/handsontable/blob/feature/issue-9678/docs/.nvmrc).

**Comment by warpech** [comment]
> But it looks like this PR removes the wrong .nvmrc - ./.nvmrc is gone, but [docs/.nvmrc still exists](https://github.com/handsontable/handsontable/blob/feature/issue-9678/docs/.nvmrc).

Oops! Good that you've checked, thanks. Fixed in my last 2 commits. Please re-review.

**Review by jansiegel — APPROVED** [review]
👍

**Comment by warpech** [comment]
Thanks for the review. Before merging, I will double check by:
1. running the updated action locally to see if it gives the desired PR number
2. compare dependencies history between the action versions https://github.com/jwalton/gh-find-current-pr/compare/b6f8d7342efe4913388d5d1ac7f4b956caa5db52..65d225dc3075efac1d37658e44c10edcc9999e87

**Comment by budnix** [comment]
Recently the GH workflow [action was updated](https://github.com/handsontable/handsontable/pull/10077). I can only guess, but it seems to me that this issue may be not valid anymore. @warpech, can you confirm?

**Comment by warpech** [comment]
Yes, the problem was fixed in https://github.com/jwalton/gh-find-current-pr/releases/tag/v1.3.1, so your update includes it. Thank you

**Pull request closed without merging**
