### PR TITLE
Remove extra \r in pasted data

### PR DESCRIPTION
**Pull request by JSalter02**
### Context

Pasted data from windows (i.e. from Excel, or anywhere) includes an extra \r that is visible when you edit the cell. It is trimmed away after editing, but causes serious problems if it remains.

### How has this been tested?

I verified that this properly splits on \r (Mac), \n (Linux), or \r\n (Windows)

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #5477
2.
3.

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by JSalter02** [comment]
I don't see a particularly good place to add it. I suggest you add a test if you want one. I've fixed a major bug for you and am not inclined to donate further time to your product.

**Comment by swistach** [comment]
Unfortunately, we cannot accept PRs which are not fit with our [contributing policy](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

**Comment by JSalter02** [comment]
Well, I guess that's your choice, but you should be aware we're planning to drop handsontable due to your extremely slow and poor support. This bug, in particular, breaks everything related to pasting data in, and should have been patched rapidly.

**Comment by JSalter02** [comment]
And incidentally, instead of asking me to do more work for you, you should be thanking me for spending my time to find your bug and provide you with a patch.

**Comment by AMBudnik** [comment]
Even if we're not able to pull the changes without tests (as _it's against the rules_) it's very nice of you for doing the whole investigation @JSalter02 It wasn't obvious what's causing the issue in the first place, but now, thanks to you, we know.

**Comment by JSalter02** [comment]
I don't blame you for having that rule in general. But without an obvious place to add tests for this issue, you're asking me to add a bunch of test infrastructure for a 1 line fix, and all of this review process has delayed an urgent bug from being patched.

You don't have to pull my code, but you do need to patch this bug.

**Comment by swistach** [comment]
Thank you @JSalter02,
we will finish it on a separated branch.

**Comment by jaredbaszler** [comment]
This is causing issues with our clients as well.  Please fix/approve ASAP.

**Comment by AMBudnik** [comment]
Hey @jaredbaszler 

it's already merged. It'll be published soon

**Pull request merged**
