### PR TITLE
Docs: Add support for remembering the chosen framework

### LINKED ISSUE #9907: Docs: React docs: Remember last used framework in the browser and redirect to it upon the next visit
### Description

User story:

> As a React developer I want to be able to easily reach the React-specific docs and each time I re-visit it see the proper version of it, so I don’t waste my time wandering around site looking for a switcher.

----

We have explained this in the design document in the following way:

The last used FIXED_PHRASE is remembered in the browser (as a cookie or localStorage). The next time the user visits https://handsontable.com/docs/, they should be redirected to https://handsontable.com/docs/FIXED_PHRASE/

The "fixed phrase" is either "javascript-data-grid" or "react-data-grid"

### Links

https://handsontable.com/docs/

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR adds the feature to the Docs, which enables remembering the chosen framework. Once the framework is remembered, all Docs pages that do not have a defined framework within the name are redirected to the page with the remembered framework.

For example, when the "react" framework is saved, the following pages are permanently redirected:
 * `/docs/` -> `/docs/react-data-grid/`;
 * `/docs/12.1/` -> `/docs/12.1/react-data-grid/`;
 * `/docs/foo/bar` -> `/docs/react-data-grid/foo/bar`;
 * `/docs/12.1/foo/bar` -> `/docs/12.1/react-data-grid/foo/bar`;
 * The same happens for legacy URLs defined in [redirects.conf](https://github.com/handsontable/handsontable/blob/feature/issue-9907/docs/docker/redirects.conf#L1). For example:
   * `/docs/plugins/` -> `/docs/react-data-grid/plugins/`;
   * `/docs/demo-scrolling` -> `/docs/react-data-grid/row-virtualization/`;
   * ...

When the URL page already contains the framework, the page won't be redirected. For example:
 * `/docs/javascript-data-grid/`;
 * `/docs/12.1/javascript-data-grid/`;
 * `/docs/javascript-data-grid/foo/bar/`;
 * `/docs/12.1/javascript-data-grid/foo/bar/`;

_[skip changelog]_

### How has this been tested?

I tested the changes locally using the Docker image. The redirect rules are applied to the server, so for `watch` mode, it won't work.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes #9907

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Review by wszymanski — CHANGES_REQUESTED** [review]
The code looks good, everything except one case works.

Below pages (without slash at the end) redirects to wrong place:

`/docs/javascript-data-grid`
`/docs/12.1/javascript-data-grid`
`/docs/javascript-data-grid/foo/bar`
`/docs/12.1/javascript-data-grid/foo/bar`

**Comment by budnix** [comment]
> `/docs/javascript-data-grid`
> `/docs/12.1/javascript-data-grid`
> `/docs/javascript-data-grid/foo/bar`
> `/docs/12.1/javascript-data-grid/foo/bar`

@wszymanski I've checked those URLs, and it seems all work. I've used an [HTTP client](https://httpie.io/) (can be `curl`) to read the response headers. Here are my results:
 * `http -h http://localhost:8080/docs/javascript-data-grid Cookie:docs_fw=react` -> No redirect;
 * `http -h http://localhost:8080/docs/12.1/javascript-data-grid Cookie:docs_fw=react` -> No redirect. Renders as 404 - becouse it's local env;
 * `http -h http://localhost:8080/docs/javascript-data-grid/foo/bar Cookie:docs_fw=react` -> No redirect. Renders as 404 - because it's local env;
 * `http -h http://localhost:8080/docs/12.1/javascript-data-grid/foo/bar Cookie:docs_fw=react` -> No redirect. Renders as 404 - because it's local env;

Can you check again?

**Comment by wszymanski** [comment]
> > `/docs/javascript-data-grid`
> > `/docs/12.1/javascript-data-grid`
> > `/docs/javascript-data-grid/foo/bar`
> > `/docs/12.1/javascript-data-grid/foo/bar`
> 
> @wszymanski I've checked those URLs, and it seems all work. I've used an [HTTP client](https://httpie.io/) (can be `curl`) to read the response headers. Here are my results:
> 
> * `http -h http://localhost:8080/docs/javascript-data-grid Cookie:docs_fw=react` -> No redirect;
> * `http -h http://localhost:8080/docs/12.1/javascript-data-grid Cookie:docs_fw=react` -> No redirect. Renders as 404 - becouse it's local env;
> * `http -h http://localhost:8080/docs/javascript-data-grid/foo/bar Cookie:docs_fw=react` -> No redirect. Renders as 404 - because it's local env;
> * `http -h http://localhost:8080/docs/12.1/javascript-data-grid/foo/bar Cookie:docs_fw=react` -> No redirect. Renders as 404 - because it's local env;
> 
> Can you check again?

I confirm that it works on locally build Docker image, while it doesn't on [the image from the comment](https://github.com/handsontable/handsontable/pull/9923#issuecomment-1250728355).

**Comment by wszymanski** [comment]
Command running Docker for the last commit show that everything works properly.

`npm run docs:review 2863ae6cc2f051cb5b403adf453eb2df7fc209e9`

**Review by wszymanski — APPROVED** [review]

**Pull request merged**
