### PR TITLE
Work around a Chrome bug causing the freshly merged cells to not have right and bottom borders.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR adds a logic to work around a Chrome bug, forcing a repaint after the merge action, only when triggered in Chrome.

I managed to reproduce the issue without Handsontable: https://jsfiddle.net/js_ziggle/qga74pyL/
And work around it similarly to as I did in this PR: https://jsfiddle.net/js_ziggle/L7b5pgzs/

### How has this been tested?
As it seems to be only a visual glitch, I don't know how to test it without visual tests.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. handsontable/dev-handsontable#521

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by budnix — CHANGES_REQUESTED** [review]
The fix works only for the main table. When you merge the cells on the overlays the issue still exists.

While searching for some information about the Chrome issue I found [this](https://github.com/asciidoctor/asciidoctor/issues/3793). I changed the `border-collapse` to `collapse` and besides the fact that you would have to shift the selection by the pixel, merging cells works without the workaround. Maybe we should go in that way? 🤔

**Comment by jansiegel** [comment]
> While searching for some information about the Chrome issue I found [this](https://github.com/asciidoctor/asciidoctor/issues/3793). I changed the `border-collapse` to `collapse` and besides the fact that you would have to shift the selection by the pixel, merging cells works without the workaround. Maybe we should go in that way? 🤔

We got a comment like this in our current spreadsheets:
https://github.com/handsontable/handsontable/blob/803baf1b6c72c1466da2ab8a7a9ae06383f7141a/handsontable/src/3rdparty/walkontable/css/walkontable.scss#L43-L44

I tested the case described in the StackOverflow link, and I _think_ it's working fine in the latest versions of Chrome, FF, and Safari.

That being said, applying `border-collapse: collapse` to the current table makes the first table column a little wider, which results in the selection being misplaced (as you mentioned earlier). I'm wondering if modifying the table to work with `collapse` isn't a kind of breaking change? I'm not sure yet.

I'll take a closer look at it, as it could potentially be less "hacky" as my fix.

**Comment by krzysztofspilka** [comment]
@jansiegel @budnix collapsing columns might potentially cause issues with selection, custom borders, and proper width calculation (settings like stretched and relative table widths should be double-checked).

**Comment by jansiegel** [comment]
I tested the `border-collapse` idea and:

1. It looks like it's a good way to move forward, as it removes the need for this PR's workaround,
2. If I'm measuring it correctly, it resolves an issue we currently have, which is:
    - Currently, in an empty table with default column widths, not all the columns have the same width; namely, the first one is narrower than the rest by `1px`:
      image
      After implementing `border-collapse: collapse`, all the columns have a width of `49px`.
   - That change, however, results in some visual glitches, like a misplaced selection (moved by 1px, most probably because of the column width change), missing left-side borders, etc.
   - Resolving those issues would require going through the code and removing previously added workarounds that most probably compensate for the `1px` the first column is missing.

That being said, resolving those issues would require some additional time, so after discussing it with @budnix and @adamu-handsontable, we decided to temporarily implement this PR's workaround and tackle this issue in the future.

I created a separate issue to track its future progress: https://github.com/handsontable/dev-handsontable/issues/1033.

**Review by budnix — CHANGES_REQUESTED** [review]
Weird 🤔 the fix stopped working. I've tried merging the cells within the main table and the left overlay, but the borders are still missing.
Kapture 2023-01-20 at 09 25 08

**Comment by jansiegel** [comment]
@budnix 
🤦 After a refactor, I forgot to include the `master` overlay in the fix. Could you check if it works alright after https://github.com/handsontable/handsontable/pull/10212/commits/c2f62b8daf4a5004dc89b71e09d162c1954b5b68?

**Comment by budnix** [comment]
> @budnix 🤦 After a refactor, I forgot to include the `master` overlay in the fix. Could you check if it works alright after [c2f62b8](https://github.com/handsontable/handsontable/commit/c2f62b8daf4a5004dc89b71e09d162c1954b5b68)?

It's definitely better, but there are still some cases where the borders disappear. Here, in the bottom overlay, the cells do not have a border:
Kapture 2023-01-23 at 09 30 52

**Review by budnix — APPROVED** [review]
👍

**Comment by aninde** [comment]
There are still a few cases where borders do not appear on Chrome and Edge. Check out on the demo https://jsfiddle.net/5sbfk4d7/

https://user-images.githubusercontent.com/30186818/214529657-14482072-7bff-4eb9-ad4f-e2eff52051ae.mov

- merging regular cell with cell with bottom overlay (fixedRowsBottom)

Screenshot 2023-01-25 at 10 39 05


- merging left overlay with bottom overlay (fixedColumn with fixedRowsBottom)
Screenshot 2023-01-25 at 10 42 27

**Comment by AMBudnik** [comment]
Ref: https://github.com/handsontable/dev-handsontable/issues/289 - MergeCells produces Uncaught TypeError error when we try to merge area with fixedRowsBottom

**Comment by aninde** [comment]
@jansiegel  The bug is still present after doing autofill on merged cell. Chrome 109.0.5414.119 (Official Build) (x86_64) / macOS 12.6.3 (21G419)

https://jsfiddle.net/aninde/pa6t15 v12.3.1

https://user-images.githubusercontent.com/30186818/216316374-41ef9979-97b4-4bcc-bc48-1505259d7c90.mov

**Comment by jansiegel** [comment]
> @jansiegel The bug is still present after doing autofill on merged cell. Chrome 109.0.5414.119 (Official Build) (x86_64) / macOS 12.6.3 (21G419) and Windows 10. After scrolling the table are borders are back.
> 
> https://jsfiddle.net/aninde/xjowpvu0/ v12.3.1
> 
>  Screen.Recording.2023-02-02.at.12.45.23.mov

@aninde The fiddle you linked to doesn't match the video you sent. How do I replicate the problem?

**Comment by aninde** [comment]
@jansiegel 
1.Select one of the merged cell
2. Autofill it down to merge cells below.

**Comment by aninde** [comment]
After autofill on merged cells we still missing borders. Scrolling or merging another cells make borders visible, selection not.
https://user-images.githubusercontent.com/30186818/216317997-002ccd2c-bf91-4c9f-ab75-92e3c6d892f6.mov

**Comment by jansiegel** [comment]
I'll look into it 👍

**Comment by jansiegel** [comment]
@aninde Should be fixed in #10225.

Could you check if it works fine now? 

- version: `12.3.1-next-8792e1c-20230202`
- https://jsfiddle.net/js_ziggle/8dLp7qjf/

**Comment by aninde** [comment]
@jansiegel now it works like a charm on Chome on macOS and Windows 10 & 11. 
Drawing borders works after autofill on merged cells works well on each direction.
 https://jsfiddle.net/aninde/16tgpumr/ version: `12.3.1-next-8792e1c-20230202`

Screenshot 2023-02-02 at 14 28 00

**Comment by AMBudnik** [comment]
Released in Handsontable v12.3.1

**Comment by zy-zero** [comment]
@jansiegel 
Hello, here have some issue with merge cells
when I use Core.updateSettings to update the hot table setting with merge cell. it also no right and bottom border.
following is my code. Can we have some function to resolve this issue?

```
import Handsontable from "handsontable";
import ReactDOM from "react-dom";
import { HotTable } from "@handsontable/react";
import { registerAllModules } from "handsontable/registry";
import "handsontable/dist/handsontable.full.min.css";
import { useEffect, useRef, useState } from "react";

registerAllModules();

const HtTable = () => {
  const tableRef = useRef<HotTable>(null);
  const [hotSetting, setHotSetting] = useState({
    height: 320,
    colWidths: 48,
    rowHeaders: true,
    colHeaders: true,
    contextMenu: true,
  });

  useEffect(() => {
    if (tableRef.current) {
      const table = tableRef.current.hotInstance;
      const data = Handsontable.helper.createSpreadsheetData(100, 50);
      if (table) {
        table.updateSettings({
          data: data,
        });
      }
    }
  }, [tableRef.current]);

  const [merge, setMerge]= useState(false);

  const handleMergeChange = () => {
    setMerge(!merge);
  }

  useEffect(() => {
    if (tableRef.current) {
      const table = tableRef.current.hotInstance;
      if (table ) {
        if(merge){
          table.updateSettings({
            mergeCells: [
              { row: 1, col: 1, rowspan: 3, colspan: 3 },
              { row: 3, col: 4, rowspan: 2, colspan: 2 },
              { row: 5, col: 6, rowspan: 3, colspan: 3 },
            ],
          });
        } else{
          table.updateSettings({
            mergeCells: [],
          });
        }
      }
    }
  }, [merge]);

  return (
    <div>
      <button className="merge-cell" type="button" onClick={handleMergeChange}>
        Merge {merge}
      </button>
      <HotTable
        ref={tableRef}
        // data={Handsontable.helper.createSpreadsheetData(100, 50)}
        settings={hotSetting}
      />
    </div>
  );
};

export default HtTable;

```

**Comment by jansiegel** [comment]
@zy-zero Seems to work fine when I implemented your example in JSFiddle: https://jsfiddle.net/js_ziggle/83x4e1cy/
@AMBudnik could you confirm?

**Comment by zy-zero** [comment]
image
it is not right I think.
And may be your computer screen setting should be 100% zoom. don't use 125% zoom.
My computer is:
Vershion	Windows 10 HOME
22H2
OS Version	19045.2788

Chrome version is 113.0.5672.93. Do this information can help you?

**Comment by jansiegel** [comment]
@zy-zero, @AMBudnik 
You're right - it looks like it works fine on a retina display but breaks on a regular monitor. @AMBudnik when you're creating an issue for this problem, could you add a note about it for future reference?

**Comment by zy-zero** [comment]
> @zy-zero, @AMBudnik You're right - it looks like it works fine on a retina display but breaks on a regular monitor. @AMBudnik when you're creating an issue for this problem, could you add a note about it for future reference?

Hi @jansiegel @AMBudnik Do this fixed?

**Comment by AMBudnik** [comment]
Hi @zy-zero 

We have the second issue reported internally in our ticketing system.

I made a note to infirm you once we fix it.

**Pull request merged**
