### PR TITLE
Test + fix for updateSettings breaking on mixed in attributes to Array.

### PR DESCRIPTION
**Pull request by archit**
I noticed this issue, while trying to use Handsontable with EmberJS.

### CODE REVIEW

**Comment by archit** [comment]
./ping

**Comment by archit** [comment]
ping @jansiegel

**Comment by archit** [comment]
ping

**Comment by budnix** [comment]
Merged into develop by commit https://github.com/handsontable/handsontable/commit/0f2feebdcfa2b71d22d6ffb14d93cdd44cf4ce11. Additionaly I saw that this fix was implemented in 0.15.0-beta1 but without tests.

**Pull request closed without merging**
