### PR TITLE
Add CodeSandbox CI to our PR workflow

### PR DESCRIPTION
**Pull request by wojciechczerniak**
### Context
CodeSandbox CI bot should follow the link to the issue, get the example and build it with newer HoT version. It should also take three examples from the config file and create new forks.

And as a developer I attach another example: https://codesandbox.io/s/amazing-cohen-9elvv
which should be included as well. Let's see 👀 

### How has this been tested?
It is a test 😄 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6563
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by wojciechczerniak** [comment]
My investigation showed that internal CodeSandbox requests resource with `version` missing in the URL to JSDelivr CDN:

Screenshot 2019-12-13 at 16 06 14


Might be something wrong in our build or CodeSandbox parser. Reported: https://github.com/codesandbox/codesandbox-client/issues/3203

**Comment by wojciechczerniak** [comment]
I think I've found the issue. CodeSandbox has a problem with loading `voc` library. It cannot parse `version` to load it from CDN. `voc` is a dependency of `bassel` which is used by `@handsontable/formulajs`.

In earlier versions of `bassel` the `voc` version was not specified:

https://github.com/SheetJS/bessel/blob/31237637de54abece1ebf05944b3859c677b4c3b/package.json#L14

In that case, CodeSandbox should omit `@` and load the latest version. That what the author intended. But it doesn't work like that ATM.

The current `bassel` version has `voc` version provided. It was even moved to `devDeps` so it doesn't have to be loaded by Handsontable either.

https://github.com/SheetJS/bessel/blob/2e2331329891dc5c16bda3461db0b9fe590ff2e9/package.json#L12

To move forward with this PR and don't wait for CodeSandbox (this is an edge case so they can ignore it for a long time) and I'm not sure if that will solve the issue (let's say we load latest `vox`, will it work with current `formula.js` ?) we can update the deps for `formula.js` to a never `bassel` package: 

https://github.com/handsontable/formula.js/blob/ae8f338f10f49dafe2b17cfa210202ceeb55f62b/package.json#L25

@budnix Do you think it will work with a simple package update for `formula.js`?

**Comment by wojciechczerniak** [comment]
It's alive! Thx @budnix 

WDYT @handsontable/devs @warpech ?

**Comment by warpech** [comment]
Amazing! 

However, I have a few questions already: 

1. It does not load for me in Firefox (normal and incognito). Am I alone with that problem?
2. It takes 15 seconds to load in Chrome and 25 seconds to load in Edge. This is quite annoying, can anything be done to speed this up?
3. In CodeSandbox UI, can I force building any branch name or commit SHA of Handsontable and/or wrappers?
4. If my PR has 50 commits, will CodeSandbox create 50 comments with different sandboxes? I am not saying it is bad, just asking :D I know that redundant comments can be hidden using GitHub UI.
5. Why are there two slightly different sandboxes for React? https://codesandbox.io/s/vibrant-dew-d8hes, https://codesandbox.io/s/brave-sky-qobx8
6. I can see that the React and Vue sandboxes are based on the source sandboxes, but what is the source for the vanilla sandbox (https://codesandbox.io/s/focused-silence-pq0ed)?
7. Why are the first 3 sandboxes (for vanilla, Vue, React) called "Configuration" but the last one (for React, again) is called "PR")? In the issue
8. Is there a possibility to give better names to the 4 sandboxes than "Configuration", "Configuration", "Configuration", "PR"? It is hard to find the source sandboxes for the new sandboxes, especially when there is a few of them.
9. In CodeSandbox UI I can see that there is a tab called "Tests". Could we run our test suite there?
10. Are the builds made by CodeSandbox usable outside of CodeSandbox, for example can I hot link them in my localhost?

**Comment by wojciechczerniak** [comment]
> 1. It does not load for me in Firefox (normal and incognito). Am I alone with that problem?

You're never alone! But it works for me. FF 72.0.1, OS X 10.15.

> 2. It takes 15 seconds to load in Chrome and 25 seconds to load in Edge. This is quite annoying, can anything be done to speed this up?

15 sec on Chrome and Firefox for the first run. Then 3 sec witch cached sandboxes. I'm affraid it's up to them and I think they're doing quite well. Remember that everything has to be download from npm and build with webpack. 

IMO It's still faster than recreating every use case example in JSFiddle with each new build. And would help @aninde and the reviewers a lot.

> 3. In CodeSandbox UI, can I force building any branch name or commit SHA of Handsontable and/or wrappers?

I'm not aware of such a feature. CodeSandbox UI supports already build and published packages. But since CodeSandbox CI already does it for each commit it should be possible with the instructions in an answer to your 10th question.

> 4. If my PR has 50 commits, will CodeSandbox create 50 comments with different sandboxes? I am not saying it is bad, just asking :D I know that redundant comments can be hidden using GitHub UI.

No. It will add only one comment and then update it with new links. Check the comment history for details: https://github.com/handsontable/handsontable/pull/6565#issuecomment-565463738

> 5. Why are there two slightly different sandboxes for React? https://codesandbox.io/s/vibrant-dew-d8hes, https://codesandbox.io/s/brave-sky-qobx8

One is taken from the configuration (see files in this PR) and the second one is taken from the PR comment. I was lazy while creating this PR and made a copy&paste example with a small change. They should be quite different in a real-life use case.

> 6. I can see that the React and Vue sandboxes are based on the source sandboxes, but what is the source for the vanilla sandbox (https://codesandbox.io/s/focused-silence-pq0ed)?

Sources for "Configuration" sandboxes are taken from this repo: https://github.com/handsontable/examples and are configured in ` .codesandbox/ci.json` file in this PR: https://github.com/handsontable/handsontable/pull/6565/files#diff-3a497e46516b2c9e330c20af04452b77

> 7. Why are the first 3 sandboxes (for vanilla, Vue, React) called "Configuration" but the last one (for React, again) is called "PR")? In the issue

"Configuration" sandboxes are taken from the `.codesandbox/ci.json` file and are always run with the CI. Their purpose is to check some generic use cases with each PR, ie. wrappers.

"PR" sandboxes are the ones that bot found in the PR. They are PR specific. Those could be use cases that the developer used to implement/demonstrate the feature or bug fix.

One type is missing in this PR and it's called "Issue". Those are the sandboxes that we're found by the bot in the issue that was mentioned in the PR comment. If there we're a use case scenarios reported there by the user, quality assurance or project manager (among others) within the issue we're fixing in the PR we will be able to verify that the original use case scenario was fixed as well.

> 8. Is there a possibility to give better names to the 4 sandboxes than "Configuration", "Configuration", "Configuration", "PR"? It is hard to find the source sandboxes for the new sandboxes, especially when there is a few of them.

Unfortunately no. It might be a good feature request.

> 9. In CodeSandbox UI I can see that there is a tab called "Tests". Could we run our test suite there?

We would have to add tests to sandboxes in https://github.com/handsontable/examples. It's more for adding additional tests for a particular example than running our tests suite again. The tests we're already run with Codeship CI. 

> 10. Are the builds made by CodeSandbox usable outside of CodeSandbox, for example can I hot link them in my localhost?

Yes. Instructions are available here: https://ci.codesandbox.io/status/handsontable/handsontable/pr/6565/builds/4801

**Comment by aninde** [comment]
My proposal of advanced, but also universal settings:
```
const settings = {
  colHeaders: true,
  rowHeaders: false,
  width: 600,
  height: 500,
  contextMenu: true,
  manualColumnFreeze: true,
  fixedRowsTop: 3,
  fixedColumnsLeft: 3,
  fixedRowsBottom: 3,
  manualColumnMove: true,
  manualColumnResize: true,
  manualRowResize: true,
  manualRomMove: true,
  dropdownMenu: true,
  filters: true,
  columnSorting: true,
  licenseKey: 'non-commercial-and-evaluation',
};
```

**Comment by AMBudnik** [comment]
I would also turn on `comments` they are one of those things people use pretty regularly in Excel.

**Pull request merged**
