### PR TITLE
Fix addClass

### PR DESCRIPTION
**Pull request by zachary822**
Fix bug where if an empty string class name is introduced into an array of
classes, all classes after the empty string will be ignored.

#6367 Pull request to develop branch

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you @zachary822

**Comment by wojciechczerniak** [comment]
Can you create an issue for this @AMBudnik?

**Comment by zachary822** [comment]
Is there is a timeline of when this is going to be incorporated into the master branch?

**Comment by AMBudnik** [comment]
We need to schedule a review soon. If the changes are suitable for the current path we'd like to continue the PR will get merged and pull to a new version of Handsontable.

**Comment by wojciechczerniak** [comment]
Might be already fixed in #6157:

https://github.com/handsontable/handsontable/blob/a858e207e7c780c7fe4df322adfa79e79656a020/src/helpers/dom/element.js#L221-L227

I'm not sure if @warpech had exactly this issue in mind but a test will be useful.

**Comment by zachary822** [comment]
That fixes the `filterEmptyClassNames` function, but the `addClass` would still be broken, because not all branches of `addClass` uses `filterEmptyClassNames`.

**Comment by wojciechczerniak** [comment]
@pnowak Cool. Then I would refactor the second `__addClass` to use the same `filterEmptyClassNames` and we can merge this. @warpech will overwrite the implementation of `filterEmptyClassNames` and we're done

**Comment by warpech** [comment]
Or perhaps you can cherry pick my fix here, and improve it.

**Comment by pnowak** [comment]
Hi @zachary822 

Thank you for your help.
We decided to extend your PR by @warpech approach.
So we'll finish it on a separated branch.

Thanks again :)

**Comment by AMBudnik** [comment]
Hi @zachary822 ,

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Pull request merged**
