### PR TITLE
Prevent clearing portal cache array in StrictMode second render (#9723)

### PR DESCRIPTION
**Pull request by bulaj**
### Context

This PR prevents the issue when custom rendered components are not visible after second render caused by react StrictMode in development mode. I have noticed that if render is forced by StrictMode renderedCellCache and portalCacheArray sizes are not equal and thats how i detect it.
Actual problem is caused by line
```this.portalCacheArray.length = 0;```
Length of the array is modified directly, outside of react's lifecycle and doesnt trigger methods necessary to render components properly.
Unfortunately, i'm not able to write unit test for this, because wrapper uses older version of react, which does not behave in same way as the newest.
 
### How has this been tested?

In demo application from components-comparison repository using reacts StrictMode component in 'all grids' section. Development mode only.
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #9723 
2.
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [x] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by krzysztofspilka** [comment]
@jansiegel is it going to be reviewed?

**Comment by jansiegel** [comment]
> @jansiegel is it going to be reviewed?

Sure, but it was put on hold to finish the React-Docs project and now it's not in the scope of `12.2`.

**Review by jansiegel — CHANGES_REQUESTED** [review]
Also, I can see that the `Code Quality` CI check has failed - could you check what is that before merging?

**Review by warpech — CHANGES_REQUESTED** [review]
I agree with what @jansiegel pointed out, that it is wierd that we don't have a test for this. @bulaj please add test(s). If that's not possible, why is that?

**Comment by warpech** [comment]
> @warpech, maybe we should prepare a CI script that runs the wrapper tests in multiple React versions? This would prevent situations like that from happening in the future.

We definitely can do it any time. We already did that for Angular in https://github.com/handsontable/handsontable/pull/9575, because that PR was a turning point that could, in fact, break older versions. @jansiegel is this PR, in your opinion, such a turning point for the React wrapper?

**Comment by jansiegel** [comment]
> @jansiegel is this PR, in your opinion, such a turning point for the React wrapper?

@warpech If I understand correctly, this problem exists only for the newer versions of React (@bulaj, correct me if I'm wrong). Although I don't think it's extremely severe, I _do_ think it's an good time to address the multi-version testing infrastructure.

**Comment by bulaj** [comment]
> I agree with what @jansiegel pointed out, that it is wierd that we don't have a test for this. @bulaj please add test(s). If that's not possible, why is that?

As stated in PR description, this bug occurs only in react 18 version.

**Comment by warpech** [comment]
To finish up the thought from the above comment: Our tests use React 17, so that's why a problem from React 18 is not reproducible.

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/pull/9731

**Pull request closed without merging**
