### PR TITLE
modifide copyPaste ts file

### PR DESCRIPTION
**Pull request by aoi12012**
### Context

https://handsontable.com/docs/7.1.1/CopyPaste.html
Not accept objects like those listed here
Added definitions to ts file

I'm sorry if it was different from the intended specification
If you are wrong, please tell me how to use it correctly

### How has this been tested?

After defining in ts file
rowsLimit
columnsLimit
pasteMode
Was actually set and executed

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing the PR.

You're right, according to the comments in the code copyPaste can also be an object

> /**
>  * @description
>  * This plugin enables the copy/paste functionality in the Handsontable. The functionality works for API, Context Menu,
>  * using keyboard shortcuts and menu bar from the browser.
>  * Possible values:
>  * * `true` (to enable default options),
>  * * `false` (to disable completely)
>  *
>  * or an object with values:
>  * * `'columnsLimit'` (see {@link CopyPaste#columnsLimit})
>  * * `'rowsLimit'` (see {@link CopyPaste#rowsLimit})
>  * * `'pasteMode'` (see {@link CopyPaste#pasteMode})
>  *
>  * See [the copy/paste demo](https://docs.handsontable.com/demo-copy-paste.html) for examples.
>  *
>  * @example
>  * ```js
>  * // Enables the plugin with default values
>  * copyPaste: true,
>  * // Enables the plugin with custom values
>  * copyPaste: {
>  *   columnsLimit: 25,
>  *   rowsLimit: 50,
>  *   pasteMode: 'shift_down',
>  * },
>  * ```
>  * @class CopyPaste
>  * @plugin CopyPaste
>  */

Can I ask you to sign [our CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)? [Without it, we won't be able to review/merge the changes.](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md)

**Comment by wojciechczerniak** [comment]
I'm not sure it's the correct way to do it. You're assigning plugin class to settings. Other plugins have settings object created for that purpose.

**Comment by AMBudnik** [comment]
Hey @wojciechczerniak 

Yup, we get the test report

```
handsontable.d.ts:1699:27 - error TS2713: Cannot access 'Plugins.CopyPaste' because 'Plugins' is a type, but not a namespace. Did you mean to retrieve the type of the property 'CopyPaste' in 'Plugins' with 'Plugins["CopyPaste"]'?
1699     copyPaste?: boolean | Plugins.CopyPaste;
```

I've already got a confirmation from @pnowak that he'll take a look at it.

**Comment by aoi12012** [comment]
Hay @AMBudnik 
I signed the CLA

**Pull request closed without merging**
