### PR TITLE
Do not allow change height after resize window when hot has a parent

### PR DESCRIPTION
**Pull request by pnowak**
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #3433

### Checklist:

- [ ] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by budnix** [comment]
I've checked PR and found some places which can be improved. I removed all arguments which you added to the renderer as an indication of table hight. Improved how the cloned node is inserted to DOM (now it is placed in the same position as the original element). I found that test which you wrote didn't fail using `develop` branch - it should.

I allowed myself to correct these issues. All the changes are committed. Can I ask you to review my changes and test using your methodology if the table behaves appropriately?

**Comment by pnowak** [comment]
I found one test scenario when your improvement didn't fix - if you have an inline style for the parent element `height: initial` or any without numbers then `parseInt` returns `NaN` and we still have a bug.

**Comment by budnix** [comment]
Thanks for the quick response! You are right. There was a bug when the inline style is used. I've fixed it. Can you check now?

**Comment by pnowak** [comment]
Yes, I checked and everything is ok.

**Pull request merged**
