### PR TITLE
Add lv-LV Latvian-Latvia translation

### PR DESCRIPTION
**Pull request by NullIsNot0**
### Context

Adds Latvian language translation

### How has this been tested?

In my local dev env. Seems quite ok.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Additional language file or change to the existing one (translations)

### Related issue(s):
None

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing the PR @NullIsNot0 
After we get 5 confirmations from the community at https://github.com/handsontable/handsontable/issues/5186 we'll be able to pull the changes :)

**Comment by NullIsNot0** [comment]
I have signed Contributor License Agreement and changed branch.

**Comment by AMBudnik** [comment]
Thank you @NullIsNot0

**Comment by AMBudnik** [comment]
Thank you very much for sharing the translation @NullIsNot0 

it has been added to Handsontable 6.2.0

**Comment by adrianszymanski89** [comment]
Hi @NullIsNot0. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

Here you can find more information about it: https://github.com/handsontable/handsontable/issues/10112

**Pull request merged**
