### PR TITLE
Prevent errors when destroying the underlying Handsontable instance of the wrappers.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR adds the Handsontable's `isDestroyed` check to all of the wrappers, and makes them display a warning if trying to use an already-destroyed instance.

### How has this been tested?
Added test cases for all of the wrappers.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8311 
2. #8165

### Affected project(s):
- [ ] `handsontable`
- [x] `@handsontable/angular`
- [x] `@handsontable/react`
- [x] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by aninde — DISMISSED** [review]
Each of the wrappers builds correctly and the tests are written well for everyone and pass. I have no critical comments. It's 👍  from me.

**Review by budnix — APPROVED** [review]
LGTM 👍

**Review by budnix — APPROVED** [review]

**Review by aninde — APPROVED** [review]
LGTM 👍

**Comment by AMBudnik** [comment]
The changes within this PR probably caused a regression reported at https://github.com/handsontable/handsontable/issues/8664
about missing IF statement causing extending warnings.

reference to a proposed solution
> as in React
https://github.com/handsontable/handsontable/blob/b0a09bde9a9d4164bee4f28cd047fa843f42a7a9/wrappers/react/src/hotTable.tsx#L157-L168

**Pull request merged**
