### PR TITLE
[Context Menu] Allow executing default commands by their key

### PR DESCRIPTION
**Pull request by nicolas-schreiber**
### Context

This change affects the context menu.
It allows to use the default keys of actions like `alignment:right` or `remove_col` with custom menu items to execute these default functions.
The developer can still create an own callback without removing the default behavior.
This is also helpful if you simply want to rename the default options without creating a custom i18n file.

The main changes are in contextMenu.js and commandExecutor.js.
I added a pool of default commands in the commandExecutor.
If the user selects a command, the executor will look in both the registered and the default commands and will execute all that fit the key.

I did not yet create any test-cases, as I am not sure how to do that in this use-case. 
But I plan to add them in a bit. In the meantime I would like your comments.

### How has this been tested?

Like described in issue #3807 use following contextMenu config:
```
items: {
    "alignment": {
         name: 'Alignment',
         submenu: {
             items: [
                 {key: 'alignment:left', name: 'Align to LEFT'},
                 {key: 'alignment:right', name: 'Align to RIGHT'},
             ]
         }
    },
}
```
Now you can test it by clicking `Align to RIGHT` in the context menu.

To further elaborate this problem:
If I have following item in the contextMenu config then It will create a default submenu with all the alignment options and a nice separator with the display name ALG: `'alignment': {name: 'ALG'}`
I can also create other top level options, with submenus that use for example the key `alignment:right`
and it will execute that behavior when selected.
Now as soon as I add a submenu parameter in `alignment` or I am not able to do that anymore, even if I create the submenu item for `alignment:right` myself.
I can also not execute any of the default commands if its default menu option is not present.

I tracked this problem down to the function `getItems` in the `itemsFactory.js` file.
`
if (isObject(value)) {
    extend(item, value);
}
`
Up to this point item contains the default alignment-menu. It is then extended with the custom item defined in the contextMenu config. If that item has a submenu it will entirely overwrite the default functionality.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
(This could basically mean that some people would need to change their keys if they do not want the default behavior)

### Related issue(s):
1. #3807

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @nicolas-schreiber 

Thank you for sharing this pull request.
I can see that you did a lot of work and investigation.

Can I ask you to delete the changes made on files in the `dist `directory? They are made automatically by our scripts are those and the result files of the core + plugins so we do not change them. Additionally, each time we add anything that is not a typo fix we need to add tests to check if te code doesn't break any previous table logic. Please take a moment to check our [Contributor guidelines](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

Also, please [sign the CLA document](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform). Without it we won't be able to merge code that we do not own.

**Comment by nicolas-schreiber** [comment]
Hi @AMBudnik I will do that. 
One question though, I do not really get what I am supposed to enter in the CLA document. The first field wants me to type in a number and there is Antonio Policastro written above it. The other two I expect to be E-Mail and Name, but I think the bottom part of the document is a bit confusing.

**Comment by AMBudnik** [comment]
Sorry, that was an incorrect link. I have replaced it with the correct one

**Comment by nicolas-schreiber** [comment]
@AMBudnik It still says that my name has to be a number. These are some pretty interesting restrictions

**Comment by AMBudnik** [comment]
Can you try again?

I was able to use letters

image

**Comment by nicolas-schreiber** [comment]
@AMBudnik Well, now it worked.

**Comment by AMBudnik** [comment]
Great! Sorry for the inconvenience.

**Comment by nicolas-schreiber** [comment]
@AMBudnik So, I fixed some Issues, and added two tests.

**Comment by AMBudnik** [comment]
Thank you. I can see that all the tests passed.
I am adding the `ready for review` label.

**Comment by AMBudnik** [comment]
Hi @nicolas-schreiber 

Can you check if the PR has all needed changes?

We have tried to build an app with your code and using the following settings for `contextMenu`

```
"alignment": {
            name: 'Alignment',
          submenu: {
            items: [
                {key: 'alignment:left', name: 'Align to LEFT'},
              {key: 'alignment:right', name: 'Align to RIGHT'},
            ]
          }
         },

```
use any of the options but it doesn't do anything. It is build into the full.js file but doesn't seem to fix the issue.

**Comment by nicolas-schreiber** [comment]
Hi @AMBudnik

It should be working now. 
One more lesson learned: "Try your own example code" :)
If I had chosen a different menu key (That is not a default command) it would have worked.
So it was actually good to have this as example

**Comment by AMBudnik** [comment]
Thank you :) we'll check it as soon as possible

**Comment by AMBudnik** [comment]
Can I ask you to check the changes? It looks like there are some conflicts within the files.

**Comment by AMBudnik** [comment]
As there are no updates or changes to the PR (pending conflict) I need to close the PR. If you are still interested in the subject please solve the file conflict.

**Pull request closed without merging**
