### PR TITLE
Fixed bug related to desynchronization of bottom layers position when table's height is set by settings

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

As the title says. According to [discussion on Slack](https://handsoncode.slack.com/archives/C01DAFLSWEA/p1646667938873949?thread_ts=1646667216.931599&cid=C01DAFLSWEA) we don't address alternative approaches, [mentioned in the task](https://github.com/handsontable/handsontable/issues/4454#:~:text=wszymanski-,on%2028%20Jan%202021,-I%20did%20commit).

### How has this been tested?

Manual tests for the use case.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #4454

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by budnix — CHANGES_REQUESTED** [review]
I've checked and it seems that nothing changed. Still I've got doubled rows in the bottom overlay 🤔 
image

**Comment by wszymanski** [comment]
> I've checked and it seems that nothing changed. Still, I've got doubled rows in the bottom overlay 🤔 

Please share more information. I've fixed the first example mentioned by user within the issue. I've checked it once again and even added extra test checks for `fixedBottomRows` > `1` within https://github.com/handsontable/handsontable/pull/9283/commits/418441e6478c006921394815a5ccf8f42a47e472.

My config:

```js
    height: 300,
    rowHeaders: true,
    colHeaders: true,
    fixedRowsBottom: 2,
```

Before (`develop`)

Screenshot 2022-03-14 at 13 18 10

After

Screenshot 2022-03-14 at 13 17 45

**Comment by budnix** [comment]
I've prepared a build using the latest changes and the bottom overlay still appears https://jsfiddle.net/budnix/2f5pujqs/1/. What am I doing wrong? 🤔

**Review by budnix — CHANGES_REQUESTED** [review]
https://github.com/handsontable/handsontable/pull/9283#issuecomment-1074890552

**Comment by wszymanski** [comment]
> ```js
>     height: 300,
>     rowHeaders: true,
>     colHeaders: true,
>     fixedRowsBottom: 2,
> ```

Thank you for that case. It seems that it doesn't work when there is more data (probably above set `height`) and `rowHeaders` option is enabled.

**Review by budnix — APPROVED** [review]
Excellent 👌 🤣

**Comment by wszymanski** [comment]
Thanks for your changes. I'll merge the branch.

**Comment by aninde** [comment]
[e2e case](https://github.com/handsontable/handsontable/pull/9283/files#diff-e5fa72bfb1597f94b801027da397fd41a8bfe6d9dd3081354f453c3f94a3d92c) covers acceptance test.
Manual tests cover each case on the OP issue and [various forms ](https://app.qase.io/project/HOT?view=1&suite=30&case=967) of dependence between Handsontable dimensions and the div while scrolling. Test cases [967](https://app.qase.io/project/HOT?view=1&suite=30&case=967)-[977](https://app.qase.io/project/HOT?view=1&suite=30&case=977), including `rtl`.

**Pull request merged**
