### PR TITLE
Add support for keyboard shortcuts that allows selecting all rows/columns

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR adds support for new keyboard shortcuts that allow selecting the entire rows/columns based on the currently selected cell/cells.

### New keyboard shortcuts
 - <kbd>Ctrl</kbd>+<kbd>Space</kbd> Select columns that holds the currently focused cell/cells

Kapture 2023-06-07 at 10 00 58
 - <kbd>Shift</kbd>+<kbd>Space</kbd> Select rows that holds the currently focused cell/cells

Kapture 2023-06-07 at 10 02 04

And there is a possibility to select all headers and cells when at least one column was selected. The keyboard shortcut that selects all rows extends the selection to the whole table (the same happens with row selection extended by the columns).
Kapture 2023-06-07 at 10 05 31

When non-contiguous selection is applied, only the latest layer is considered to expand to rows/columns. The rest layers are cleared.
Kapture 2023-06-07 at 10 09 27

To make the feature happen, some new APIs needed to be extended, and some new hooks had to be added.

#### The Core API changes (extends the API from the not released PR [#10301](https://github.com/handsontable/handsontable/pull/10301))
 - `selectColumns` allow moving the focus highlight position to any row within the table rows range (the 3rd argument);
 - `selectRows` allow moving the focus highlight position to any column within the table columns range (the 3rd argument);
 - `selectAll` allow moving the focus highlight to any row and column position within the table range (the 3rd argument);

#### New hooks
 - `beforeSelectColumns` Allows modifies the columns selection range that was triggered by a selection API call or a mouse header click; 
 - `afterSelectColumns` Allows doing some things right after the columns selection is applied but before it is rendered on the table;
 - `beforeSelectRows` Allows modifies the rows selection range that was triggered by a selection API call or a mouse header click; 
 - `beforeSelectRows` Allows doing some things right after the rows selection is applied but before it is rendered on the table;

### How has this been tested?

I've tested the code locally using different configurations. All features are covered with new E2E tests.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1083

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by aninde** [comment]
I reported a bug with the focus position of `selectAll`, which was quickly fixed.

Before: 
image
After af9cd792e3b205d59cd74eabcec6d4e18e076d64: 
image

**Comment by aninde** [comment]
After some steps it was possible for me to open context menu and insert row on column headers, which shouldn't be happening.

Open demo https://js-nfbyj7.stackblitz.io/ with version ac51aa99734f2f1cb73a9c361ed9ce90039b8936.
Screenshot 2023-06-13 at 16 53 52

1. Click `Ctrl + Space` to select column 1.
2. Click `Shift + Space` to select All
3. Open context menu on header G.
Result: It's possible to insert row above (before row 1), above *the last row in the table).

**Comment by budnix** [comment]
> After some steps it was possible for me to open context menu and insert row on column headers, which shouldn't be happening.

@aninde I guess, it's not a bug. The same behavior is for the latest 12.4.0 version.
Kapture 2023-06-14 at 08 27 50

**Review by aninde — APPROVED** [review]
> @aninde I guess, it's not a bug. The same behavior is for the latest 12.4.0 version.
@budnix truth.

I made sure it works properly on Chrome 114.0.5735.106, Firefox 114.0.1, Safari 16.5 (18615.2.9.11.4), Microsoft Edge 113.0.1774.42 for macOS 13.4 and Windows 10.

**Review by jansiegel — APPROVED** [review]

**Comment by kirszenbaum** [comment]
Documented in #10402

**Comment by AMBudnik** [comment]
Here's a v14.0.0 demo with all of the four new hooks added https://jsfiddle.net/mns5rjkz/1/
Also the select all rows/columns work well with and without headers.

**Pull request merged**
