### PR TITLE
issue-3381: preventing validation occurring prior to 'beforeChange' (recreating PR #4509)

### PR DESCRIPTION
**Pull request by jdmcnair**
### Context

Issue described in #3381. Validation happens on changes before the potential cancelling of those changes in the `beforeChange` event. This means that the table may sometimes show validation unrelated to the actual data in the table.

These changes were originally proposed in PR #4509, but further modifications were requested, and I'm no longer a member of the surgeforward organization that owns that fork. I've included those original changes, and the requested modifications from PR #4509.

### How has this been tested?

New tests in `Core_validate.spec.js` and manual testing in the UI.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #3381 
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by jdmcnair** [comment]
@AMBudnik @swistach see my final comment on #4509. I was unable to get access to the fork/branch this PR was originally created on because I no longer belong to that organization. Please look over the history of that PR and pick up on those changes here. I've already signed the CLA.

**Comment by AMBudnik** [comment]
Thank you very much for your effort to keep this PR alive and accessible.

**Comment by jdmcnair** [comment]
@swistach it's not totally clear to me what's being shown in the gif above. I see the F5 value being edited, then other cells being selected. What is the expected behavior in this context? Is the problem the fact that the editor is still active even after other cells are selected?

**Comment by swistach** [comment]
Exactly :+1:
New cell selection should close the active editor (except the case, when `allowInvalid` is set as `false`).
Moreover, it's impossible to begin editing any other cell.

**Comment by swistach** [comment]
Hi @jdmcnair, we'll finish this issue internally.
Thank you for your involvement 👍

**Comment by jdmcnair** [comment]
@swistach thanks! Yes, I hadn't had a chance to look into that final bug, so that's great if you guys can finish it out.

**Pull request merged**
