### PR TITLE
#4851 Add auto-align to autocomplete dropdown when space is limited

### PR DESCRIPTION
**Pull request by joelamos**
### Context
This change introduces functionality that aligns the autocomplete dropdown with the right edge of the text area if space to the right of the text area is limited.

### How has this been tested?
This change has received minimal internal testing at my company.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #4851 

### Checklist:
- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hey @joelamos 

thank you for taking the time to investigate this case and create a pull request.

Nevertheless, we won't be able to merge it without your written permission so please sign the [CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1).

Also, that is a bigger change so the tests are needed. Can you prepare them?

**Comment by AMBudnik** [comment]
I need to close this PR as there no CLA for 4 months.
If you'd like us to review it please sign the CLA and leave a comment.

**Comment by joelamos** [comment]
I've signed the CLA

**Comment by AMBudnik** [comment]
Hi @joelamos 

Our developer did a review of the pull request that you've made. And at this point, we cannot merge it as our plans for the fix of the following scenario differ. We would rather keep the consistency between other (non-dropdown) cell types. 

Nevertheless, thank you very for your effort to prepare the pull request. That made us rethink the behavior again and make some notes for the future.

**Pull request closed without merging**
