### PR TITLE
Korean langauge support

### PR DESCRIPTION
**Pull request by kuil09**
### Context
Added Korean language support

### How has this been tested?
N/A

### Types of changes
-[O] Additional language file or change to the existing one (translations)

### Checklist:

- [O] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

This is my first pull request. :) 
You did great work.

### CODE REVIEW

**Comment by AMBudnik** [comment]
I am so happy to see a Korean translation! Thank you @kuil09 👍 

Before we wait for the confirmation from the community (we need 5) can you please 
1. Change the branch to `develop`
2. Change the comment:
```
Authors: Handsoncode << it should be you
 * Last updated: Nov 15, 2017 << date of change
 *
 * Description: Definition file for English - United States language-country. << proper language
```

**Comment by kuil09** [comment]
@AMBudnik OK. I changed comment and branch.
have a nice day.

**Comment by AMBudnik** [comment]
Thank you very much @kuil09 
Have a great day as well.

**Comment by AMBudnik** [comment]
Thank you very much for sharing the translation @kuil09  

it has been added to Handsontable 6.2.0

**Comment by adrianszymanski89** [comment]
Hi @kuil09. We just announced an introduction of a new functionality called `Copy with headers`. Could you help us to translate three short lines for the context menu?

**Pull request merged**
