### PR TITLE
Docs: Update the "Cell functions getters" section

### PR DESCRIPTION
**Pull request by kirszenbaum**
This PR updates the "Cell functions getters" section, fixing [#1504](https://github.com/handsontable/dev-handsontable/issues/1504).

### Updated sections
- http://localhost:8080/docs/javascript-data-grid/cell-function/#cell-functions-getters
- http://localhost:8080/docs/react-data-grid/cell-function/#cell-functions-getters

[skip changelog]

### CODE REVIEW

**Review by AMBudnik — CHANGES_REQUESTED** [review]
Please replace the `undefined` as in the demo https://jsfiddle.net/ez3yh48n/1/ and `numeric` for all of the functions is not enough. I think that we should educate users that something like a Editor, Validator, and Renderer exist and that a cell type has its own set of those functions.

**Comment by AMBudnik** [comment]
@kirszenbaum yes, with changes to https://github.com/handsontable/handsontable/commit/e6d481ca866fa49347906e199e0226a2528a7d53 there's nothing more to add 👍

**Comment by evanSe** [comment]
@AMBudnik if happy with the changes can you approve, I am also happy 😃

**Review by AMBudnik — APPROVED** [review]
👍

**Pull request merged**
