### PR TITLE
let isCommand can be a function

### PR DESCRIPTION
**Pull request by maketubo**
### Context
let isCommand can be a function,and isCommandPassive in menu.js still work properly,even more flexible.

### How has this been tested?
I checkout a feature branch from master and merge into develop, then test in develop branch.(It seems that many commit had't merge into develop so i just apply the change created by me and revert else by other to solve the conflict.) 
Then i created an e2e js file which have one test case to test the menu whether still work properly and pass with script npm run test:e2e.
I am new to JavaScript and working hard on my English:). Pelease let me know if i do something wrong. 
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.#6583
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hey @maketubo 

thank you for signing CLA, the branch is correct but according to the [Contributing guide](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) we cannot change /dist files. Also please add a test that checks the new implementation.

**Comment by maketubo** [comment]
> Hey @maketubo
> 
> thank you for signing CLA, the branch is correct but according to the [Contributing guide](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) we cannot change /dist files. Also please add a test that checks the new implementation.

what do you mean? There is just 2 file change i commit and other  30 commits on 23 Oct are added by pnowak and others.

**Comment by maketubo** [comment]
> Hey @maketubo
> 
> thank you for signing CLA, the branch is correct but according to the [Contributing guide](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) we cannot change /dist files. Also please add a test that checks the new implementation.

should i checkout a branch from develop and commit my changes?

**Comment by AMBudnik** [comment]
You can pass another commit to the `maketubo:feature-commandpassive` branch and it will update or you can create a new pull request.

**Comment by maketubo** [comment]
> You can pass another commit to the `maketubo:feature-commandpassive` branch and it will update or you can create a new pull request.

ok,i think i get your point.By the way, i think it may be a good idea that add /dist path to .gitignore file to limit other to commit  /dist files

**Pull request closed without merging**
