### PR TITLE
Update README.md link to ce-downloads page on external site

### PR DESCRIPTION
**Pull request by Waterdrips**
Link updated to correct CE-Downloads page

### Context

Documentation change - Link is incorrect for ce-downloads page
### How has this been tested?

Following the link from my fork README.md works
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1.
2.
3.

### Checklist:

- [ ] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you @Waterdrips for sharing the PR and for your time to find the proper link

Can you please switch the branch to `develop` and [sign CLA](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) for allow us to merge the PR?

**Comment by Waterdrips** [comment]
Branch changed, and CLA already signed.
Thanks @AMBudnik

**Comment by AMBudnik** [comment]
Great! Thank you

**Comment by AMBudnik** [comment]
Thanks for merging @budnix

**Pull request merged**
