### PR TITLE
Fixes #4304

### LINKED ISSUE #4304: Using wrong row/col indexes for validation
### Description

When using a sorted table with the "allowInvalid" option set to false and validation set for a column, entering an invalid value whilst the physical index for that row is not visible causes an error. The issue is that the line for getting the cell element uses the row and col values from "cellProperties" which is using the physical indexes when it should be using the visual indexes for the "getCell()" method.

The exact code block causing this issue is here: [core.js Line 1038](https://github.com/handsontable/handsontable/blob/33dcdf5bb81cad36b1705ec502eef84b899849c4/src/core.js#L1038)
The exact line is: [core.js Line 1041](https://github.com/handsontable/handsontable/blob/33dcdf5bb81cad36b1705ec502eef84b899849c4/src/core.js#L1041)

So to fix it this line:
```
const cell = instance.getCell(cellProperties.row, cellProperties.col);
```
should become:
```
const cell = instance.getCell(cellProperties.visualRow, cellProperties.visualCol);
```

### Steps to reproduce

1. Disable "allowInvalid" in a table and add validation to a column.
2. Sort the table so that the physical row index matching the visual row index is not visible (null).
3. Enter an invalid value.

### Demo

http://jsfiddle.net/Lp4qn55v/691/
Enter a letter into any cell which will cause validation to fail and an error to occur.

### Your environment
* Handsontable version: 1.10.2
* Browser Name and version: Google Chrome: Version 58.0.3029.110 (64-bit)
* Operating System: Windows 10

### PR DESCRIPTION
**Pull request by jeremy-smith-maco**
### Context

Fixes issue #4304 which is required for our project's use.

### How has this been tested?

Tested them with our project and works as expected (no longer throws exception).

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #4304

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thanks for sharing @jeremy-smith-maco

**Comment by AMBudnik** [comment]
Hi again @jeremy-smith-maco 

could you add some tests, please?

**Comment by jeremy-smith-maco** [comment]
Tests added.

**Comment by jeremy-smith-maco** [comment]
That failing test has nothing to do with this PR so not sure why it is failing.

**Comment by wszymanski** [comment]
Hi, @jeremy-smith-maco. Sorry for the late. The test has passed after the restart. Travis sometimes has got problems with tests which should pass.

Thanks for your contribution. Task description is detailed, fix is really good. Just two propositions after review:

1. I would recommend writing only one test which will recognize if physical indexes were used. For example, you can check if `validateChanges` removed `htInvalid` class from the proper cell after sorting. Your test checking lot of sequences, but I'm afraid one precise test will be enough. Three less test will reduce the time of testing Handsontable :)
2. Tests for this functionality are very old. Please remember about changing two equal signs to three equal signs (ESLint `eqeqeq` rule) if you will copy part of another test. What's more setting `validated` variable can be omitted (ESLint `no-unused-vars`).

Please let me know what you think.

**Comment by jeremy-smith-maco** [comment]
Fixed @wszymanski (hopefully)

**Comment by jeremy-smith-maco** [comment]
*fingers crossed* @wszymanski

**Comment by wszymanski** [comment]
Thank you. It looks good. Every fix in core is important :thumbsup: 

Today we release, but changes for 0.34.2 are already closed. This change must come with 0.34.2/0.35.0 version of Handsontable in line with our release policy so I'll have to ask you for a little more patiens.

**Comment by wszymanski** [comment]
We have done next release with a hot fix. Your change was also released. Thank you for your contribution.

**Pull request merged**
