### PR TITLE
Loosen dependencies

### PR DESCRIPTION
**Pull request by swrobel**
This is the only package I've come across that locks all of its dependencies to specific versions, which is causing me to have to load multiple versions of moment into my app, amongst other things.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @swrobel 

thank you for sharing the code.

Please change the branch for `develop` (we do not merge PR made to `master`) and [sign the CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

**Comment by swrobel** [comment]
@AMBudnik done

**Comment by AMBudnik** [comment]
Thank you @swrobel

**Comment by swrobel** [comment]
@swistach great to hear that your team agrees on this change. I believe my PR is now ready to merge.

**Comment by swrobel** [comment]
@swistach ping!

**Comment by mismith** [comment]
Can we reopen and merge this @swistach / @AMBudnik ?

**Comment by AMBudnik** [comment]
I am reopening the PR.

**Comment by mismith** [comment]
Nice, thanks @AMBudnik!

@swrobel, have a sec fix up those minor conflicts soon?

**Comment by swrobel** [comment]
@AMBudnik changes are made but I think @swistach still needs to approve the review which never happened last time...

**Comment by AMBudnik** [comment]
I have spoken with him and it looks like we're held by the lerna.js that our CTO wants to deploy. I do not know when that will happen, I'm still waiting for the new sprint's task list.

**Comment by swrobel** [comment]
This is twice now you guys have jerked me around fixing a PR that you have no intention to merge. If this needs fixing in the future, please do so yourselves. I do not even use handsontable anymore.

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting, Stefan. 

I had a very long discussion with our CTO, about possible approaches and it looks like even if we do not have learna now it is wiser to do not update the dependencies. 
He posted a comment here https://github.com/handsontable/handsontable/issues/5159#issuecomment-452658054 on that subject. I have to admit that he's more qualified than I in this subject, and despite the fact that I would update the dependencies, I need to stick to his decision.

**Comment by AMBudnik** [comment]
The referenced issue has just been closed as solved https://github.com/handsontable/handsontable/issues/5159

**Pull request closed without merging**
