### PR TITLE
Editor for merged area will be open with proper data when there are hidden rows/columns

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

An editor wasn't opened with proper data.

### How has this been tested?
Manul clicks on the merged cells with hidden columns.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #6872

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by budnix** [comment]
cc @wojciechczerniak https://github.com/handsontable/handsontable/pull/6939#pullrequestreview-419074546.

**Comment by wszymanski** [comment]
> Additionally, I'm a little worried about `modifyGetCellCoords` hook usage. [Docs](https://handsontable.com/docs/7.4.2/Hooks.html#event:modifyGetCellCoords) says that the hook only modifies how the `getCell` method gets the DOM elements. However, after that changes the hook meaning is slightly extended to modifying not only how the DOM elements are grabbed but it intercepts what cell meta-object and source data will be glued with the editor.

Yeah, I'm also concerned with the fact that hook isn't used just in one place. The problem is that it's needed to get both:

- `TD` element and the current selection is the best for getting it from `hightlight` value of the `SelectedRange` (it's not equal to the start of merge area when the merged area starts with the hidden column). We can't get `TD` element (for example by `getCell` method) for the hidden column as it returns `null` by design.
- data related to the start of the merge area (start point maybe not equal to the current highlight).

I have no idea how to change it. I've considered also using two hooks - one returning renderable coordinates and another for returning just the visual start of the merge area, but it doesn't sound the best.

I'm open to any feedback and suggestions.

**Comment by wszymanski** [comment]
@budnix I will fix problems found by you within https://github.com/handsontable/handsontable/issues/6878.

**Comment by budnix** [comment]
I was thinking about the hook and there should be introduced a new hook - in this case, a replacement for `modifyGetCellCoords `. I'd call it `modifyEditorCoordsPoint` (`modifyEditorPointer`) or similar? The hook allows the forwarding editor's value and the cell properties from another cell. 

It can be an interesting feature to change editor type or other properties by pointing to another cell. However, does it have any benefit for the user? I can't imagine that right now.

@wojciechczerniak

**Comment by wszymanski** [comment]
I will do some changes, discussed at a meeting.

**Comment by wszymanski** [comment]
Should be changed within https://github.com/handsontable/handsontable/pull/6939/commits/1f5ffc6f8428e5e310dedb22ff3c872334eddfb2.

**Pull request merged**
