### PR TITLE
Fix "TypeError: Converting circular structure to JSON" when passing `hyperformulaInstance` to `hotSettings`

### LINKED ISSUE #8728: [9.0.0+] Adding HyperFormula leads to "TypeError: Converting circular structure to JSON"
### Description
When the HyperFormula instance is added to the settings of a hot-table component, a warning from Vue is emitted about a circular JSON structure:

```
[Vue warn]: Error in getter for watcher "mergedHotSettings": "TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'DependencyGraph'
    |     property 'lazilyTransformingAstService' -> object with constructor 'LazilyTransformingAstService'
    |     property 'undoRedo' -> object with constructor 'UndoRedo'
    |     property 'operations' -> object with constructor 'Operations'
    --- property 'dependencyGraph' closes the circle"

found in

---> <HotTable>
```

### Steps to reproduce
See jsfiddle

### Demo
Clicking "Run" hangs the browser for a while until it errors out. https://jsfiddle.net/z3568ovc/ The problem is the same but the error message is different because Vue is not running with development mode on in jsfiddle.

```
<a class='gotoLine' href='#"[Vue warn'>"[Vue warn</a>: You may have an infinite update loop in watcher with expression \&quot;settings\&quot;

found in

---&gt; &lt;HotTable&gt; at src/common/HotTable.vue
       &lt;Root&gt;"]
```

### Your environment
* Vue wrapper version: 9.0.2
* Handsontable version: 9.0.2
* Browser Name and version: Google Chrome Version 93.0.4577.82 (Official Build) (64-bit)
* Operating System: Windows 10 Pro Version 2004 (OS Build 19041.1237)

### PR DESCRIPTION
**Pull request by tonextone**
### Context

Fixes the issue https://github.com/handsontable/handsontable/issues/8728#issuecomment-1148825594 .

For `JSON.stringify()` is used to compare `hotSettings` (current ⇔ new) ,
any circular structure ( like `hyperformulaInstance` ) within `hotSettings`
causes this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

### How has this been tested?

Added a test case.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):

1. Fix #8728 

### Affected project(s):

- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [x] `@handsontable/vue`
- [x] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you very much for creating the pull request and adding the test scenario.

Could I also ask you to sign our CLA? Without the signature, we do not have permission to merge your changes.

**Comment by AMBudnik** [comment]
Thank you very much for creating the pull request, signing CLA, and adding the test scenario.
I am adding the `ready for review` label. We will proceed with the code review as soon as possible.

**Comment by 171h** [comment]
why not merge? I have the same problem.

cc: @kirszenbaum @AMBudnik 

```
@handsontable_vue3.js:127  Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Rule2'
    |     property 'definition' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Alternation2'
    |     ...
    |     index 1 -> object with constructor 'NonTerminal2'
    --- property 'referencedRule' closes the circle
    at JSON.stringify (<anonymous>)
    at simpleEqual (@handsontable_vue3.js:127:15)
    at prepareSettings (@handsontable_vue3.js:115:128)
    at Proxy.handler (@handsontable_vue3.js:141:24)
    at callWithErrorHandling (chunk-J7TRJLPB.js:213:18)
    at callWithAsyncErrorHandling (chunk-J7TRJLPB.js:221:17)
    at job (chunk-J7TRJLPB.js:1810:9)
    at callWithErrorHandling (chunk-J7TRJLPB.js:213:32)
    at flushJobs (chunk-J7TRJLPB.js:411:9)
    at flushJobs (chunk-J7TRJLPB.js:421:7)
```

**Comment by budnix** [comment]
@tonextone Can I ask you to add a changelog file? You can generate that by running `npm run changelog entry` in the project's root dir. Then, I'll be able to merge the PR.

**Comment by tonextone** [comment]
@budnix Thank you for the follow-up. I just added a changelog entry.

( It's my first time, so I'm not sure if it's perfect. )

**Comment by AMBudnik** [comment]
Thank you again for your contribution @tonextone 
The changes are published.

**Pull request merged**
