### PR TITLE
Optimization for minSpareRows, minSpareCols, minRows and minCols options reducing time of initialization

### PR DESCRIPTION
**Pull request by wszymanski**
### Context
A report from a user showed that Handsontable `8.0.0` is much slower while creating a dataset with a lot of spare rows (created by `minSpareRows` option). I've confirmed that this version is almost `3 times slower` than Handsontable `7.4.2`.

I've optimized the way how those rows are created. ~~I've used also `batch` method implemented within #7274 issue.~~ Performance tests (measured time for initialization of Handsontable) shows that the current version, with changes, is about `8%` faster than Handsontable `7.4.2`.

After changing the way how spare rows are created a bug has become apparent. Thus, there was a need to fix it.

### CODE REVIEW

**Review by Siemienik — COMMENTED** [review]
Great job @wszymanski, it looks good to me. 🚀 I've also tested it manually in code sandbox, where I tested many combinations of minSpare and min cols and rows. It works perfectly. I'm going to check the performance increase yet.

Before merging, please verify why Angular sandbox doesn't work:

https://codesandbox.io/s/handsontableexamples-pull-request-g0ubu

If it is a problem out of this PR scope and will be fixed in another Issue/PR, I will approve this PR.

**Comment by wszymanski** [comment]
> Great job @wszymanski, it looks good to me. 🚀 I've also tested it manually in code sandbox, where I tested many combinations of minSpare and min cols and rows. It works perfectly. I'm going to check the performance increase yet.

Thanks!

> Before merging, please verify why Angular sandbox doesn't work:
> 
> [codesandbox.io/s/handsontableexamples-pull-request-g0ubu](https://codesandbox.io/s/handsontableexamples-pull-request-g0ubu)
> 
> If it is a problem out of this PR scope and will be fixed in another Issue/PR, I will approve this PR.

It seems to be more general problem 🙂

**Comment by wojciechczerniak** [comment]
CodeSandbox was fixed on the old wrapper version that worked only for v7. Should be fixed for the next commit

**Review by Siemienik — APPROVED** [review]
LGTM🥇!Thank you for checking the sandbox and confirm that the performance increase was achieved 😃 

I have one additional proposal for increasing performance a little more (which shouldn't be done in this PR). The `adjustRowsAndCols` might be split into two function. Then `alter('remove_row',...)` and `alter('remove_col',...)` might call suitable function. That makes some saving operations because `remove_row` does not need to calculate empty columns.

**Pull request merged**
