### PR TITLE
Update Latvian language translation

### PR DESCRIPTION
**Pull request by NullIsNot0**
### Context
Add new strings translation for Latvian language in context of #10112.
Update existing translations to better express actions.

[skip changelog]

### How has this been tested?
Not tested yet. Waiting on #10093.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #5183
2. #10112
3. #10093

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by adrianszymanski89** [comment]
Hi @NullIsNot0

Thank you for the translation. In the meantime, we made some changes to the specification. The current version looks like this:

- Copy with header
- Copy with headers
- Copy with group headers
- Copy header only
- Copy headers only

In cases where there is the singular and plural form, it should be done as an `array`, like here:

https://github.com/handsontable/handsontable/blob/feature/issue-2288/handsontable/src/i18n/languages/en-US.js#L52-L54

If you could update your PR, that would be great :)

**Comment by NullIsNot0** [comment]
Hi, @adrianszymanski89 !
I have updated translation to reflect new changes.

**Comment by adrianszymanski89** [comment]
Hi @NullIsNot0 

Thank you very much!

**Comment by adrianszymanski89** [comment]
Closed as PR is already merged here: https://github.com/handsontable/handsontable/pull/10141

**Pull request closed without merging**
