### PR TITLE
Add support for new keyboard shortcut that allows scrolling the viewport

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR adds support for a new keyboard shortcut that allows scrolling the table viewport to the focused cell.

### Expected working new keyboard shortcuts
 - <kbd>Cmd/Ctrl</kbd>+<kbd>Backspace</kbd> Scroll the table viewport to the focused cell. The viewport is always scrolled to the cell in a way that it's positioned right in the middle of the table.

Viewport scroll to the focused cell:
Kapture 2023-06-20 at 15 06 13

When the column header is focused, the viewport is only scrolled horizontally, keeping the scroll Y position untouched:
Kapture 2023-06-20 at 15 08 30

When the row header is focused, the viewport is only scrolled vertically, keeping the scroll X position untouched:
Kapture 2023-06-20 at 15 09 44

When the corner is selected, the keyboard shortcut is inactive:
Kapture 2023-06-20 at 15 10 43

### How has this been tested?

I tested the changes locally, and I covered the feature with new E2E tests.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1371

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by budnix** [comment]
@kirszenbaum, and here is another keyboard shortcut that needs to be added to https://github.com/handsontable/handsontable/pull/10402.

**Review by aninde — CHANGES_REQUESTED** [review]
I confirm that the shortcut works fine on windows and macOs, however I was able to find a case where it doesn't work.

When Handsontable has declared height: 'auto' shortcut doesn't work for vertical scroll, see demo: https://jsfiddle.net/aninde/yw9fts8b/show, [config](https://jsfiddle.net/aninde/yw9fts8b/)

For comparision,  check out a working demo with height: '100%" https://jsfiddle.net/aninde/ahsktw2p/show, [config](https://jsfiddle.net/aninde/ahsktw2p/)

Tested with be250b6376c607feb2a7d2f350cea3fd8530c98f [version](https://www.npmjs.com/package/handsontable/v/0.0.0-next-be250b6-20230621).

**Comment by budnix** [comment]
> When Handsontable has declared height: 'auto' shortcut doesn't work for vertical scroll, see demo: https://jsfiddle.net/aninde/yw9fts8b/show, [config](https://jsfiddle.net/aninde/yw9fts8b/)

Thanks for testing. After investigation, I can confirm that this issue is out of the PR's scope. The bug occurs in the latest version as well. When `height: 'auto'` is used (https://jsfiddle.net/b41teqn0/) or `preventOverflow` is enabled (https://jsfiddle.net/2o9zk806/) the simple cell navigation does not work. The scroll position is not changing when the cell goes out of the table's viewport. It works ok, for example, when `renderAllRows` is enabled (https://jsfiddle.net/2o9zk806/).

**Review by aninde — APPROVED** [review]

**Review by wszymanski — APPROVED** [review]

**Comment by kirszenbaum** [comment]
Documented in #10402

**Comment by AMBudnik** [comment]
The shortcut works excellent for any element cell/header in v14.0.0 https://jsfiddle.net/mns5rjkz/8/

**Pull request merged**
