### PR TITLE
Add a new "BigExample" preview to the Hello World page

### PR DESCRIPTION
**Pull request by warpech**
### Context

This example adds a demo previewer to Vuepress, that is a copy of the demo previewer on our product website: https://handsontable.com/demo

In Vuepress, it looks like this:

Screenshot 2022-01-28 at 18 41 38

The screenshot and this PR now contain `basic-example` instead of the actual Demo, which requires #9160 to be merged first.

### How has this been tested?

Locally with `npm run docs:start`

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/8980 (first checkbox in the OP)
2. https://github.com/handsontable/handsontable/issues/8980#issuecomment-993697293 (points 6 from my comment)
3.

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

[skip changelog]

### CODE REVIEW

**Review by jansiegel — APPROVED** [review]

**Comment by warpech** [comment]
I additionally tested it by running `npm run docs:version`. The source references in to the BigExample were successfully replaced (from `/next/` to `/<version/`)

**Review by kirszenbaum — DISMISSED** [review]

**Comment by warpech** [comment]
Waiting for https://github.com/handsontable/handsontable/pull/9179

**Comment by warpech** [comment]
#9179 is now merged, but there are still problems with the deployment of the examples - now tracked in #9182. Until #9182 is fixed, the `iframes` in the demo will show a 404. Still, I think that this PR can be reviewed and merged, because solving #9182 is totally independent of this PR.

**Comment by warpech** [comment]
Merging as it was already approved by @kirszenbaum yesterday.

**Pull request merged**
