### PR TITLE
Add support for keyboard shortcut that allows clearing the filters

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR adds support for a new keyboard shortcut that allows clearing the state of the filters. The shortcut is active only when the _Filters_ plugin is enabled.

### Expected working new keyboard shortcuts
 - <kbd>Alt/Option</kbd></kbd>+<kbd>A</kbd> Clears the filters from all columns. The shortcut is active for the whole table. There is not necessary to select a column or a cell to clear the states. Clearing the states should keep the position of the current selection the same.

Kapture 2023-06-21 at 10 36 12

### How has this been tested?

I tested the changes locally, and I covered the feature with new E2E tests.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1374

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by budnix** [comment]
@kirszenbaum, and here is another keyboard shortcut that needs to be added to https://github.com/handsontable/handsontable/pull/10402.

**Review by wszymanski — APPROVED** [review]
Works as desired 👌

**Review by aninde — APPROVED** [review]
Works like charm on Windows 10 and MacOS Browser. Tested on Edge, Chrome, FF i Safari.

**Comment by AMBudnik** [comment]
Works well in v14.0.0 https://jsfiddle.net/mns5rjkz/11/ (including many columns)

**Pull request merged**
