### PR TITLE
GH Actions - auto deployment versioned code examples

### PR DESCRIPTION
**Pull request by Osky772**
This PR is based on #7588 

Any change made in versioned examples (like examples/8.3.2, examples/8.1.0, etc.) will trigger GH Actions to build and deploy modified examples folders.

Note: GH Action will be triggered when **ANY** change is made to the versioned examples, including removing some versioned examples.

To prevent CI from creating examples that have been removed, write "[skip ci]" to the commit message. If the "[skip ci]" is found in a commit message, CI won't be triggered. Pull request to the Handsontable is merged using the squash, so you can write "[skip ci]" in the squash commit message.

### CODE REVIEW

**Review by aninde — APPROVED** [review]
I will leave you to check if it works because I do not see anything business here at this stage. @Osky772  thank you very much for the comments in the code, they make it easier to understand :)

**Comment by jansiegel** [comment]
@warpech Is this PR something we still want (deploying the examples as they are to gh-pages)?

**Comment by warpech** [comment]
Definitely yes! Is there anything tricky/discussable about this? Why was it not finished in the first place?

It is a good timing, because I it would solve point 4 from https://github.com/handsontable/handsontable/issues/8980#issuecomment-993697293.

**Comment by jansiegel** [comment]
> Why was it not finished in the first place?

I think it slipped through the cracks as the task priorities changed over time. I'll take a look if it needs updating.

**Review by aninde — APPROVED** [review]
I repeat my previous comment so as not to suspend the merge.
https://github.com/handsontable/handsontable/pull/7661#pullrequestreview-634335699

**Comment by jansiegel** [comment]
Continued in #9058.

**Pull request closed without merging**
