### PR TITLE
Handling undo/redo actions using HF's UndoRedo mechanism #8078

### PR DESCRIPTION
**Pull request by wszymanski**
### Context

It seems that actions done by `UndoRedo` plugin doesn't work well when we reduce sheet size used for calculations. This PR realise idea to transfer responsibility for undo and redo actions on data (stack of changes performed on the table is still tracked by `UndoRedo` plugin) to `HyperFormula` engine.

[Source issue](https://github.com/handsontable/handsontable/issues/8078) provided case which shows that current code isn't prepared for `UndoRedo` when there was a row removal. So far, the `Formula` plugin has handled it by providing own component. Parts of a workaround were placed both in `UndoRedo` and `Formulas` plugin.

https://github.com/handsontable/handsontable/blob/5ec680c6315d6f0cc35926807fc77a81b098a1e7/src/plugins/formulas/formulas.js#L14
After removing `restore` call from the below code (5ec680c6315d6f0cc35926807fc77a81b098a1e7 commit) we can get exactly the same result as described within #8078.
https://github.com/handsontable/handsontable/blob/5ec680c6315d6f0cc35926807fc77a81b098a1e7/src/plugins/formulas/formulas.js#L302-L304
https://github.com/handsontable/handsontable/blob/5ec680c6315d6f0cc35926807fc77a81b098a1e7/src/plugins/undoRedo/undoRedo.js#L459-L460
https://github.com/handsontable/handsontable/blob/5ec680c6315d6f0cc35926807fc77a81b098a1e7/src/plugins/undoRedo/undoRedo.js#L471

This PR tries to provide suggestion mentioned within https://github.com/handsontable/handsontable/issues/7652.

> Consider using [HyperFormula's native undo/redo](https://handsontable.github.io/hyperformula/guide/undo-redo.html) (somehow).

It may be the best solution for not creating workarounds. Please keep in mind that code without changes have also problem with littering `UndoRedo` stack of `HyperFormula` engine. Look below to see the difference.

#### Before change

Screenshot 2021-05-28 at 15 47 54

#### After change

Screenshot 2021-05-28 at 15 37 20

Note: Please keep in mind that stack of the `UndoRedo` should be checked also. You can log it by checking `hot.undoRedo.doneActions` and `hot.undoRedo.undoneActions` variables.

What's more, @jansiegel has mentioned important case. Changes should be handled by the `UndoRedo` **also when formulas plugin is disabled**.

This PR removes also unnecessary, "private" (used just as workaround), last argument for the `afterAutofill` hook (`hasFillDataChanged` parameter).

### How has this been tested?

Manual tests of `UndoRedo` functionality.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #8078

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Review by aninde — CHANGES_REQUESTED** [review]
I was able to found a regression in this build. 
After few autofill operation, the first autofill operation can't be undone.

Demo from [this version](https://github.com/handsontable/handsontable/pull/8129/#issuecomment-850434760) https://codesandbox.io/s/vanilla-handsontable-pr-forked-iqf19
Comparing to v9.0.0 where this working https://jsfiddle.net/aninde/6scxy4na/

**Broken this version**
this

**Working v9.0.0** 
v9 0 0

**Steps to reproduction:**
- at least two autofills on different cells 
1. Select cell A1.
2. Autofill down 1 cell.
3. Autofill right.
4. Select another cell.
5. Autofill right.
6. Undo three times to restore the initial state.

**Expected result:**
Initial state is restored
Screenshot 2021-05-28 at 17 22 27

**Comment by wszymanski** [comment]
Commit 60594b560422f9992ff6a47a8033a9c2775187ef is waiting for HyperFormula 1.0 release. There are 2 developed PR's in the project which are needed for `UndoRedo`: https://github.com/handsontable/hyperformula/pull/678, https://github.com/handsontable/hyperformula/pull/687. The code should be tested after release.

**Comment by wszymanski** [comment]
I've found another regression. While using `cmd`+`z` we can see wrong data.

Was (Handsontable 8.4.0):

https://user-images.githubusercontent.com/141330/133645435-3669c286-ced7-43e7-bee5-8992067cf97b.mp4

Is:

https://user-images.githubusercontent.com/141330/133645516-138db245-26d1-4927-ad0e-963fc5499939.mp4


https://user-images.githubusercontent.com/141330/133645535-45f8f96e-53f4-41d4-bba9-7c70808ccd92.mp4

**Comment by wszymanski** [comment]
There is another regression.

https://user-images.githubusercontent.com/141330/133796726-5e0f5f17-7212-4170-9553-d2c1a6ce5aa6.mp4

**Comment by wszymanski** [comment]
@aninde @jansiegel I've fixed all problems. Please do CR and tests 🙂

**Review by jansiegel — APPROVED** [review]
Looks good to me 👍 

(you can remove `[skip changelog]` from the description)

**Comment by wszymanski** [comment]
> (you can remove `[skip changelog]` from the description)

Done 🙂

**Review by aninde — APPROVED** [review]
Well done 👏  Thank you for the repair and for finding the regression that I missed. The tests are good.  I couldn't find new regressions in this build 🏅

Fixed demos:
1st regression https://jsfiddle.net/aninde/6scxy4na/
2nd regression https://jsfiddle.net/5f0sozum/

**Pull request merged**
