### PR TITLE
fix Context.getShortcuts type

### PR DESCRIPTION
**Pull request by fanshi1028**
### Context
fix outdated type

### How has this been tested?
Nope

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Affected project(s):
- [x] `handsontable`
- [ ] `@handsontable/angular`
- [ ] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by adrianszymanski89** [comment]
Hi @fanshi1028 

Thank you for your contribution! We will review your PR and update you when we check if we are able to merge it.

**Comment by fanshi1028** [comment]
> Hi @fanshi1028
> 
> Thank you for your contribution! We will review your PR and update you when we check if we can merge it.
> 
> Before that, please add a changelog entry and tests for the new type. Thank you.

Added a changelog but I don't know where/what to add tests for this fix.

**Comment by AMBudnik** [comment]
Hi @fanshi1028 

It seems that you can add it here https://github.com/handsontable/handsontable/blob/develop/handsontable/src/shortcuts/__tests__/shortcutManager.types.ts

**Review by evanSe — APPROVED** [review]

**Comment by AMBudnik** [comment]
Thank you again for your feedback and pull request @fanshi1028 

The code was merged to v14.4.0

**Pull request merged**
