### PR TITLE
Modify the freezing script to generate the docs directories.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
This PR:
- Adds a documentation generation logic to the freezing script.
- Modifies the documentation generation script to allow passing the version number as an argument.

<sup>[skip changelog]</sup>

### How has this been tested?
Did a faux freeze to check if the version-based docs directories get generated.

### Types of changes

- [x] Internal change

### Related issue(s):
1. #9046 

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by Siemienik — CHANGES_REQUESTED** [review]
Hi @jansiegel, It's amazing to review that.

I've checked it out and I see, that there is a little problem. The `semver.valid()` returns `null`(invalid) for versions without patch number (like `123.40`). It requires to provide all major, minor, and patch:
image

This makes, that the script doesn't work for our assumes, because we're maintaining the docs without patch number. Would you like to find a way to fix that, please?

Once again, many thanks for the improvement. It's quite important I think.

**Comment by jansiegel** [comment]
> Hi @jansiegel, It's amazing to review that.
> 
> I've checked it out and I see, that there is a little problem. The`sever.valid()` returns `null`(invalid) for versions without patch number (like `123.40`). It requires to provide all major, minor, and patch
> 
> This makes, that the script doesn't work for our assumes, because we're maintaining the docs without patch number. Would you like to find a way to fix that, please?
> 
> Once again, many thanks for the improvement. It's quite important I think.

True, I assumed the cli-based approach would be used only with the freezing script, but it should be more lenient when it comes to the provided version numbers.
Corrected in https://github.com/handsontable/handsontable/pull/9047/commits/4bce2f375dec7196b753e43f656adaacf0b1656d.

**Review by Siemienik — APPROVED** [review]
LGTM! Thanks

**Review by Siemienik — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
