### PR TITLE
Stabilize the tests by hiding Jasmine's test dot reports

### LINKED ISSUE #9960: Failing e2e tests on Chrome, but pass in the IDE console
### Description

Some e2e don't pass on the latest Chrome, but they pass in the IDE console. Details in the [team discussion](https://handsoncode.slack.com/archives/C4PV4S33Q/p1664359782373789?thread_ts=1664293713.074289&cid=C4PV4S33Q).

[Comments](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling) > [using configuration object: {"htmlDir":"ltr","layoutDirection":"inherit"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60) > [should display the comment editor on the left of the cell when on the right there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60%20should%20display%20the%20comment%20editor%20on%20the%20left%20of%20the%20cell%20when%20on%20the%20right%20there%20is%20no%20left%20space)
Expected 2531 to be close to 2599, 0.
Error: Expected 2531 to be close to 2599, 0. at at _callee4$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:122643:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)
[Comments](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling) > [using configuration object: {"htmlDir":"rtl","layoutDirection":"ltr"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22ltr%22%7D%60) > [should display the comment editor on the left of the cell when on the right there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20Styling%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22ltr%22%7D%60%20should%20display%20the%20comment%20editor%20on%20the%20left%20of%20the%20cell%20when%20on%20the%20right%20there%20is%20no%20left%20space)
Expected 2531 to be close to 2599, 0.
Error: Expected 2531 to be close to 2599, 0. at at _callee4$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:122643:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)
[Comments (RTL mode)](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)) > [using configuration object: {"htmlDir":"rtl","layoutDirection":"inherit"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60%20Styling) > [should display the comment editor on the right of the cell when on the left there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22rtl%22%2C%22layoutDirection%22%3A%22inherit%22%7D%60%20Styling%20should%20display%20the%20comment%20editor%20on%20the%20right%20of%20the%20cell%20when%20on%20the%20left%20there%20is%20no%20left%20space)
Expected 2531 to be close to 2599, 0.
Error: Expected 2531 to be close to 2599, 0. at at _callee3$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:124128:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)
[Comments (RTL mode)](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)) > [using configuration object: {"htmlDir":"ltr","layoutDirection":"rtl"}](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22rtl%22%7D%60) > [Styling](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22rtl%22%7D%60%20Styling) > [should display the comment editor on the right of the cell when on the left there is no left space](http://10.0.0.5:5000/handsontable/test/E2ERunner?spec=Comments%20(RTL%20mode)%20using%20configuration%20object%3A%20%60%7B%22htmlDir%22%3A%22ltr%22%2C%22layoutDirection%22%3A%22rtl%22%7D%60%20Styling%20should%20display%20the%20comment%20editor%20on%20the%20right%20of%20the%20cell%20when%20on%20the%20left%20there%20is%20no%20left%20space)
Expected 2546 to be close to 2614, 0.
Error: Expected 2546 to be close to 2614, 0. at at _callee3$ (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:124128:42) at tryCatch (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27092:17) at Generator._invoke (http://10.0.0.5:5000/handsontable/test/dist/e2e.entry.js:27072:24)

Extracted from the https://github.com/handsontable/dev-handsontable/issues/326.

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 12.1.3
* Browser name and version: Chrome 105.0.5195.125 (Official Build) (x86_64)
* Operating system: macOS and Windows 10

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR stabilizes the tests by hiding Jasmine's test dot reports. After running the tests using the Chrome headless (CLI), Chrome, FF, and Safari I've found 3 tests that need to be adjusted/updated:
 1. [_ManualRowMove_](https://github.com/handsontable/handsontable/pull/10090/files#diff-8245911eda76d04cf90f14949235166360076f3b23baac4a694519b373f0c36dR808) test started reporting fails. The test is reviewed and fixed by using a more stable API;
 2. [_Walkontable Table_](https://github.com/handsontable/handsontable/pull/10090/files#diff-d95f87fce66c53ff3f8f89b9e69736f5ef9f2596894b324e865ff887629ebfadR141) test fails on the browser (not in the CLI) 🤔  It turned out that one expectation is wrong. Since the [Walkontable refactors](https://github.com/handsontable/handsontable/pull/9005) the `bottomInlineStartCornerOverlay` overlay is always created;
 3. [_NestedHeaders_](https://github.com/handsontable/handsontable/pull/10090/files#diff-ca95e8f246d20763bb146012951991bed5cfff4a011e94fe3fa978f65299f70eR643) there is a missing `render` call. Without that, the table scroll was incomplete, which caused the failure.
 4. After hiding the Jasmine dots, the _Comments_ (mentioned by issue #9960) tests pass. 

@jansiegel's updates: https://github.com/handsontable/handsontable/pull/10090#issuecomment-1313965383

_[skip changelog]_

### How has this been tested?

I tested the changes locally on different browsers (Chrome, FF, Safari). All tests pass on Chrome. On FF (106), there were and still are 6 failures (not related to the issue). On Safari (16.1), there were and still are 21 failures (not related to the issue).

I run the tests using the bigger viewport. Something like 1260px width and ~1200px height on the screen with DPI = 1 (non-retina).

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Related issue(s):
1. fixes #9960 

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)

### CODE REVIEW

**Review by wszymanski — APPROVED** [review]
I don' think that there is an alternative for removing dots. However, it's wort to mention that our habit to see dots in browser between tests will change.

I'm not sure whether not passing tests according to some viewport size is good. Is there any alternative? So far, I have been using MacBook Pro with 15" Retina and two external 1920x1200 displays. I think that tests have been passing on maximized Chrome. From some time, I'm using MacBook Pro with 16" Retina screen and the same monitors. On macOS 13, Chrome 107, 8 tests are not passing on current branch - four from `BaseEditor API` and four already described within https://github.com/handsontable/handsontable/issues/9960.

Generally, I think that there are positive changes, but I'm not sure whether it is everything which we can do with tests. I have a request that you, @jansiegel, have a look at it. I'm giving 🟢 , but please wait for @jansiegel feedback, yet.

**Comment by jansiegel** [comment]
I'm reassigning this PR to me, as @budnix is currently busy working on #2288.
I also removed myself from the reviewers list, obviously.

**Comment by jansiegel** [comment]
Updates after @budnix's changes:

1. I resolved the remaining failing tests:
    - Those related to the Comments plugin turned out to be caused by a bug in the Comments plugin itself.
    The fact that the direction of the comments box depends on the amount of free space below/next to the table caused different issues on different window sizes:
        - On the smaller windows, the `licenseKey` warning DOM element was higher in size than on larger windows (because it was broken into multiple lines). This influenced the plugin's calculations and gave different results.
        - After resolving that issue by adding `licenseKey` to the test cases, I noticed that the comment box direction can also be influenced by its previous position. As it's rendered before being assigned the correct position, it sometimes "pushed" the bottom of the page down, forcing Handsontable to render the comment box downwards, when it should in fact be rendered upwards. [I resolved this problem by resetting the box's position to (0,0) before each use.](https://github.com/handsontable/handsontable/pull/10090/files#diff-862c2b234f3f48b084fa06efe037f2b1b642e8490796841ba31f07cda117df67R453-R455)
    - Some specs of `BaseEditor` were failing on windows wider then `1775px`. 
      After some research, I found that the spreader element varied in width by `1px` because of `AutoColumnSize` worked slightly differently when the spec was run on a smaller window (the columns did not have their widths calculated initially) than on a larger window (the columns were calculated, and in that very spec the calculations were off by `1px`). As the problem did not apply directly to the specs in question, I disabled `AutoColumnSize` for them.
2. After a suggestion from @budnix, I modified the Handsontable-initializing helper for the test cases, forcing it to use `licenseKey` for every Handsontable instance. This standarizes the way specs should be written and removes room for mistakes like the ones described in 1).
  For test cases requiring the `licenseKey` to be passed differently, I added a second argument to the `handsontable()` function, allowing it to pass the HOT options explicitly - used in `licenseKey.spec.js`.
3. I implemented a progress bar for the tests running in the browser.
  After this change, `E2ERunner.html` will contain a 5px-high bar that will fill up along with each finished test case. 
    - If a test case is skipped/pending or fails, it will be marked on the progress bar as a lighter color (pending) or red (failed). 
    - Clicking on the failed/pending mark on the progress bar will open a page with the problematic test case in isolation. Hovering over it will give you the name of the failed/pending test.
    - Additionally, the number of failing test cases will be displayed in a box on the top-right side of the page and more information on the failed specs will be logged in the browser's console.
  
  Initially, I planned to place the bar on the bottom of the page, but as the test cases sometimes made the horizontal scrollbar appear, which caused some jumping/flickering of the progress bar, I moved it to the top.

**Comment by jansiegel** [comment]
As @wszymanski's not available, @budnix,  could you review my changes? I can't add you as a reviewer because you're the original author of the PR 😆.

**Comment by budnix** [comment]
@jansiegel Everything looks good, but I'd stick to the Jasmine color palette. For us as well as for contributors, it is easier to follow the states represented by 🚥 than our custom palette. WDYT?

Current:
Zrzut ekranu 2022-11-15 o 08 10 47
T?

Suggestion: 
Zrzut ekranu 2022-11-15 o 08 12 41

I set the background color to the progress bar element as `#007069` (Jasmine success).

**Comment by budnix** [comment]
@aninde PR is marked as ready to review. Can you check if the _Comments_ tests pass on your machine?

**Comment by jansiegel** [comment]
> I'd stick to the Jasmine color palette.

Makes sense, I was trying to go more with the Handsontable theme, but you're probably right 👍

**Comment by budnix** [comment]
@jansiegel I accepting the PR. Everything looks good 👍 Thanks!

**Review by aninde — APPROVED** [review]
I tested on Chrome 107.0.5304.110, Firefox 106.0.5, Safari 16.0 (17614.1.25.9.10, 17614) and Edge 107.0.1418.42 on Windows 10 and macOS 12.6.1 (21G215). 
There have been no additional failed tests beyond those already known. 

On Chrome I had 3 or 6 fake bad results with e2e, but when run separately they were green.  Even when the browser did not store cache, there were false results when running tests in bulk. 

False failing tests:
```
[Comments](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments) > [updateSettings](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments%20updateSettings) > [should change delay, after which comment is showed #4323](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments%20updateSettings%20should%20change%20delay%2C%20after%20which%20comment%20is%20showed%20%234323)
Expected ‘none’ to equal ‘block’.
Error: Expected ‘none’ to equal ‘block’.
    at <Jasmine>
    at _callee$ (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:106400:55)
    at tryCatch (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:23009:17)
    at Generator.<anonymous> (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:23090:22)
[Comments](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments) > [Displaying comment after `mouseover` event](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments%20Displaying%20comment%20after%20%60mouseover%60%20event) > [should display comment after predefined delay when custom `displayDelay` option of `comments` plugin is not set](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments%20Displaying%20comment%20after%20%60mouseover%60%20event%20should%20display%20comment%20after%20predefined%20delay%20when%20custom%20%60displayDelay%60%20option%20of%20%60comments%60%20plugin%20is%20not%20set)
Expected ‘none’ to be ‘block’.
Error: Expected ‘none’ to be ‘block’.
    at <Jasmine>
    at _callee7$ (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:106696:55)
    at tryCatch (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:23009:17)
    at Generator.<anonymous> (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:23090:22)
[Comments](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments) > [Displaying comment after `mouseover` event](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments%20Displaying%20comment%20after%20%60mouseover%60%20event) > [should display comment after defined delay when custom `displayDelay` option of `comments` plugin is set](http://10.0.0.12:5000/handsontable/test/E2ERunner?spec=Comments%20Displaying%20comment%20after%20%60mouseover%60%20event%20should%20display%20comment%20after%20defined%20delay%20when%20custom%20%60displayDelay%60%20option%20of%20%60comments%60%20plugin%20is%20set)
Expected ‘none’ to be ‘block’.
Error: Expected ‘none’ to be ‘block’.
    at <Jasmine>
    at _callee8$ (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:106738:43)
    at tryCatch (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:23009:17)
    at Generator.<anonymous> (http://10.0.0.12:5000/handsontable/test/dist/e2e.entry.js:23090:22)
```

I'm giving the green light as this PR solves #9960.

I like the new progress bar option. It is useful that you can also click failing tests from it and check them one at a time without having to wait for the whole process.

**Pull request merged**
