### PR TITLE
Stop crashing when the one of the links in a dot-noteted "data" property of the "columns" option is null

### PR DESCRIPTION
**Pull request by sakalys**
### Context
This PR makes sure Handsontable functions as expected (without crashing) when one of the links in a dot-noteted "data" property of the "columns" option is null.

### How has this been tested?
Spec added.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:
- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by sakalys** [comment]
I was not sure if I must push the build, si I didn't. Let me know if it's ok to push it.

**Comment by sakalys** [comment]
Also, this i guess this fix is a patch, so I should make the PR to "master" branch?

**Comment by AMBudnik** [comment]
Hi @sakalys 
Thank you for your effort to share a PR. We check only PR made to develop branch however I see that some tests have failed.

Can you also attach a simple demo where we'll be able to get currently existing unwanted behavior?

**Comment by sakalys** [comment]
The failing checks were in the development branch before my commit. I would like not to add the demo as I  have added a spec (test) for this PR. It demonstrates the issue clearly. If you really really really need a demo, then I'll think of something :)

**Comment by sakalys** [comment]
People, can we up this issue? This is really important for my client.

As for the Travis build... It fails, because the main 'develop' branch fails, not because this PR breaks it.

**Comment by sakalys** [comment]
Alright, I pushed the build files. Everything is passing :+1:

**Comment by AMBudnik** [comment]
Sorry for a delay @sakalys 

as mentioned at https://github.com/handsontable/handsontable/pull/3998 we are currently put on hold with PR as we are waiting for the Contributor Agreement.

**Comment by AMBudnik** [comment]
Hi @mpetris 

Thank you very much for sharing the pull request with us!

Yesterday we have changed the Contributing policy, a new file can be found [here](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md). As you can see the first obligatory step is to sign a CLA document that will allow us to check your code and (if it meets project requirements) merge it to Handsontable.

As most of the PR in our repository are 3 months+ old we have decided to close them all and reopen immediately after the author confirms that all the steps of the [Contributing file](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) have been accomplished. 
In the same time, I am really sorry that we have waited so long to provide the correct pull request process. I hope that now we will be able to build the perfect library together :)

ps. if you have added more than one pull request please share all their numbers in one post. Thanks in advance!

**Pull request closed without merging**
