### PR TITLE
New docs: change styles for "edit" button and fix button styles across pages

### PR DESCRIPTION
**Pull request by Osky772**
Change styles for the "Edit" button and fix other button styles across pages

### CODE REVIEW

**Review by Siemienik — COMMENTED** [review]
Hi, thank you for this PR. I found an issue on this branch

### feature/issue-7624-fix-styling

image

### feature/issue-7624

image

I suppose that you haven't got the never version of the new docs. Could you please update a branch?

**Review by Siemienik — CHANGES_REQUESTED** [review]
**Before:**

image

**After:**

image


Is it desirable?

**Comment by Osky772** [comment]
> **Before:**
> 
> image
> 
> **After:**
> 
> image
> 
> Is it desirable?

Yes, because HTML in the demos should have its own styles

**Comment by Osky772** [comment]
@Siemienik the branch has been updated now

**Comment by Siemienik** [comment]
> Yes, because HTML in the demos should have its own styles
cc @krzysztofspilka is that right? Could you confirm it, please?

**Comment by Osky772** [comment]
> > Yes, because HTML in the demos should have its own styles
> 
> cc @krzysztofspilka is that right? Could you confirm it, please?

You can see the discussion about this topic here https://handsoncode.slack.com/archives/C01KNSJ4M08/p1622622549003500

**Comment by krzysztofspilka** [comment]
It looks not attractive. Let's get back to what we had before that. If the demo needs some special treatment then we can still overwrite the global styles, that's not a problem at all. It's just CSS after all:)

**Comment by Osky772** [comment]
CLosed in favor of #8218

**Pull request closed without merging**
