### PR TITLE
Fix extra \r in pasted data

### PR DESCRIPTION
**Pull request by JSalter02**
### Context

Pasted data from windows (i.e. from Excel, or anywhere) includes an extra \r that is visible when you edit the cell. It is trimmed away after editing, but causes serious problems if it remains.

### How has this been tested?

I verified that this properly splits on \r (Mac), \n (Linux), or \r\n (Windows)

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #5477 

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing the pull request.

Can you change the branch to `develop`? We do not pull changes made to `master` branch. The pull request also requires additional tests. I also do not see a [CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1) being signed.

Without those points being accomplished I won't be able to schedule a code review.

**Comment by JSalter02** [comment]
Cancelling this one and making a new one.

**Comment by JSalter02** [comment]
Because I'm getting some stray commits included from master branch, I'm trying to close this pull request and open a new one. Github is behaving strangely. I'll try again later if it doesn't show up.

**Comment by AMBudnik** [comment]
@JSalter02 yes, GH is really awful today.
Some of our developers can'r even log in.

**Comment by JSalter02** [comment]
New one is:
https://github.com/handsontable/handsontable/pull/5537

I signed a CLA last time I contributed. 
https://github.com/handsontable/handsontable/pull/5259

I don't see any existing tests for SheetClip to add this to. It's enough that I'm debugging your code for free - I think you guys can come up with whatever tests you want.

**Comment by AMBudnik** [comment]
Thank you @JSalter02 

I will ask about the tests

**Pull request closed without merging**
