### PR TITLE
Feature/issue 588

### PR DESCRIPTION
**Pull request by ziaulrehmandevsinc**
### Context
If we need to manipulate or change our data before it is being pasted, we need a beforePaste hook, in which we will be able to convert/parse our data, for instance to match the type of data already in cell, we cant do it in before change because onPaste function checks for data type compatibilty itself, and if it is not same, it just rejects the change and beforeChange is never called.

### How has this been tested?
We needed this hook in our project, where we were storing custom objects in background and were displaying its specific property using custom editor. We were manipulating input string to object in before change and in editor setValue etc. Now, we needed to paste data from excel or any other source, and to process this data to object there was no method available, so we created this hook to convert/parse input before pasting it

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. 588
2. 862

### Checklist:
- [x] My code follows the code style of this project,
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by frontyard** [comment]
Same as my PR from year ago:
https://github.com/handsontable/handsontable/pull/2876
Maybe you can extract a unit test from it?

**Comment by ziaulrehmandevsinc** [comment]
@frontyard thats strnge, your PR seems much better than mine, that or any of its variants should had been approved. I believe many people like me are forced to use custom modified handsontable. Its a shame as issue 588 ks from 2013.

**Comment by AMBudnik** [comment]
Hi @ziaulrehmandevsinc @frontyard 
we do not accept PR to `master`, only to `develop`
ps. if you would like the PR to be pulled please create Fiddle that describes the issue that is fixed and add tests.

**Comment by ziaulrehmandevsinc** [comment]
@frontyard  your PR is absolutely more complete and better than mine, so i would say you should try doing what he requires. I hope your PR will be accepted.

**Comment by AMBudnik** [comment]
Hi @ziaulrehmandevsinc 

Thank you for your input.

We have added `beforePaste` hook in v0.31.1 https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:beforePaste

Sorry for not accepting PRs. We were informed by our lawyer that we need a written permission to use PR code and the document is not in our hands.

**Comment by ziaulrehmandevsinc** [comment]
Thank-you @AMBudnik  for the addition,
though me making PR is enough proof that it is my consent in sharing code, anyway. Good to hear about addition. Thanks.

**Comment by AMBudnik** [comment]
@ziaulrehmandevsinc it was a good way to merge code in November 2016 but as we released [a commercial version of a software](https://handsontable.com/pricing.html) which uses Community Edition (this one on Github) the process got a little bit more complicated. 
However, it is great to know that we have active contributors. It means that we did a good job with the software in general.

Thank you again and wish you a great day.

**Pull request closed without merging**
